package.json, src/botonic.ts, src/commands/webview.ts, src/index.ts, src/pages/webview.js, tsconfig.json
Upgrade next to version 6.0.4-canary.9, react and react-dom to 16.4.1 and new logic for Facebook Webviews.
=> Webviews feature

packages/botonic-react/src/components/carousel.jsx, packages/botonic-react/src/components/location.jsx, packages/botonic-react/src/components/message.jsx, packages/botonic-react/src/utils.js
Add new function in order to decompose all types of components and store it in the localStorage of the browser
=> decompose Components for keeping browser bot session

packages/botonic-react/src/webview.jsx
Redirects to chat when closing a webview on WhatsApp
=> feat: Support for whatsapp webviews

packages/botonic-react/package.json, packages/botonic-react/src/components/audio.jsx, packages/botonic-react/src/components/carousel.jsx, packages/botonic-react/src/components/document.jsx, packages/botonic-react/src/components/image.jsx, packages/botonic-react/src/components/video.jsx
Fix error os last release. Some components were failing with the renderNode function
=> fix(react): error of release 0.8

packages/botonic-core/index.d.ts, packages/botonic-core/src/handoff.js, packages/botonic-core/src/index.js, packages/botonic-core/src/router.js, packages/botonic-plugin-contentful/src/cms/cms.ts, packages/botonic-plugin-contentful/src/cms/model.ts, packages/botonic-plugin-contentful/src/contentful/text.ts, packages/botonic-plugin-contentful/src/render/render.tsx, packages/botonic-plugin-contentful/tests/render/render.test.tsx, packages/botonic-react/index.d.ts
* add call to backend to store a case rating
* add flag to cms.Text to show buttons as replies
=> Case rating when getting back from human handoff

packages/botonic-core/index.d.ts, packages/botonic-core/src/handoff.js, packages/botonic-core/src/index.js, packages/botonic-core/src/router.js, packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-contentful/src/cms/cms.ts, packages/botonic-plugin-contentful/src/cms/model.ts, packages/botonic-plugin-contentful/src/contentful/button.ts, packages/botonic-plugin-contentful/src/contentful/text.ts, packages/botonic-plugin-contentful/src/index.ts, packages/botonic-plugin-contentful/src/keywords/index.ts, packages/botonic-plugin-contentful/src/nlp/keywords.ts, packages/botonic-plugin-contentful/src/render/render.tsx, packages/botonic-plugin-contentful/tests/contentful/text.test.ts, packages/botonic-plugin-contentful/tests/index.test.ts, packages/botonic-plugin-contentful/tests/render/render.test.tsx, packages/botonic-react/index.d.ts
* Get different Text from CMS when no keyword detected in input text.
* new CMS model type "payload". Useful for buttons which just need to submit a payload.
=> treatment of no keywords founds in input text

packages/botonic-plugin-dashbot/package-lock.json, packages/botonic-plugin-dashbot/package.json, packages/botonic-plugin-dialogflow/package-lock.json, packages/botonic-plugin-dialogflow/package.json, packages/botonic-plugin-dialogflow/src/index.js
Function that allows calling dialogflow manually inside a bot to change the input of it. 
Example:
```
let newInput = 'this is a new text'
await dialogflow.apiCall(newInput, { input, session, lastRoutePath })
```
It updates the input of the bot on success.
=> feat(plugin-dialogflow): Allow doing api calls directly

packages/botonic-plugin-contentful/src/cms/cms-dummy.ts, packages/botonic-plugin-contentful/src/cms/cms-error.ts, packages/botonic-plugin-contentful/src/cms/cms.ts, packages/botonic-plugin-contentful/src/cms/contents.ts, packages/botonic-plugin-contentful/src/contentful/delivery-api.ts, packages/botonic-plugin-contentful/src/contentful/index.ts, packages/botonic-plugin-contentful/src/contentful/keywords.ts, packages/botonic-plugin-contentful/src/contentful/queue.ts, packages/botonic-plugin-contentful/src/contentful/schedule.ts
=> Contentful queue

packages/botonic-cli/src/botonicAPIService.ts, packages/botonic-core/package-lock.json, packages/botonic-core/src/core-bot.js, packages/botonic-react/index.d.ts, packages/botonic-react/src/utils.js
Small changes in react & core some related to typescript & contentful
=> Sdk capabilities dani

packages/botonic-react/package.json, packages/botonic-react/src/components/button.jsx, packages/botonic-react/src/components/message.jsx, packages/botonic-react/src/webchat/header.jsx, packages/botonic-react/src/webchat/menu.jsx, packages/botonic-react/src/webchat/messageList.jsx, packages/botonic-react/src/webchat/webchat.jsx, packages/botonic-react/src/webchat/webchatDev.jsx
webchat can receive custom components from bots and apply it
=> Webchat style setup

packages/botonic-core/index.d.ts, packages/botonic-plugin-luis/package.json, packages/botonic-plugin-luis/src/index.js, packages/botonic-react/index.d.ts
- changed LUIS plugin format of intents to rename score to confidence
- improve typings of core and react
=> Change LUIS plugin intents.score and improve types

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-plugin-contentful/README_wip.md, packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-contentful/src/contentful/button.ts, packages/botonic-plugin-dynamodb/README.md, packages/botonic-plugin-dynamodb/README_wip.md, packages/botonic-plugin-dynamodb/package-lock.json, packages/botonic-plugin-dynamodb/package.json, packages/botonic-react/index.d.ts, packages/botonic-react/package-lock.json, packages/botonic-react/package.json
=> Contentful/dynamo/core/react release with sdk-capabilities 

packages/botonic-react/src/dev-app.jsx, packages/botonic-react/src/webchat/webchat.jsx
With the help of Eric we have improve the readability and the efficiency of the previous function. We've split it in two functions to distinguish which functionality is which one.
=> refactor: sendInput function refactorized for not repeating code

packages/botonic-react/src/webchat/webchat.jsx
Friday with Eric we realized this function was creating a bug. It shows the payload when user press a button of a carousel
=> fix: remove function that was created only for testing

packages/botonic-react/src/webchat-app.jsx, packages/botonic-react/src/webchat/header.jsx
With Arnau when we have deployed the bot for hp, we realized two wrong behavior that didn't appear with botonic serve.
=> add: fixing some issues

packages/botonic-react/src/components/message.jsx
I've centered the position of the bot logo.
=> fix(react/message.jsx): bot logo position center

packages/botonic-react/src/webchat/header.jsx, packages/botonic-react/src/webchat/webchat.jsx
If we don't want to create a customize header and we only want to change the image header, title or subtitle now we can by checking if user passes from index.html
=> add(react/header): new customitzation features on default header

packages/botonic-react/src/webchat/webchat.jsx, packages/botonic-react/src/webchat/webview.jsx
=> Allow to have config style in the webview div

packages/botonic-react/src/components/carousel.jsx, packages/botonic-react/src/components/message.jsx, packages/botonic-react/src/webchat/header.jsx, packages/botonic-react/src/webchat/webchat.jsx
I refactored the styles of the header component to be 100% responsive.
=> feat(react/header-style): header styles refactor

.editorconfig, .prettierrc, packages/botonic-plugin-contentful/.prettierrc, packages/botonic-plugin-dynamodb/.prettierrc
=> chore: editorconfig config file and common .prettierc

packages/botonic-core/src/handoff.js, packages/botonic-core/src/handoff.test.js, packages/botonic-core/src/router.js, packages/botonic-core/src/router.test.js
Revert part of  #382 
on_finish handoff path again within payload with __PATH_PAYLOAD__ prefix
=> revert(core): on_finish handoff path again within payload

packages/botonic-plugin-dynamodb/.eslintrc.js, packages/botonic-plugin-dynamodb/package-lock.json, packages/botonic-plugin-dynamodb/package.json, packages/botonic-plugin-dynamodb/src/domain/dummy.ts, packages/botonic-plugin-dynamodb/src/domain/exceptions.ts, packages/botonic-plugin-dynamodb/src/domain/track.ts, packages/botonic-plugin-dynamodb/src/index.ts, packages/botonic-plugin-dynamodb/src/infrastructure/dynamo.ts, packages/botonic-plugin-dynamodb/tests/domain/time.test.ts, packages/botonic-plugin-dynamodb/tests/domain/track.test.ts, packages/botonic-plugin-dynamodb/tests/helpers/dynamo.ts, packages/botonic-plugin-dynamodb/tests/helpers/jest.ts, packages/botonic-plugin-dynamodb/tests/infrastructure/dynamo.integration.test.ts
Allow configuring the Dynamo timeouts
=> Dynamo/timeouts 0.10.0

packages/botonic-plugin-contentful/.eslintrc.js, packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json
minor dependency upgrades
specify node 12
=> chore(contentful): 0.10 release

packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-contentful/src/nlp/normalizer.ts, packages/botonic-plugin-contentful/src/nlp/similar-words.ts, packages/botonic-plugin-contentful/src/nlp/stemmer.ts, packages/botonic-plugin-contentful/src/nlp/stemmers/polish-stemmer.ts, packages/botonic-plugin-contentful/src/nlp/tokens.ts, packages/botonic-plugin-contentful/src/tools/search-performance.ts, packages/botonic-plugin-contentful/src/typings.d.ts, packages/botonic-plugin-contentful/tests/contentful/keywords.test.ts, packages/botonic-plugin-contentful/tests/nlp/similar-words.test.ts, packages/botonic-plugin-contentful/tests/nlp/stemmer.test.ts, packages/botonic-plugin-contentful/tests/nlp/stemmers/polish-stemmer.test.ts
Required to avoid a excessive cpu usage when finding similar substrings in long sentences
=> upgrade to nlp4

packages/botonic-core/src/core-bot.js, packages/botonic-core/src/plugins.js, packages/botonic-react/src/node-app.jsx
Hi all! This PR is related to: https://github.com/metis-ai/hubtype-backend/pull/87
In this PR I added the method `getConfig` to be called from the lambda function in order to retrieve the plugins that the user has integrated in his bot.
=> feat: getting plugins config from lambda

docs/3.main-concepts/7.humanhandoff.mdx, packages/botonic-core/index.d.ts, packages/botonic-core/src/handoff.js
Updated version of this [PR](https://github.com/hubtype/botonic/pull/419)
=> feat: add new getAvailable of all organization

packages/botonic-plugin-contentful/package.json
revert eslint plugin not compatible with eslint 5
=> chore: fix contentful eslint

.dependabot/config.yml, packages/botonic-cli/README.md, packages/botonic-cli/package-lock.json, packages/botonic-cli/package.json, packages/botonic-cli/templates/blank/package.json, packages/botonic-cli/templates/childs/package.json, packages/botonic-cli/templates/custom-webchat/package.json, packages/botonic-cli/templates/dynamic-carousel/package.json, packages/botonic-cli/templates/handoff/package.json, packages/botonic-cli/templates/intent/package.json, packages/botonic-cli/templates/nlu/package.json, packages/botonic-cli/templates/tutorial/package.json, packages/botonic-nlu/package.json, packages/botonic-plugin-contentful/src/cms/test-helpers/builders.ts, packages/botonic-plugin-contentful/src/render/botonic-converter.ts, packages/botonic-plugin-contentful/tests/render/botonic-converter.test.ts
* also added unit test
* minor improvements in text builders
=> fix: BotonicMsgConverter was not using replaceEmptyStringsWith option value

packages/botonic-plugin-contentful/tests/contentful/contents/carousel.test.ts, packages/botonic-plugin-contentful/tests/contentful/contents/text.test.ts, packages/botonic-plugin-contentful/tests/contentful/ignore-fallback-decorator.test.ts
In contentful.com's test contents, some fields had the Spanish
text in the English locale.
After fixing, test asserts had to be adapted
=> test(contentful): adapt to changes in contentful contents

packages/botonic-core/package-lock.json, packages/botonic-core/package.json
Alpha including get vacation ranges for agent: https://github.com/hubtype/botonic/pull/688
=> chore(core): bump to 0.11.2-alpha.1

docs/1.introduction/1.index.mdx, docs/2.getting-started/2.getting-started.mdx, docs/3.tutorials/3.create-convapp.mdx, docs/4.templates/1.templates.mdx, docs/4.templates/2.template-custom-webchat.mdx, docs/4.templates/3.childs.mdx, docs/4.templates/4.template-dynamic-carousel.mdx, docs/4.templates/5.template-human-handoff.mdx, docs/4.templates/6.template-nlu.mdx, docs/5.concepts/10.actions.mdx, docs/5.concepts/11.botonic_settings.mdx, docs/5.concepts/12.components.mdx, docs/5.concepts/14.humanhandoff.mdx, docs/5.concepts/15.i18n.mdx, docs/5.concepts/16.nlu.mdx, docs/5.concepts/17.routes.mdx, docs/5.concepts/18.webchat.mdx, docs/5.concepts/19.webviews.mdx, docs/6.supported-platforms/20.supported-platforms.mdx, docs/7.plugins/21.botonic-plugins.mdx, docs/7.plugins/22.using-plugins.mdx, docs/7.plugins/23.plugin-contentful.mdx, docs/8.project/project-structure.mdx, docs/9.test-deploy/1.testing-your-components.mdx, docs/9.test-deploy/2.deployment.mdx
Fix numbering issues in docz prod build. (Already deployed, **doesn't need revision**, put it separated the changes in this branch).
It's very likely we are moving to a better documentation tool like docusaurus nearly.
=> fix: fix numbering issues in prod build

packages/botonic-core/index.d.ts
* Fixed a pair of outdated definitions
=> fix: fix HandoffBuilder definitions

packages/botonic-core/index.d.ts
Add more types to core/index.d.ts
**Please review InputType, as I'm not sure about it**
=> chore(core): add types for input type, plugin constructor and config

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-core/src/index.js
* Adding missing types.
* Bump @botonic/core to 0.11.3-rc.2
Test are failing in #756 as I need at least these types published into npm to pass the tests.
=> chore(core): add missing types and bump to next rc

packages/botonic-plugin-inbenta/README.md, packages/botonic-plugin-inbenta/package-lock.json, packages/botonic-plugin-inbenta/package.json, packages/botonic-plugin-inbenta/src/index.js
Adding a new package `@botonic/plugin-inbenta` to integrate the Inbenta Knowledge Management API. Please refer to the README in this PR for more information.
This is an improvement needed for our COVID Whatsapp bot for Generalitat.
=> feat: add new package botonic-plugin-inbenta

packages/botonic-plugin-dialogflow/package-lock.json, packages/botonic-plugin-dialogflow/package.json, packages/botonic-plugin-dialogflow/src/index.js, packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/components/message.jsx, packages/botonic-react/src/webchat/webchat.jsx
* This dependency was quite out of date, updating it manually as it has breaking changes, see #771.
=> chore: update uuid deps manually

scripts/bump-version.sh, scripts/prepare-packages.sh
* Created a script for automatically clean, install and build every project.
* Created a script for automatically update all package versions given a version number.
I have adapted the script Dani did to speed up the publishment process with these two helpful scripts.
e.g.: `./bump-version.sh 0.13.0` will update all packages to `0.13.0` version.
=> chore: scripts for easier maintainance

packages/botonic-nlu/package-lock.json, packages/botonic-nlu/package.json, packages/botonic-plugin-nlu/package-lock.json, packages/botonic-plugin-nlu/package.json
* Update deps and freeze them to latest stable tfjs deps (1.7.3), as it won't work with v1.7.4 due to https://github.com/justadudewhohacks/face-api.js/issues/615. 
* ~Update and test manually sqlite-async update: https://github.com/hubtype/botonic/pull/798~
* **Updated**: latest version of `sqlite-async` updates its `sqlite3` to non guaranteed cross-platform deps. Freeze it to `1.0.11`
Project maintenance, with incoming NLU will try to update to 2.0.0 (it introduces breaking changes).
=> chore(nlu/plugin-nlu): update tfjs deps

packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/components/message.jsx, packages/botonic-react/src/constants.js, packages/botonic-react/src/dev-app.jsx, packages/botonic-react/src/webchat-app.jsx, packages/botonic-react/src/webchat/webchat.jsx, packages/botonic-react/tests/webchat.theme.test.js
* Deep merging of `theme` properties at top-level in order to have properly merged the properties coming from `webchat/index.js` and the ones defined in `index.html`.
* Refactor `mobile` webchat configs and allow `mobileStyle` 
* Add message classNames to every message to be able to select them via css/scss.
Little improvements needed for some projects
* Using lodash.merge method in the same way we do it inside `webchat.jsx`
* Having classNames for messages.
=> fix(react): minor improvements

doc-botonic/docs/components/components-carousel.md, doc-botonic/docs/concepts/10.actions.md, doc-botonic/docs/concepts/14.humanhandoff.md, doc-botonic/docs/concepts/17.routes.md, doc-botonic/docs/concepts/18.webchat.md, doc-botonic/docs/concepts/19.webviews.md, doc-botonic/docs/create-convapp.md, doc-botonic/docs/getting-started.md, doc-botonic/docs/plugins/21.botonic-plugins.md, doc-botonic/docs/plugins/22.using-plugins.md, doc-botonic/docs/plugins/plugin-contentful.md, doc-botonic/docs/plugins/plugin-nlu.md, doc-botonic/docs/project-structure.md, doc-botonic/docs/supported-platforms.md, doc-botonic/docs/templates/1.templates.md, doc-botonic/docs/templates/2.template-custom-webchat.md, doc-botonic/docs/templates/3.childs.md, doc-botonic/docs/templates/4.template-dynamic-carousel.md, doc-botonic/docs/templates/5.template-human-handoff.md, doc-botonic/docs/test-deploy/1.testing-your-components.md, doc-botonic/docs/test-deploy/2.deployment.md, doc-botonic/docs/welcome.md
Fixed English typos in Botonic documentation throughout the site. Please check if everything's fine. Thanks.
=> docs: typos fixed

packages/botonic-cli/templates/tutorial/src/actions/carousel.js
=> refactor: Fixes misspelling of "carrousel" to "carousel"

packages/botonic-react/src/components/index.d.ts, packages/botonic-react/src/components/webchat-settings.jsx, packages/botonic-react/src/dev-app.jsx, packages/botonic-react/src/webchat-app.jsx, packages/botonic-react/src/webchat/webchat.jsx
* Improve `index.d.ts` with definitions.
* Pass missing `animationsEnabled` prop.
Added while doing documentation review in: https://github.com/hubtype/botonic/pull/822
=> fix: improvements from docs review

packages/botonic-core/src/index.d.ts
Add `imp_id` attribute inside `SessionUser` interface on the @core package.
- [ X ] doesn't need tests because... **[provide a description]**
=> fix: add imp_id option inside SessionUser interface

CHANGELOG.md
WIP changelog to be added in the next Botonic release.
=> wip: prepare changelog for 0.14.0 release

packages/botonic-react/package-lock.json, packages/botonic-react/src/components/button.jsx, packages/botonic-react/src/components/index.d.ts, packages/botonic-react/src/components/message.jsx, packages/botonic-react/src/msg-to-botonic.jsx, packages/botonic-react/src/webchat/components/persistent-menu.jsx
New prop for the Button to define the target of a url that allows to open the url in the same tab
Until now all url where opened in a new tab 
Add a target to `window.open`, by default it will be `_blank` (new tab)
Add a prop to the button named `target` that allows to open urls in the same tab, by default it will be open in a new tab (`_blank`) but it can also be `_blank`, `_self`,` _parent`, `_top` or `framename` https://www.w3schools.com/tags/att_a_target.asp
Example:
``` 
<Button url='https://botonic.io' target={‘_blank'|'_self'|'_parent'|'_top'|'framename’}>Botoni …
```
=> feat(react): target url button

.github/pull_request_template.md, packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/webchat/webchat.jsx
* Missing deep merge.
* Downgrade react-textarea-autosize causing styling issues to 7.1.2.
=> fix(react): missing deep merge user-session refs

packages/botonic-core/src/index.d.ts, packages/botonic-react/src/components/index.d.ts, packages/botonic-react/src/contexts.jsx, packages/botonic-react/src/index.d.ts
* add coverComponent missing type
* update webchatContext available methods
* add types for WebchatApp and WebchatDevApp 
Keep adding types for facilitating our dev workflows and be easier to migrate in the future.
=> chore(react): improve and sort typings for webchat app and contexts

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-core/src/index.d.ts
* add missing field to HubtypeAgentsInfo
* added type for routes function. Useful to pass it around
=> feat(core): minor fixed in types

packages/botonic-plugin-contentful/src/cms/cms-dummy.ts, packages/botonic-plugin-contentful/src/cms/cms-error.ts, packages/botonic-plugin-contentful/src/cms/cms-log.ts, packages/botonic-plugin-contentful/src/cms/cms-multilocale.ts, packages/botonic-plugin-contentful/src/cms/cms.ts, packages/botonic-plugin-contentful/src/cms/transform/cms-filter.ts, packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts, packages/botonic-plugin-contentful/src/contentful/contents/button.ts, packages/botonic-plugin-contentful/tests/contentful/contents.test.ts, packages/botonic-plugin-contentful/tests/contentful/contents/button.test.ts, packages/botonic-plugin-contentful/tests/contentful/contents/text.test.ts
new CMS method to deliver a content from id when we don't know the type
=> feat(contentful): new CMS.content

packages/botonic-react/src/components/text.jsx, packages/botonic-react/tests/components/__snapshots__/text.test.jsx.snap, packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-carousel-multibutton.test.jsx.snap, packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-carousel.test.jsx.snap, packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-text.test.jsx.snap, packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-wrapper.test.jsx.snap
* Fixed error appearing in some tests: `Received true for a non-boolean attribute markdown`. Caused by styled-components: https://github.com/styled-components/styled-components/issues/1198#issue-262022540
* Updated snapshots
=> fix(react): fix non-boolean attribute test

packages/botonic-react/package.json, packages/botonic-react/src/webchat/components/attachment.jsx, packages/botonic-react/src/webchat/components/emoji-picker.jsx, packages/botonic-react/src/webchat/components/persistent-menu.jsx, packages/botonic-react/src/webchat/components/send-button.jsx, packages/botonic-react/src/webchat/components/typing-indicator.jsx, packages/botonic-react/src/webchat/header.jsx, packages/botonic-react/src/webchat/message-list.jsx, packages/botonic-react/src/webchat/webchat.jsx, packages/botonic-react/tests/webchat/webchat.component.test.jsx
Tests for the webchat component.
Add roles to some of the webchat components to be able to get them in the tests.
=> test(react): add webchat component tests #BOT-31

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-core/src/index.d.ts, packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/components/index.d.ts
fix types of core & react index.dts
=> chore: fix types for isMobile, mobileStyle & webchat button

packages/botonic-nlu/package-lock.json, packages/botonic-nlu/package.json, packages/botonic-plugin-nlu/package-lock.json, packages/botonic-plugin-nlu/package.json, packages/botonic-plugin-nlu/src/model-handler.ts
Upgrade manually to tfjs 2.7.0 and fix issue with suggested detail.
=> chore(nlu/plugin-nlu): bump tfjs from 2.4.0 to 2.7.0

README.md, packages/botonic-react/README.md
Update README
Information was a bit outdated and some links/images broken
=> docs: update README

packages/botonic-core/src/router.js, packages/botonic-core/src/router.test.js
Fix a bug in getting child routes that was added in https://github.com/hubtype/botonic/pull/903. When the bot was receiving a payload like : payload: '__PATH __PAYLOAD_2' and also had a lastRoute the lastRoute wasn't being checked and it wasn't able to find the route.
=> fix(core): router

packages/botonic-cli/README.md, packages/botonic-cli/package-lock.json, packages/botonic-cli/package.json
`qs` dependency was missing in cli's package.json
=> chore(cli): add missing qs dependency, bump cli's alpha

docs/docs/welcome.md, docs/website/_redirects, docs/website/sidebars.json
Update Welcome page with:
* What is Botonic
* Features
* Alternatives
* Who uses Botonic
=> docs: update welcome page and sidebars

packages/botonic-core/src/index.d.ts, packages/botonic-core/src/index.js
* add session types for case status & resolution
* types for case resolution and status
=> chore(core): add _hubtype_case_status/typification fields

packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/webchat/hooks.js, packages/botonic-react/src/webchat/webchat.jsx, packages/botonic-react/tests/webchat/usewebchat.test.js
* Fixed webchatSettings not updating properly.
=> fix(react): webchat settings now are updated

packages/botonic-react/src/components/index.d.ts, packages/botonic-react/src/contexts.jsx, packages/botonic-react/src/index.d.ts, packages/botonic-react/src/util/index.d.ts, packages/botonic-react/src/webchat/index.d.ts
Added the following react typescript missing types:
- WebchatContext
- CoverComponent
- staticAsset
- isDev
- isProp
-
=> style(react): fix & add types

packages/botonic-react/src/components/multichannel/facebook/facebook.jsx, packages/botonic-react/src/components/multichannel/multichannel-text.jsx, packages/botonic-react/src/components/multichannel/multichannel-utils.js, packages/botonic-react/src/components/multichannel/multichannel.jsx, packages/botonic-react/src/constants.js, packages/botonic-react/tests/components/multichannel/facebook/facebook.test.jsx
Split the text when the provider is Facebook  and the number of characters is larger than 640
Facebook messenger allows a maximum of 640 characters per message
=> feat(react): multichannel Facebook text converter

packages/botonic-react/package-lock.json, packages/botonic-react/package.json
Bumping alpha to show @AinaVendrell how to publish packages and check `FacebookMultichannel` is working.
=> chore(react): bump alpha version

packages/botonic-core/src/router.js, packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/components/multichannel/deepmap-with-index.js, packages/botonic-react/src/util/environment.js, packages/botonic-react/src/util/index.d.ts, packages/botonic-react/src/util/react.js
* Independent branch from https://github.com/hubtype/botonic/pull/1159 (applied feedback)
* Remove react-children-utilities dependency 
* Removed unnecessary url import and refactored piece of code
=> chore(react): remove react-children-utilities dependency, remove url import

packages/botonic-plugin-contentful/bin/l10n/import-from-translators.sh, packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-contentful/src/contentful/export/space-export.ts, packages/botonic-plugin-contentful/src/tools/l10n/create-locale.ts, packages/botonic-plugin-contentful/src/tools/l10n/reference-field-duplicator.ts
* After #1118, csv import was broken due to a rename in LocaleInfo class field 
* Upgrade contentful-management and adapt renamed type
=> fix(contentful): import csv failed due after renaming LocaleInfo field

packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-contentful/src/cms/cms-error.ts, packages/botonic-plugin-contentful/src/cms/contents.ts, packages/botonic-plugin-contentful/src/cms/factories/content-factories.ts, packages/botonic-plugin-contentful/src/cms/test-helpers/builders.ts, packages/botonic-plugin-contentful/src/nlp/stemmer.ts, packages/botonic-plugin-contentful/src/nlp/tokens.ts, packages/botonic-plugin-contentful/tests/cms/cms-error.test.ts
fix(contentful): remove lazy .ts imports. it does not work from a bot when compiled with webpack
=> fix(contentful): fix lazy .ts imports

docs/docs/releases/v0-17-0.md, docs/website/sidebars.json
* Update docs with new release (already published site)
=> chore: update docs with new release

docs/docs/deployment/standalone-js-bundle.md
Updated Botonic Standalone JS deploy readme to address recent breaking changes from version 0.16.0 -> 0.17.0.
Following the minor version increase to 0.17.0 (and likely due to the updating of the webpack version), the instructions to deploy Botonic as a standalone JS bundle require updating. 
The full bug is described here:
Fixes [1199](https://github.com/hubtype/botonic/issues/1199)
In short, without these adjustments, the output file is incorrect.
Docs updated. Tested locally with both own project and "telco example" from [Botonic examples](https://github.com/hubtype/botonic-examples)
Main remaining question is whether the approach I detail passing in `webchat` to the `render` method of the `SelfHostedApp` class is advisable. It does work, but unsure if it is best practice/maintainable. …
=> docs: update standalone deploy readme

docs/docs/concepts/11.botonic_settings.md, docs/docs/concepts/19.webviews.md
In botonic-settings: removed deprecated info for NLU integrations
In webviews:  corrected typo
=> docs: removed deprecated info for NLU integrations and corrected typo

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-core/src/hubtype-service.js, packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/webchat/hooks.js, packages/botonic-react/src/webchat/webchat.jsx, packages/botonic-react/tests/helpers/test-utils.jsx, packages/botonic-react/tests/webchat/connection-issues.test.js
* Hotfix PR (published alpha) trying to fix some issues regarding connection.
* I have opted for using `connection-checker` library instead of relying on `navigator.onLine` (could not work for all browsers) adapting the current `useNetwork` hook.
* Bumped alpha version
* Bumped versions to 0.18.1
=> fix(core/react): fix connection issues with connection-checker, avoid resending duplicates

packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/src/cms/contents.ts, packages/botonic-plugin-contentful/src/contentful/contents/queue.ts, packages/botonic-plugin-contentful/tests/contentful/contents/queue.test.ts
Added a new field named handoffMessage in cms queue. This field is used to show a message before a handoff and it is placed in desk queue contentful content model.
=> Botonic plugin contentful: add handoffMessage field

README.md
- Banner added
- Twitter button added
- Links added on top of the page
- Reduced content to essential info
- Added supporters shortcuts
=> docs: readme file updated

docs/docs/components/components-button.md, docs/docs/concepts/14.humanhandoff.md, docs/docs/webchat/webchat-button-disable.md, docs/docs/webchat/webchat-style.md, docs/website/sidebars.json
The following files have been updated based on the new button disabling feature:
- components-button
- webchat-style
- sidebars 
The following file has been created:
- webchat-button-disable (with new images)
+ Also removed typos in humanhandoff file
=> docs: description of disabled button

packages/botonic-core/src/errors.js, packages/botonic-core/src/index.d.ts, packages/botonic-core/src/router.d.ts, packages/botonic-core/src/router.js, packages/botonic-core/src/router.test.js
* Improvements in core typings
* Improvements in Router types and tests
* Throw specialized exception if route not found and 404 route was not defined in bot
=> minor improments in Core/router

.gitignore, README.md, docs/docs/components/components-multichannel.md
2 doc-related updates:
- In the Multichannel component doc, the syntax example has been fixed.
- In the Readme GitHub file, 2 titles have been enhanced for better seo.
=> docs: fix example and add info in readme

packages/botonic-nlp/src/tasks/text-classification/models/constants.ts, packages/botonic-nlp/src/tasks/text-classification/models/simple-nn.ts, packages/botonic-nlp/src/tasks/text-classification/models/types.ts, packages/botonic-nlp/tests/helpers/tasks/text-classification/constants-helper.ts, packages/botonic-nlp/tests/tasks/text-classification/models/simple-nn.test.ts
Creation of the SimpleNN model template for Text Classification.
Implements the function that creates the Text Classifier template model.
Implement the `createSimpleNN` function.
``` 
const MAX_LENGTH = 12
const INTENTS = [ 'returnProduct', 'buyProduct', 'createOrder' ]
const embeddingsMatrix = ...
const model = createSimpleNN(MAX_LENGTH, INTENTS, embeddingsMatrix, {
units: 64,
learningRate: 0.01,
dropout: 0.12,
})
```
=> feat(nlp): Text Classification - Models

packages/botonic-plugin-contentful/src/contentful/manage/manage-contentful.ts, packages/botonic-plugin-contentful/src/manage-cms/manage-cms.ts, packages/botonic-plugin-contentful/src/tools/l10n/export-csv-for-translators.ts, packages/botonic-plugin-contentful/src/tools/l10n/import-csv-from-translators.ts
Improve documentation on --help of the contentful tools to export/import translators CSV
=> doc(contentful): improved help doc on export CSV

packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts, packages/botonic-nlp/src/tasks/text-classification/process/prediction-processor.ts, packages/botonic-nlp/tests/tasks/text-classification/botonic-text-classifier.test.ts, packages/botonic-nlp/tests/tasks/text-classification/process/prediction-processor.test.ts
Implementation of the class needed to process the model output.
We need to process the output tensor so we can obtain the intents and their confidences.
=> feat(nlp): Text Classification - PredictionProcessor

packages/botonic-nlp/src/preprocess/preprocessor.ts, packages/botonic-nlp/src/preprocess/types.ts, packages/botonic-nlp/src/tasks/ner/botonic-ner.ts, packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts, packages/botonic-nlp/tests/preprocess/preprocessor.test.ts
The `Preprocessor` class needs the following modifications:
- Create a new `preprocess` method that preprocesses a given text.
- Remove `paddingPosition` from class constructor.
- Split `pad` method into: `pad` and `truncate` methods.
These changes are required to improve the code.
=> refactor(nlp): Preprocessor

packages/botonic-plugin-contentful/exports/contentful-export.json, packages/botonic-plugin-contentful/tests/contentful/contents.test.ts, packages/botonic-plugin-contentful/tests/contentful/contents/carousel.test.ts, packages/botonic-plugin-contentful/tests/contentful/contents/text.test.ts, packages/botonic-plugin-contentful/tests/tools/validate-all-contents.test.ts
Remove some contents and reduce some texts from the contentful space used by integration tests
Less is more. Removed some stuff not used by tests
=> test(contentful): simplify contents in test space

packages/botonic-nlp/src/dataset/dataset.ts, packages/botonic-nlp/src/preprocess/vocabulary.ts, packages/botonic-nlp/src/utils/array-utils.ts, packages/botonic-nlp/tests/dataset/dataset.test.ts, packages/botonic-nlp/tests/preprocess/vocabulary.test.ts
Implementation of the `Vocabulary` class and the way the vocabulary is extracted from a `Dataset`.
We need an easy way of creating a vocabulary and using it.
The `Dataset` class can extract a `Vocabulary` by preprocessing its samples.
Also, the `Vocabulary` has some methods that will be used later by the Encoders.
How to create a `Vocabulary`:
```typescript
const vocabulary = new Vocabulary([ 'product', 'material', 'color' ])
``` 
Extract the `Vocabulary` from a `Dataset`:
```typescript
const vocabulary = dataset.extractVocabulary(preprocessor)
``` 
- Integrate `Vocabulary` class into `BotonicNER` and `BotonicTextClassifier`.
- Refactor `LabelEncoder` and `OneHotEncoder` to use `Vocabulary` class.
=> feat(nlp): Vocabulary class

packages/botonic-plugin-text-classification/jest.config.js, packages/botonic-plugin-text-classification/package-lock.json, packages/botonic-plugin-text-classification/package.json, packages/botonic-plugin-text-classification/src/constants.ts, packages/botonic-plugin-text-classification/src/index.ts, packages/botonic-plugin-text-classification/src/model/model-selector.ts, packages/botonic-plugin-text-classification/src/model/text-classifier.ts, packages/botonic-plugin-text-classification/src/types.ts, packages/botonic-plugin-text-classification/src/utils/locale-utils.ts, packages/botonic-plugin-text-classification/tsconfig.eslint.json, packages/botonic-plugin-text-classification/tsconfig.json
Following the top-down approach, the first thing has been to create the plugin configuration and the main class: `BotonicPluginTextClassification`.
=> feat(plugin-text-classification): BotonicPluginTextClassification implementation #BOT-342

packages/botonic-plugin-text-classification/src/index.ts, packages/botonic-plugin-text-classification/src/model/model-info.ts, packages/botonic-plugin-text-classification/src/model/model-selector.ts
**Depends on #1473.** Please, review it first. ⚠️ 
Implementation of the `ModelSelector` class which is responsible for loading the models and return the model corresponding to the specified locale.
=> feat(plugin-text-classification): Model Selector implementation #BOT-347

packages/botonic-plugin-text-classification/src/model/model-info.ts
**Depends on #1474.** Please, review it first. ⚠️ 
The `ModelInfo` class is responsible for getting the configuration and loading the model from the given uri.
=> feat(plugin-text-classification): ModelInfo implemented #BOT-348

packages/botonic-plugin-ner/package-lock.json, packages/botonic-plugin-ner/package.json, packages/botonic-plugin-ner/src/model/model-info.ts, packages/botonic-plugin-ner/src/model/ner.ts
Use a cross-environment fetch for NER plugin.
=> refactor(plugin-ner): Cross-fetch used #BOT-357

packages/botonic-plugin-text-classification/package-lock.json, packages/botonic-plugin-text-classification/package.json, packages/botonic-plugin-text-classification/src/model/model-info.ts, packages/botonic-plugin-text-classification/src/model/text-classifier.ts, packages/botonic-plugin-text-classification/src/process/prediction-processor.ts, packages/botonic-plugin-text-classification/src/process/text-processor.ts
**Depends on #1475 .** Please, review it first. ⚠️ 
The `TextClassifier` class is responsible for classifying a given text. 
This class takes the given text and:
1. Processes it to get the input tensor.
2. Uses the model to predict the output.
3. Processes the output so it returns a list with all possible intents and their corresponding confidences.
=> feat(plugin-text-classification): TextClassifier implemented #BOT-349

packages/botonic-plugin-text-classification/src/process/text-processor.ts
**Depends on #1476.** Please, review it first. ⚠️ 
The `TextProcessor` class is responsible for process the given text and generate the input tensor and its corresponding sequence.
We need the input tensor for the model prediction and the sequence for unmasking the decoded input tensor.
=> feat(plugin-text-classification): TextProcessor implemented #BOT-345

packages/botonic-plugin-text-classification/src/process/prediction-processor.ts
**Depends on #1477.** Please, review it first. ⚠️ 
The `PredictionProcessor` class is responsible for processing the model prediction and return an array of all possible intents sorted by confidence.
We need a class that processes the output tensor and gives to the user the prediction in a friendly format.
=> feat(plugin-text-classification): PredictionProcessor implemented #BOT-346

.github/workflows/botonic-plugin-text-classification-tests.yml, .pre-commit-config.yaml, codecov.yml
Tests from `plugin-text-classification` package have been enabled.
=> test(botonic): enable plugin-text-classification tests #BOT-363

packages/botonic-plugin-text-classification/README.md
Documentation of `plugin-text-classification`.
=> docs(plugin-text-classification): Plugin Documentation #BOT-372

.github/workflows/botonic-plugin-text-classification-tests.yml, .pre-commit-config.yaml, codecov.yml, packages/botonic-plugin-text-classification/README.md, packages/botonic-plugin-text-classification/jest.config.js, packages/botonic-plugin-text-classification/package-lock.json, packages/botonic-plugin-text-classification/package.json, packages/botonic-plugin-text-classification/src/constants.ts, packages/botonic-plugin-text-classification/src/index.ts, packages/botonic-plugin-text-classification/src/model/model-info.ts, packages/botonic-plugin-text-classification/src/model/model-selector.ts, packages/botonic-plugin-text-classification/src/model/text-classifier.ts, packages/botonic-plugin-text-classification/src/process/prediction-processor.ts, packages/botonic-plugin-text-classification/src/process/text-processor.ts, packages/botonic-plugin-text-classification/src/types.ts, packages/botonic-plugin-text-classification/src/utils/environment-utils.ts, packages/botonic-plugin-text-classification/src/utils/locale-utils.ts, packages/botonic-plugin-text-classification/tests/utils/locale-utils.test.ts, packages/botonic-plugin-text-classification/tsconfig.eslint.json, packages/botonic-plugin-text-classification/tsconfig.json
Feature branch containing the implementation of the `plugin-text-classification`.
**ALL COMMITS HAVE BEEN REVIEWED IN OTHER PRs.**
=> feat(plugin-text-classification): Text Classification Plugin implemented #BOT-344

packages/botonic-plugin-ner/README.md
Documentation of `plugin-ner`.
=> docs(plugin-ner): Plugin NER Documentation #BOT-322

packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json
Bumping alpha of the contentful plugin to use the new manage cms functions in the flow builder.
=> chore(plugin-contentful): bump alpha

packages/botonic-nlp/package-lock.json, packages/botonic-nlp/package.json, packages/botonic-plugin-intent-classification/package-lock.json, packages/botonic-plugin-intent-classification/package.json, packages/botonic-plugin-intent-classification/src/model/intent-classifier.ts, packages/botonic-plugin-intent-classification/src/process/prediction-processor.ts, packages/botonic-plugin-intent-classification/src/process/text-processor.ts, packages/botonic-plugin-ner/src/model/model-info.ts, packages/botonic-plugin-ner/src/model/ner.ts, packages/botonic-plugin-ner/src/process/prediction-processor.ts, packages/botonic-plugin-ner/src/process/text-processor.ts, packages/botonic-plugin-ner/tests/helper/tools-helper.ts, packages/botonic-plugin-ner/tests/process/prediction-processor.test.ts, packages/botonic-plugin-ner/tests/process/text-processor.test.ts
**Depends on #1525.** Please, review it first. ⚠️ 
Imports from both NLP plugins (plugin-ner & plugin-text-classification) have been updated. 
=> refactor(plugin-ner, plugin-text-classification): Update Plugins Imports #BOT-382

packages/botonic-plugin-ner/package-lock.json, packages/botonic-plugin-ner/package.json
Bump `botonic-nlp` alpha version.
=> chore(plugin-ner): bump nlp alpha version

packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/webchat/webchat.jsx
Remove parent div of the cover component. In case the developer wants to define a background, it can be defined in the cover component itself.
There was a div that was not accessible in the cover component that broke the layout sometimes.
=> Fix/remove parent div of cover component #BOT-384

packages/botonic-nlp/package-lock.json, packages/botonic-nlp/package.json, packages/botonic-nlp/src/model/model-info.ts, packages/botonic-nlp/src/model/model-selector.ts, packages/botonic-plugin-intent-classification/package-lock.json, packages/botonic-plugin-intent-classification/package.json, packages/botonic-plugin-ner/package-lock.json, packages/botonic-plugin-ner/package.json
Bump NLP alpha version. 
Also, as plugin-intent-classification and plugin-ner have nlp as dependency, we need to bump them too.
=> feat(nlp): bump alpha version

packages/botonic-plugin-contentful/README.md, packages/botonic-plugin-contentful/src/cms/cms.ts, packages/botonic-plugin-contentful/src/cms/contents.ts, packages/botonic-plugin-contentful/src/cms/factories/content-factories.ts, packages/botonic-plugin-contentful/src/cms/test-helpers/builders.ts, packages/botonic-plugin-contentful/src/manage-cms/fields.ts
Documentation on how to add a new model (content type) to contentful plugin
=> doc(contentful): doc to add new model

packages/botonic-plugin-intent-classification/tests/helper/constants-helper.ts, packages/botonic-plugin-intent-classification/tests/helper/tools-helper.ts, packages/botonic-plugin-intent-classification/tests/process/prediction-processor.test.ts, packages/botonic-plugin-intent-classification/tests/process/text-processor.test.ts
Tests added to `plugin-intent-classification`.
=> tests(plugin-intent-classification): tests added #BOT-457

packages/botonic-pulumi/package-lock.json, packages/botonic-pulumi/package.json, packages/botonic-pulumi/src/aws/deployment-stacks.ts, packages/botonic-pulumi/src/aws/dynamodb.ts, packages/botonic-pulumi/src/aws/index.ts, packages/botonic-pulumi/src/aws/nlp-models-bucket.ts, packages/botonic-pulumi/src/aws/policies.ts, packages/botonic-pulumi/src/aws/rest-server.ts, packages/botonic-pulumi/src/aws/static-webchat-contents.ts, packages/botonic-pulumi/src/aws/websocket-server-lambda.ts, packages/botonic-pulumi/src/aws/websocket-server.ts, packages/botonic-pulumi/src/index.ts, packages/botonic-pulumi/src/pulumi-downloader.ts, packages/botonic-pulumi/src/pulumi-runner.ts, packages/botonic-pulumi/src/system-utils.ts, packages/botonic-pulumi/tsconfig.json
* Added pulumi classes to handle deploying with pulumi in a headless way and Botonic AWS Components to have all the infrastructure uploaded to AWS.
* **Note:** 1st approach, some parts are susceptible to change.
`PulumiRunner` is the main class to handle all the logic (it is the one that will be used within the deploy script, probably in @botonic/cli). Given the config of the user, which can include the developer aws credentials, it will deploy the full-stack in two steps (due to some limitations with Pulumi, we couldn't handle to do it with a single component).
1. Run build commands for websocket server, rest server and webchat.
2. Deploying backend
* Deployment of DynamoDB database.
* Deployment of NLP models in a static s3 Bucket.
* Deployment of WebSocket Server (it will use …
=> feat(pulumi): add pulumi package to handle 1.0 deployments

packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-contentful/src/contentful/delivery/cache.ts
* Bump and publish plugin-contentful to alpha version to test added features
=> chore(plugin-contentful): bump and publish 0.19.0-alpha.5 version

packages/create-botonic-app/babel.config.json, packages/create-botonic-app/package-lock.json, packages/create-botonic-app/package.json, packages/create-botonic-app/src/create-botonic-app.js, packages/create-botonic-app/template/api/package.json, packages/create-botonic-app/template/api/src/parser.js, packages/create-botonic-app/template/api/src/rest/app.ts, packages/create-botonic-app/template/api/src/rest/index.js, packages/create-botonic-app/template/api/src/websocket/index.js, packages/create-botonic-app/template/api/src/websocket/onconnect.js, packages/create-botonic-app/template/api/src/websocket/ondisconnect.js, packages/create-botonic-app/template/api/src/websocket/onmessage.js, packages/create-botonic-app/template/api/tsconfig.json, packages/create-botonic-app/template/api/webpack.config.js, packages/create-botonic-app/template/bot/package.json, packages/create-botonic-app/template/bot/src/actions/Welcome.jsx, packages/create-botonic-app/template/bot/src/index.js, packages/create-botonic-app/template/bot/src/locales/index.js, packages/create-botonic-app/template/bot/src/nlp/tasks/intent-classification/train.ts, packages/create-botonic-app/template/bot/src/nlp/tasks/ner/train.ts, packages/create-botonic-app/template/bot/src/plugins.js, packages/create-botonic-app/template/bot/src/routes.js, packages/create-botonic-app/template/package.json, packages/create-botonic-app/template/tsconfig.json, packages/create-botonic-app/template/webchat/index.html, packages/create-botonic-app/template/webchat/index.js, packages/create-botonic-app/template/webchat/package.json, packages/create-botonic-app/template/webchat/webchat-config.js, packages/create-botonic-app/template/webchat/webpack.config.js
Adding a new package `create-botonic-app` to support the command
```
yarn create botonic-app myApp
```
It contains a template app with Botonic 1.0 alpha.
We want to support the tutorial in our blog post:
https://botonic.io/blog/2021/07/18/botonic10-preview/
The goal is to get early feedback from the community
```
yarn create botonic-app myApp
```
- doesn't need tests because...
=> feat: add new package create-botonic-app

packages/botonic-api/package-lock.json, packages/botonic-api/package.json, packages/botonic-api/src/data-provider/dynamodb-data-provider.ts, packages/botonic-api/src/data-provider/dynamodb-utils.ts, packages/botonic-api/src/data-provider/index.ts, packages/botonic-api/src/data-provider/local-data-provider.ts, packages/botonic-api/src/rest/index.ts, packages/botonic-api/src/rest/routes/bot-input.ts, packages/botonic-api/src/rest/routes/events.ts, packages/botonic-api/src/rest/routes/index.ts, packages/botonic-api/src/rest/routes/users.ts, packages/botonic-api/src/rest/routes/validation/events.ts, packages/botonic-api/src/websocket/aws-websocket-server.ts, packages/botonic-api/src/websocket/index.ts, packages/botonic-api/src/websocket/local-websocket-server.ts, packages/botonic-api/tsconfig.json
* Added first alpha version of @botonic/api package to handle common wrappers for local/aws infrastructures
=> Full stack/chore(api): add api package for botonic1.0

packages/botonic-nlp/package-lock.json, packages/botonic-nlp/package.json, packages/botonic-nlp/src/model/manager.ts, packages/botonic-nlp/src/tasks/intent-classification/botonic-intent-classifier.ts
This new parameter tries to solve the bad accuracy of an `IntentClassifier` model trained with unbalanced classes.
By setting `balanceClasses` to `true` when training an `IntentClassifier`, the training process will use `ClassWeight` to ponderate the loss function according to the class weights.
=> feat(nlp): Train with Unbalanced classes

packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-contentful/src/contentful/manage/manage-entry.ts, packages/botonic-plugin-contentful/src/manage-cms/fields.ts, packages/botonic-plugin-contentful/src/util/backoff.ts, packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-entry.test.ts
- Add missing `ContentFieldTypes` to be able to update the handoff fields
=> feat(plugin-contentful): add missing handoff ContentFieldTypes

packages/botonic-plugin-contentful/src/cms/callback.ts, packages/botonic-plugin-contentful/src/cms/cms-dummy.ts, packages/botonic-plugin-contentful/src/cms/cms-error.ts, packages/botonic-plugin-contentful/src/cms/cms-log.ts, packages/botonic-plugin-contentful/src/cms/cms-multilocale.ts, packages/botonic-plugin-contentful/src/cms/cms.ts, packages/botonic-plugin-contentful/src/cms/contents.ts, packages/botonic-plugin-contentful/src/cms/transform/cms-filter.ts, packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts, packages/botonic-plugin-contentful/src/contentful/contents/button.ts, packages/botonic-plugin-contentful/src/contentful/contents/callback-delivery.ts, packages/botonic-plugin-contentful/src/contentful/contents/payload.ts, packages/botonic-plugin-contentful/src/manage-cms/fields.ts, packages/botonic-plugin-contentful/src/util/backoff.ts, packages/botonic-plugin-contentful/tests/contentful/contents/payload.test.ts
- Add payload content
- The flow builder needs to read all the available payloads and its ids
=> Feat/add payload to non message top content type #BOT-573

packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-contentful/tests/cms/cms-error.test.ts, packages/botonic-plugin-contentful/tests/util/profiler.test.ts
- Publish version `0.19.1 alpha.1` of plugin contentful
- Skip 'Measure without name' test (@vanbasten17  and I try to fix it but we are not sure of which is the expected behavior)
=> Chore/publish version 0.19.1 alpha.1 of plugin contentful

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-core/src/hubtype-service.ts, packages/botonic-react/package-lock.json, packages/botonic-react/package.json
* Decompressing large contents coming from backend (previously encoded to base64 and gzipped)
=> feat(core): decompress data for large contents coming from pusher

packages/botonic-plugin-hubtype-babel/README.md, packages/botonic-plugin-hubtype-babel/package-lock.json, packages/botonic-plugin-hubtype-babel/package.json, packages/botonic-plugin-hubtype-babel/src/hubtype-babel-api-service.ts, packages/botonic-plugin-hubtype-babel/src/index.ts, packages/botonic-plugin-hubtype-babel/src/options.ts, packages/botonic-plugin-hubtype-babel/tsconfig.base.json, packages/botonic-plugin-hubtype-babel/tsconfig.esm.json, packages/botonic-plugin-hubtype-babel/tsconfig.json
New Hubtype Babel Plugin created.
Created a new Botonic Plugin to interact with Hubtype Babel.
Add the plugin to the bot defining the `projectId` and the `authToken` (if needed):
```
export const plugins = [
{
id: 'hubtype-babel',
resolve: require('@botonic/plugin-hubtype-babel'),
options: {
projectId: '6800762a-03b5-419e-be97-67feac7bc5b9',
},
},
]
```
=> feature(babel): Plugin Hubtype Babel #DAT-65

packages/botonic-plugin-contentful/src/contentful/manage/manage-environment.ts, packages/botonic-plugin-contentful/tests/contentful/contentful.helper.ts, packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-environment.ts, packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful.helper.ts
- Add `ManageEnvironment` class
- In order to publish a flow with the flow builder, we need to have access to the available environments and apply changes such as:
- Create or delete environments 
- Change the environment alias target
=> Feat/add environment manager #FLO-107

packages/botonic-plugin-hubtype-babel/package-lock.json, packages/botonic-plugin-hubtype-babel/package.json
Update plugin version on package.json after publishing.
=> docs(Babel): bump babel plugin version

.secrets.baseline, packages/botonic-core/src/hubtype-service.ts
**Note**: contentful tests are failing, but this PR is not related to that.
Allow secret explicitly to avoid problems with .secrets.baseline file
=> fix: allow secret explicitly

packages/botonic-plugin-contentful/src/cms/callback.ts, packages/botonic-plugin-contentful/src/cms/cms-dummy.ts, packages/botonic-plugin-contentful/src/cms/cms-error.ts, packages/botonic-plugin-contentful/src/cms/cms-log.ts, packages/botonic-plugin-contentful/src/cms/cms-multilocale.ts, packages/botonic-plugin-contentful/src/cms/cms.ts, packages/botonic-plugin-contentful/src/cms/contents.ts, packages/botonic-plugin-contentful/src/cms/factories/content-factories.ts, packages/botonic-plugin-contentful/src/cms/test-helpers/builders.ts, packages/botonic-plugin-contentful/src/cms/transform/cms-filter.ts, packages/botonic-plugin-contentful/src/cms/transform/message-content-filters.ts, packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts, packages/botonic-plugin-contentful/src/contentful/contents/follow-up.ts, packages/botonic-plugin-contentful/src/contentful/contents/video.ts, packages/botonic-plugin-contentful/src/render/botonic-converter.ts, packages/botonic-plugin-contentful/tests/contentful/contents/text.test.ts, packages/botonic-plugin-contentful/tests/contentful/contents/video.test.ts, packages/botonic-plugin-contentful/tests/render/botonic-converter.test.ts, packages/botonic-plugin-contentful/tests/tools/validate-all-contents.test.ts
Create `video` content
There wasn't a content to define videos.
Fields:
- name
- video (reference to the video asset)
- follow up
=> Botonic Plugin Contentful: video content

packages/botonic-core/src/models/legacy-types.ts, packages/botonic-react/src/webview.jsx
Fixed Telegram's deep linking logic in order to return to the bot conversation when a webview is closed and added temporal logic for Apple Business Chat and Twitter DMs.
=> fix(react): fix deep link for telegram's webviews

packages/botonic-plugin-dynamodb/tests/domain/track.test.ts, packages/botonic-plugin-dynamodb/tests/helpers/jest.ts
Fix eslint issue
it makes eslint checks in botonic-plugin-dynamodb to fail
=> fix: fix jest issue

packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-contentful/src/cms/transform/message-content-filters.ts, packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts, packages/botonic-plugin-contentful/src/contentful/contents/follow-up.ts, packages/botonic-plugin-contentful/src/render/botonic-converter.ts, packages/botonic-plugin-contentful/src/tools/l10n/csv-export.ts
- Add handoff model in order to be able to export it for translators.
- doesn't need tests
=> feat(plugin-contentful): export handoff content model for translators

packages/botonic-core/package.json, packages/botonic-core/src/models/legacy-types.ts, packages/botonic-plugin-hubtype-babel/package.json, packages/botonic-plugin-hubtype-babel/src/index.ts
The inference should return also if the input text has sense or not.
We need a solution for detecting when the input text is totally random (`asdfasdf`).
Add random text detection during inference in backend.
=> Feature: Add NonSense prediction to hubtype babel plugin#DAT-332

packages/botonic-plugin-hubtype-babel/package.json
( Related to #2267 )
Upgrade `plugin-hubtype-babel` package version after being released.
=> Feature: upgrade plugin hubtype babel new version #DAT-345

packages/botonic-plugin-hubtype-babel/package-lock.json, packages/botonic-plugin-hubtype-babel/package.json, packages/botonic-plugin-hubtype-babel/src/hubtype-babel-api-service.ts, packages/botonic-plugin-hubtype-babel/src/index.ts, packages/botonic-plugin-hubtype-babel/src/options.ts
Avoid running inference on automatic bot messages. 
The inference was run for multiple automated bot messages. 
Check if the message is automated before running inference.
=> Feature: avoid inference on automatic bot messages #DAT-353

packages/botonic-react/src/components/timestamps.jsx
Added className to timestamp component. Add different name depending if the timestamp is in the user message or the bot message.
Needed in order to customize the timestamp of the messages easily.
- doesn't need tests
=> Botonic-React: add className to timestamp component

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-core/src/models/legacy-types.ts, packages/botonic-plugin-hubtype-babel/package-lock.json, packages/botonic-plugin-hubtype-babel/package.json, packages/botonic-plugin-hubtype-babel/src/hubtype-babel-api-service.ts, packages/botonic-plugin-hubtype-babel/src/index.ts, packages/botonic-plugin-hubtype-babel/src/options.ts
Added a flag that indicates if `has_sense` prediction should be applied.
The has_sense prediction is not enabled by default. If needed, it should be enabled by using the new flag. @asastre
=> Feature: Flag to enable has_sense detection on plugin-hubtype-babel

packages/botonic-plugin-hubtype-babel/README.md
Add information about the plugin's options to `plugin-hubtype-babel` README.
=> Feature: Add plugin options information #DAT-403

packages/botonic-core/src/models/legacy-types.ts, packages/botonic-react/src/webchat/webchat.jsx
* Adding typing on/off events emitted to backend to distinguish when user is typing or not.
=> feat(react): add typing on/off events

docs/docs/components/components-multichannel.md, docs/docs/test/1.testing-your-components.md, docs/docs/webchat/webchat-button-disable.md
- Fixed word repetition in [docs/docs/webchat/webchat-button-disable.md](https://github.com/hubtype/botonic/blob/master/docs/docs/webchat/webchat-button-disable.md)
- Deleted space (minor detail) 
- Corrected missing curly bracket and eliminated excessive indentation
This PR is intended to take the friction out of reading, understanding and testing documentation.
=> doc: fixing small details and code snippets

packages/botonic-plugin-contentful/src/cms/cms-dummy.ts, packages/botonic-plugin-contentful/src/cms/cms-error.ts, packages/botonic-plugin-contentful/src/cms/cms-log.ts, packages/botonic-plugin-contentful/src/cms/cms-multilocale.ts, packages/botonic-plugin-contentful/src/cms/cms.ts, packages/botonic-plugin-contentful/src/cms/transform/cms-filter.ts, packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts, packages/botonic-plugin-contentful/tests/contentful/contents.test.ts
Include number of references to include in the content method.
When using the content method to get a handoff content, it was failling because the schedule was not being sent.
Include the number of references to include. Set to 6 as we don't have any content with more than 4 references.
=> Contentful - Plugin: include references to content method

packages/botonic-react/src/webview.jsx
Webviews were not redirecting correctly when sent through WhatsApp Cloud API. With this change, the issue is fixed. Linked to [this PR](https://github.com/metis-ai/hubtype-backend/pull/1373).
Use the unformatted phone number instead of the imp_id as WhatsApp Cloud API does not follow the same rules as ordinary WhatsApp
=> fix: Webviews not redirecting correctly on WhatsApp Cloud #PLA-1598

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-core/src/models/events/message/contact.ts, packages/botonic-core/src/models/events/message/message-event.ts, packages/botonic-core/src/output-parser/factory.ts, packages/botonic-core/src/output-parser/parsers.ts, packages/botonic-core/tests/parsing/contact.test.tsx, packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json, packages/botonic-react/package-lock.json, packages/botonic-react/package.json
* Bumping @botonic/core and @botonic/react to 0.21.1 and @botonic/plugin-contentful to 0.21.0.
=> chore: bump core/react to 0.21.1 and plugin-contentful to 0.21.0

CHANGELOG.md
=> chore: update changelog for 0.21.0 release

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-core/src/models/legacy-types.ts, packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/webview.jsx
Instagram opens a browser when opening a webview. This code adds the functionality of closing it after clicking a "close" button.
https://linear.app/hubtype/issue/PLA-1688/support-webviews-in-instagram
I tried redirecting to the conversation URL: https://developers.facebook.com/docs/messenger-platform/instagram/features/ig-me-links but it did not work, because it was opening the chat inside the browser. So, I went for the straight forward solution of window.close()
=> feat: add support to close webviews in instagram #PLA-1688

docs/docs/components/components-location.md, packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/components/location.jsx
* Fixed `lat`, `long` properties of `Location` to be numbers.
=> fix(react): lat, long to be numbers instead of strings

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-core/src/core-bot.ts, packages/botonic-core/src/models/legacy-types.ts, packages/botonic-core/src/plugins.ts
* Fixed types for `Plugin` interface. Now `pre` and `post` are optional and they can return a promise or not.
* Execute methods in `runPlugins` only if they are defined.
* Added new type `ResolvedPlugins` to distinguish between the ones that are loaded in memory and the ones read from plugins file.
=> fix(core): fix plugin types, allow to have plugins without pre/post, added new ResolvedPlugins type

packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/components/audio.jsx, packages/botonic-react/src/components/document.jsx, packages/botonic-react/src/components/image.jsx, packages/botonic-react/src/components/pic.jsx, packages/botonic-react/src/components/video.jsx, packages/botonic-react/src/util/environment.js
* Add resolution for `staticAssets`automatically within framework, so user don't need to define anything extra.
=> feat(react): resolve assets automatically within components

packages/botonic-plugin-flow-builder/README.md
Added documentation for Flow Builder Plugin.
=> Botonic - Flow Builder Plugin: Add README file

packages/botonic-cli/README.md, packages/botonic-cli/package-lock.json, packages/botonic-cli/package.json, packages/botonic-cli/src/commands/deploy.ts, packages/botonic-cli/tsconfig.json
* Add functionality to allow deploy automatically a new bot if not exists when passing -b flag.
This is needed for @elozano98 to deploy a bot automatically with an external script
=> feat(cli): create new bot when passing -b name

docs/docs/welcome.md
The customer list was out of date. 
I have updated the list with an image to make it more visual and cleaner.
=> Botonic doc: Updating clients that use it

packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/flow-builder-models.ts, packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts, packages/botonic-plugin-flow-builder/src/handoff.ts, packages/botonic-plugin-flow-builder/src/index.ts
Be able to use a payload action defined in flow-builder in onFinishPayload of handoff. 
If there is a linked content it will have priority over the one defined as action payload.
With action payload I mean the text defined in "action after agent assistance"
=> feature(pluign-flow-builder): handoff payloads

.github/workflows/pr.yml
* Configure ChatGPT PR Reviewer: https://github.com/anc95/ChatGPT-CodeReview
=> feat: try to add bot-reviewer to botonic

packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/flow-builder-models.ts, packages/botonic-plugin-flow-builder/src/handoff.ts
- use handoff auto assign prop on the flow builder
- Remove  handoff `message` and `fail message`
=> Feat: use handoff auto assign prop on the flow builder #BLT-91

.github/workflows/botonic-cli-tests.yml, .github/workflows/botonic-common-workflow.yml, .github/workflows/botonic-core-tests.yml, .github/workflows/botonic-docs-netlify-deploy.yml, .github/workflows/botonic-nlp-tests.yml, .github/workflows/botonic-nlu-tests.yml, .github/workflows/botonic-plugin-contentful-tests.yml, .github/workflows/botonic-plugin-dashbot-tests.yml, .github/workflows/botonic-plugin-dialogflow-tests.yml, .github/workflows/botonic-plugin-dynamo-tests.yml, .github/workflows/botonic-plugin-google-analytics-tests.yml, .github/workflows/botonic-plugin-inbenta-tests.yml, .github/workflows/botonic-plugin-intent-classification-tests.yml, .github/workflows/botonic-plugin-luis-tests.yml, .github/workflows/botonic-plugin-ner-tests.yml, .github/workflows/botonic-plugin-nlu-tests.yml, .github/workflows/botonic-plugin-segment-tests.yml, .github/workflows/botonic-plugin-watson-tests.yml, .github/workflows/botonic-react-tests.yml
Creating a new reusable workflow to simplify action updates or version updates.
With @vanbasten17 we noticed that the workflows for each botonic package had a similar structure, and to simplify both individual workflows and actions version updates, we decided to create a reusable workflow
Checking each workflow, we could extract some common steps to use on each workflow. Also added input flags that enable or disable different steps.
[TBW]
The pull request has no tests
=> Workflows: Create a reusable workflow for most flows #SER-2260

packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/action.tsx, packages/botonic-plugin-flow-builder/src/functions/conditional-provider.ts, packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts, packages/botonic-plugin-flow-builder/src/handoff.ts, packages/botonic-plugin-flow-builder/src/index.ts, packages/botonic-plugin-flow-builder/src/types.ts
Add the possibility to pass a function from the bot configuration to do the tracking.
- track the name of each first content, not the "followups"
- track the state of the queue as it passes through a conditional queue. At this point it would be interesting for the queue status component to store the name of the project. 
- track HANDOFF_SUCESSFULL when doing a handoff
=> Plugin flow builder: tracking

.github/workflows/botonic-cli-tests.yml, packages/botonic-cli/src/botonic-api-service.ts, packages/botonic-cli/tsconfig.json, packages/botonic-cli/tsconfig.test.json
We have configured our application client as public. 
We cannot use PKCE as initially intended because we are both the authorization server and the resource server. Since the vulnerability identified by the penetration test lies in the client_secret present in our code, and we are not using it by definition, we have decided to remove it as it has no effect.
=> feature: Removed client_secret #PLA-20

packages/botonic-cli/README.md, packages/botonic-cli/package-lock.json, packages/botonic-cli/package.json, packages/botonic-cli/src/analytics/credentials-handler.ts, packages/botonic-cli/src/botonic-api-service.ts
Adapt the code to match the client release
=> feature(botonic-cli): Bump version to 0.21.4 #PLA-20

packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json
- bump botonic flow builder plugin version to 0.22.3
- includes last changes of whatsapp button list, fix url buttons and refactor of the flow builder plugin
=> chore: bump botonic flow builder plugin version to 0.22.3

packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/action.tsx, packages/botonic-plugin-flow-builder/src/action/index.tsx, packages/botonic-plugin-flow-builder/src/action/intent.ts, packages/botonic-plugin-flow-builder/src/action/keyword.ts, packages/botonic-plugin-flow-builder/src/action/tracking.ts, packages/botonic-plugin-flow-builder/src/action/user-input.ts, packages/botonic-plugin-flow-builder/src/api.ts, packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx, packages/botonic-plugin-flow-builder/src/functions/conditional-provider.ts, packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts, packages/botonic-plugin-flow-builder/src/functions/index.ts, packages/botonic-plugin-flow-builder/src/helpers.ts, packages/botonic-plugin-flow-builder/src/index.ts, packages/botonic-plugin-flow-builder/src/types.ts
Add tracking to each FlowBuilder action option. Events are created which are those defined in hubtype-analytics. Although I have put as a dependency @botonic/plugin-hubtype-analytics I am only using the types to create the events. The call to the trackEvent function will enter as a FlowBuilder dependency.
The most important thing in this PR is to generate the concrete event at each point. When I tried to do this I saw that the files were getting too big and I applied a refactor to separate everything better.
So I have transformed the action file into a folder and created a file for the way to get the node: by user input, by intent, by keyword and another one with the logic to call the trackEvent function that will not always be defined in the flow builder plugin
Apply a refactor in the …
=> Flow builder: tracking with Hubtype analytics events

package-lock.json, package.json
upgrade the version of ts-node. Without this version upgrade the Contentful scripts for importing and exporting translations are failing
=> chore(botonic): upgrade ts-node

packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/action/index.tsx, packages/botonic-plugin-flow-builder/src/constants.ts, packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx, packages/botonic-plugin-flow-builder/src/content-fields/flow-element.tsx, packages/botonic-plugin-flow-builder/src/content-fields/flow-text.tsx, packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list-row.tsx, packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list-section.tsx, packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list.tsx
- Allow having multiple buttons pointing to the same target on whatsapp
- Whatsapp buttons and rows on the same message must have unique id
- Add extra info on buttons and rows payload to allow having multiple buttons on the a message pointing the same target
=> Feat(flow-builder): allow having multiple buttons pointing to the same target #BLT-163

packages/botonic-react/package-lock.json, packages/botonic-react/package.json
publish botonic-react 0.22.6 version that adds trigger button notifications and markdown for WhatsApp
=> chore(botonic-react): publish version 0.22.6

packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/action/index.tsx, packages/botonic-plugin-flow-builder/src/api.ts, packages/botonic-plugin-flow-builder/src/constants.ts, packages/botonic-plugin-flow-builder/src/content-fields/flow-text.tsx, packages/botonic-plugin-flow-builder/src/index.ts, packages/botonic-plugin-flow-builder/src/types.ts
The objective is to be able to add a variable in a text from Flow Builder. 
For example if you put {language} in the text this part of the text will be replaced by the current language which will be stored in extra_data.language. If the variable does not exist in the session it will be left {language}.
It also performs the fallback function. If extra_data is not defined, it is set to isFirstFallbackOption = true.
I have made a refactor to have the request in the cmsApi class so it is possible to replace the variables in the FLowText.fromHubtypeCMS function. This way in the action we already have the final text and we don't have to do extra logic in the action.
replaceVariables is a static function of the FlowText class. This function receives the extraData object which is where the …
=> Flow Builder: Add a variable in a text from Flow Builder

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/index.ts, packages/botonic-plugin-google-analytics/package-lock.json, packages/botonic-plugin-google-analytics/package.json, packages/botonic-plugin-google-translation/package-lock.json, packages/botonic-plugin-google-translation/package.json, packages/botonic-plugin-hubtype-babel/package-lock.json, packages/botonic-plugin-hubtype-babel/package.json, packages/botonic-plugin-hubtype-babel/src/index.ts, packages/botonic-plugin-hubtype-babel/src/options.ts, packages/botonic-plugin-inbenta/package-lock.json, packages/botonic-plugin-inbenta/package.json, packages/botonic-plugin-luis/package-lock.json, packages/botonic-plugin-luis/package.json, packages/botonic-plugin-segment/package-lock.json, packages/botonic-plugin-segment/package.json, packages/botonic-plugin-watson/package-lock.json, packages/botonic-plugin-watson/package.json, packages/botonic-react/package-lock.json, packages/botonic-react/package.json
=> Botonic version 0.23.0

packages/botonic-react/src/components/index-types.ts, packages/botonic-react/src/components/webchat-settings.tsx, packages/botonic-react/src/util/environment.js
Write the WebchatSettings component with typescript using existing WebchatSettingsProps 
This component was written in javascript and all props were mandatory (and without type). Now they are all optional and with their corresponding types.
=> botonic-react: WebchatSettings with typescript

packages/botonic-cli/README.md, packages/botonic-cli/package-lock.json, packages/botonic-cli/package.json, packages/botonic-plugin-dialogflow/package-lock.json, packages/botonic-plugin-dialogflow/package.json, packages/botonic-plugin-dialogflow/tests/index.test.ts, packages/botonic-plugin-dynamodb/package-lock.json, packages/botonic-plugin-dynamodb/package.json, packages/botonic-plugin-dynamodb/src/infrastructure/dynamo.ts, packages/botonic-plugin-dynamodb/tests/domain/time.test.ts, packages/botonic-plugin-dynamodb/tests/domain/track.test.ts, packages/botonic-plugin-dynamodb/tests/infrastructure/dynamo.integration.test.ts
publish 0.23.0 version of packages cli, plugin-dialogflow, plugin-dynamodb
=> 0.23.0 packeges versions

packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/action/index.tsx, packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx, packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/components/multichannel/index-types.ts, packages/botonic-react/src/components/multichannel/multichannel-text.jsx, packages/botonic-react/src/components/multichannel/multichannel-utils.js, packages/botonic-react/src/components/whatsapp-button-list.tsx, packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-text.test.jsx.snap, packages/botonic-react/tests/components/multichannel/multichannel-text.test.jsx
Until now, when a text with more than 3 buttons was sent to the multichannel and the bot was executed in whatsapp, several messages were created and each one of them had 3 buttons. From now on we will use a WhatsApp button list.
If a text arrives with more than 3 whatsapp buttons a whatsapp button list will be created. But in a whatsapp button list you can't use buttons pointing to urls or webviews.
A prop is added to the Multichannel, in the same way that a string could already be passed to split messages ("More Options" by default). Now you can pass a prop to define the text of the WhatsappButtonList button ("Menu" by default).
A whatsapp button list will be created for each group of 4 to 10 buttons that have a payload or a path. 
If there is a group of less than 4 buttons left, a …
=> Botonic react: multichannel text use whatsapp button list

packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-knowledge-bases/package-lock.json, packages/botonic-plugin-knowledge-bases/package.json, packages/botonic-react/package-lock.json, packages/botonic-react/package.json
Only increases the version of the packages:
- botonic-react 0.23.1
- botonic-pluign-flow-builder 0.23.1
- botanic-plugin-knowledge-bases 0.23.0
=> Publish botonic react flow builder and knowledge bases

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts, packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts, packages/botonic-plugin-flow-builder/src/types.ts, packages/botonic-plugin-hubtype-analytics/package-lock.json, packages/botonic-plugin-hubtype-analytics/package.json, packages/botonic-plugin-knowledge-bases/package-lock.json, packages/botonic-plugin-knowledge-bases/package.json, packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts, packages/botonic-plugin-knowledge-bases/src/index.ts, packages/botonic-plugin-knowledge-bases/src/types.ts, packages/botonic-react/package-lock.json, packages/botonic-react/package.json
plugin-knowledge-bases:
- Use the end point of the external api
- In the response the attribute ai has been renamed to answer
plugin-flow-builder:
- In the knowledgeBaseResponse attribute ai has been renamed to answer
=> Plugin knowledge base: use external api

packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts, packages/botonic-plugin-hubtype-analytics/package-lock.json, packages/botonic-plugin-hubtype-analytics/package.json, packages/botonic-plugin-hubtype-analytics/src/utils.ts
The bot_ai_knowledge_base event was not added in the utils/createHtEvent function, that's why it always failed. 
createHtEvent function is the function that creates each event with all the necessary parameters using the request and attributes sent by the bot.
=> Fix: event bot_ai_knowledge_base fails

packages/botonic-plugin-contentful/jest.setup.js, packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-contentful/src/cms/transform/message-content-filters.ts, packages/botonic-plugin-contentful/src/cms/visitors/message-visitors.ts, packages/botonic-plugin-contentful/src/contentful/contents/contents.ts, packages/botonic-plugin-contentful/src/contentful/delivery-api.ts, packages/botonic-plugin-contentful/src/contentful/delivery-utils.ts, packages/botonic-plugin-contentful/src/contentful/ignore-fallback-decorator.ts, packages/botonic-plugin-contentful/src/contentful/search/keywords.ts, packages/botonic-plugin-contentful/src/contentful/traverser.ts, packages/botonic-plugin-contentful/src/plugin.ts, packages/botonic-plugin-contentful/src/tools/validate-all-contents.ts, packages/botonic-plugin-contentful/tests/contentful/contents.test.ts, packages/botonic-plugin-contentful/tests/contentful/delivery/mock-client.helper.ts, packages/botonic-plugin-contentful/tests/nlp/keywords.test.ts, packages/botonic-plugin-contentful/tests/util/profiler.test.ts
- Add `contentModelsWithKeywords` to `ContentfulOptions` to indicate which content types has keywords
- Publish version `0.22.0`
We needed to add keywords to the handoff content to just one bot. So we needed to define the contents with keywords depending on the bot.
The pull request has one unit test checking that `contentModelsWithKeywords` option is being applied correctly.
=> Contentful Plugin: add content models with keywords to plugin options 

packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-hubtype-analytics/package-lock.json, packages/botonic-plugin-hubtype-analytics/package.json, packages/botonic-plugin-knowledge-bases/package-lock.json, packages/botonic-plugin-knowledge-bases/package.json, packages/botonic-react/package-lock.json, packages/botonic-react/package.json
New Botonic version published
@botonic/core: 0.23.1
@botonic/react: 0.23.3
@botonic/plugin-flow-builder: 0.23.2
@botonic/plugin-hubtype-analytics: 0.23.1
@botonic/plugin-knowledge-bases: 0.23.1
@botonic/plugin-contentful: 0.23.0
=> Publish new versions

packages/botonic-dx/package.json, packages/botonic-eslint-config/package.json
Update prettier version to 3.0.3.
Created alpha.4.1 to avoid missmatching with the PR #2623 DX versions
=> Botonic DX: Bump prettier version #SER-2804

packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/action/index.tsx
Upgrade the axios version.
Fixes a problem with fallback
When extra_data exists but isFirstFallbackOption is not shown first option two. This happens in many bots as you can initialise extra_data in the snippet itself.
Now if extra_data is undefiend or isFirsFallbackOption is undefined update extra_data with isFirstFallbackOption to true
=> Fallback logic on plugin-flow-builder

packages/botonic-cli/README.md, packages/botonic-cli/package-lock.json, packages/botonic-cli/package.json, packages/botonic-cli/src/commands/deploy.ts, packages/botonic-plugin-dashbot/package-lock.json, packages/botonic-plugin-dashbot/package.json, packages/botonic-plugin-google-analytics/package-lock.json, packages/botonic-plugin-google-analytics/package.json, packages/botonic-plugin-google-translation/package-lock.json, packages/botonic-plugin-google-translation/package.json, packages/botonic-plugin-hubtype-analytics/package-lock.json, packages/botonic-plugin-hubtype-analytics/package.json, packages/botonic-plugin-hubtype-babel/package-lock.json, packages/botonic-plugin-hubtype-babel/package.json, packages/botonic-plugin-inbenta/package-lock.json, packages/botonic-plugin-inbenta/package.json, packages/botonic-plugin-knowledge-bases/package-lock.json, packages/botonic-plugin-knowledge-bases/package.json, packages/botonic-plugin-luis/package-lock.json, packages/botonic-plugin-luis/package.json, packages/botonic-plugin-segment/package-lock.json, packages/botonic-plugin-segment/package.json, packages/botonic-plugin-watson/package-lock.json, packages/botonic-plugin-watson/package.json
This PR upgrades the `axios` version to version ^1.6.0 for all the packages that needed to be uploaded, it also upgrades the `@botonic/core` version that uses `axios` ^1.6.0 in these packages.
=> Upgrade axios and publish new versions

packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
Use public api to avoid CORS error
Publish plugin flow builder 0.23.4 version
=> plugin-flow-builder: fix CORS error

.pre-commit-config.yaml, packages/botonic-plugin-hubtype-analytics/package.json, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-knowledge-base.ts, packages/botonic-plugin-hubtype-analytics/src/types.ts, packages/botonic-plugin-hubtype-analytics/src/utils.ts
Fix a typo in the @botonic/plugin-hubtype-analytics plugin (Knowl**a**dgeBase -> Knowl**e**dgeBase).
Also, add the Github Action and pre-commit execution for this package.
=> Plugin Hubtype Analytics: Fix typo + Add Github Action and pre-commit execution

packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts, packages/botonic-plugin-flow-builder/src/action/tracking.ts
Fix type in enum EventName detected in [PR#2693](https://github.com/hubtype/botonic/pull/2693)
=> Plugin flow builder: fix typo

packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/action/index.tsx, packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx, packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/components/custom-message.jsx, packages/botonic-react/src/components/index-types.ts, packages/botonic-react/src/components/webchat-settings.tsx, packages/botonic-react/src/webchat-app.jsx, packages/botonic-react/src/webchat/hooks/use-typing.ts, packages/botonic-react/src/webchat/message-list/scroll-button.tsx, packages/botonic-react/src/webchat/message-list/unread-messages-banner.tsx, packages/botonic-react/src/webchat/webchat.jsx
Be able to update the webchat user from a bot action using WebchatSettings component.
We have always had a problem with the synchronisation of the session.user of the webchat (front-end) and the session.user of the bot (lambda). 
In each input that is sent from the webchat the session is attached to make a merge of this in the backend (hubtype-backend) and this updates it to the bot's lambda. 
This causes that if you update the session in the bot's lambda action, in the next action you have the session with the frontend values.
For example: 
- When you start a webchat you normally give a value of user.extra_data.language to indicate in which language the bot is going to respond. This value can be obtained and updated with the language in which the web is being viewed.
- Then in an action …
=> Update webchat user using  WebchatSettings component

CHANGELOG.md, packages/botonic-core/package-lock.json, packages/botonic-core/package.json, packages/botonic-plugin-contentful/package-lock.json, packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-dashbot/package-lock.json, packages/botonic-plugin-dashbot/package.json, packages/botonic-plugin-dynamodb/package-lock.json, packages/botonic-plugin-dynamodb/package.json, packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-google-analytics/package-lock.json, packages/botonic-plugin-google-analytics/package.json, packages/botonic-plugin-hubtype-analytics/package-lock.json, packages/botonic-plugin-hubtype-analytics/package.json, packages/botonic-plugin-hubtype-babel/package-lock.json, packages/botonic-plugin-hubtype-babel/package.json, packages/botonic-plugin-inbenta/package-lock.json, packages/botonic-plugin-inbenta/package.json, packages/botonic-plugin-knowledge-bases/package-lock.json, packages/botonic-plugin-knowledge-bases/package.json, packages/botonic-plugin-luis/package-lock.json, packages/botonic-plugin-luis/package.json, packages/botonic-plugin-segment/package-lock.json, packages/botonic-plugin-segment/package.json, packages/botonic-plugin-watson/package-lock.json, packages/botonic-plugin-watson/package.json, packages/botonic-react/package-lock.json, packages/botonic-react/package.json
Publish version of packages:
- botonic-core
- botonic-react
- botonic-plugin-flow-builder
- botonic-plugin-hubtype-babel
- botonic-plugin-hubtype-analytics
- botonic-plugin-knowledge-bases
- botonic-plugin-contentful
- botonic-plugin-google-analytics
- botonic-plugin-dashbot
- botonic-plugin-dialogflow
- botonic-plugin-inbenta
- botonic-plugin-luis
- botonic-plugin-segment
- botonic-plugin-watson
=> Publish versions 0.24.0

CHANGELOG.md, packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
Use getResolvedLocale to create a text message from knowledge base
=> plugin-flow-builder: use resolvedLocale in knowledge-base

CHANGELOG.md, packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-knowledge-bases/package-lock.json, packages/botonic-plugin-knowledge-bases/package.json
Publish 0.24.6 for plugin-flow-builder
Publish  0.24.1 for plugin-knowledge-bases
=> publish plugin-flow-builder and plugin-knowledge-bases

package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/webchat/webchat.jsx, packages/botonic-react/src/webview-app.tsx
In closeWebview functions options can be undefined
=> botonic-react: options can be undefined

package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
Avoid to call smart intents api if flow does not have defined any smart intent.
=> plugin-flow-builder: avoid to call smart intents api

packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts, packages/botonic-plugin-flow-builder/tests/__mocks__/conditional-queue.ts, packages/botonic-plugin-flow-builder/tests/handoff.test.ts, packages/botonic-plugin-flow-builder/tests/helpers/flows/basic.ts
- Refactor create QueuesApi class and then create a mockQueueAvailability for testing
- Add test to check conditional queue and handoff nodes
Add tests for conditional queue and handoff nodes
=> plugin-flow-builder: handoff test

packages/botonic-plugin-flow-builder/tests/conditional-bot-variable.test.ts, packages/botonic-plugin-flow-builder/tests/conditional-channel.test.ts, packages/botonic-plugin-flow-builder/tests/conditional-country.test.ts, packages/botonic-plugin-flow-builder/tests/helpers/flows/basic.ts
Add tests for country conditionals, channel and custom
BUG: In the custom conditional, when a numerical variable is checked and the value is 0, it arrives in the JSON as a string. 
Keywords are used to reach the node to be tested.
Add tests for country conditionals, channel and custom
=> plugin-flow-builder: test conditional nodes

packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/index.ts, packages/botonic-plugin-hubtype-analytics/src/types.ts, packages/botonic-plugin-hubtype-analytics/src/utils.ts, packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
=> plugin-hubtype-analytics: update fallabck event

package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/index.ts, packages/botonic-plugin-hubtype-analytics/package.json, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-feedback.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-flow.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff-option.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-webview.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event.ts, packages/botonic-plugin-hubtype-analytics/src/types.ts, packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts, packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts, packages/botonic-plugin-hubtype-analytics/tests/event-feedback.test.ts, packages/botonic-plugin-hubtype-analytics/tests/event-flow.test.ts, packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts, packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts, packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts, packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts, packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts, packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
* Removing data field from events
=> Analytics v2: Refactor events by removing data field

packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts, packages/botonic-plugin-flow-builder/src/user-input/intent.ts, packages/botonic-plugin-flow-builder/src/user-input/keyword.ts, packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts, packages/botonic-plugin-hubtype-analytics/src/types.ts, packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts, packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts, packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts, packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
add userInput as a required attribute in all nlu events (keyword, smart intent, intent and knowledge base)
=> plugin-hubtype-analytics: add user input in nlu events

package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/action/fallback.ts, packages/botonic-plugin-flow-builder/src/user-input/keyword.ts, packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
Add await when call trackEvent function
=> plugin-flow-builder: add await when call trackEvent function

package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-react/package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/components/message/index.jsx, packages/botonic-react/src/shared/styles.ts, packages/botonic-react/src/webchat/devices/device-adapter.js, packages/botonic-react/src/webchat/message-list/index.tsx, packages/botonic-react/src/webchat/message-list/intro-message.tsx, packages/botonic-react/src/webchat/message-list/scroll-button.tsx, packages/botonic-react/src/webchat/message-list/unread-messages-banner.tsx, packages/botonic-react/src/webchat/message-list/use-notifications.ts, packages/botonic-react/src/webchat/webchat.jsx
Fixed how scroll to bottom function was executed when typing changed its state.
The issue was that when a big message was rendered (not the entire message was visible in the screen), when I tried to scroll up, it was scrolling down automatically, don't letting me to scroll up.
The issue was happening because we were checking the isLastMessageVisible and isTyping at the same time.
The desired behaviour is that when the bot is typing then we want to scroll down so the user can see the last message shown. I think checking the isLastMessageVisible is not necessary.
Added a timeout so the scroll down action is smooth.
Edited (Oriol), check commit by commit:
- [commit](4181e4f7a6089b702a1bc8a9359231e850063312): I created the hook useNotifications to reuse the logic between UnreadMessagesBanner, …
=> Botonic - React: scroll to bottom when typing

package-lock.json, packages/botonic-plugin-flow-builder/package.json
Upgrade version of react and publish 0.27.6 with tracking all follow ups
=> plugin-flow-builder: publish 0.27.6

package-lock.json, packages/botonic-dx/package.json, packages/botonic-eslint-config/index.js, packages/botonic-eslint-config/package.json
update rule no-explicit-any as warn instead of error
=> botonic-dx: update eslint rules

packages/botonic-plugin-hubtype-analytics/README.md
Add information on how to use the plugin and examples of how to create different events in the bot.
=> plugin-hubtype-analytics: update README

CHANGELOG.md, package-lock.json, packages/botonic-cli/package.json, packages/botonic-core/package.json, packages/botonic-dx/package.json, packages/botonic-eslint-config/package.json, packages/botonic-plugin-contentful/package.json, packages/botonic-plugin-dashbot/package.json, packages/botonic-plugin-dialogflow/package.json, packages/botonic-plugin-dynamodb/package.json, packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-google-analytics/package.json, packages/botonic-plugin-google-translation/package.json, packages/botonic-plugin-hubtype-analytics/package.json, packages/botonic-plugin-hubtype-babel/package.json, packages/botonic-plugin-inbenta/package.json, packages/botonic-plugin-knowledge-bases/package.json, packages/botonic-plugin-luis/package.json, packages/botonic-plugin-segment/package.json, packages/botonic-plugin-watson/package.json, packages/botonic-react/package-lock.json, packages/botonic-react/package.json
Release 0.28.0 for all packages
=> Release 0.28.0

package-lock.json, packages/botonic-core/package.json, packages/botonic-core/src/core-bot.ts, packages/botonic-plugin-flow-builder/package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-hubtype-analytics/package.json, packages/botonic-plugin-hubtype-analytics/src/index.ts, packages/botonic-plugin-hubtype-babel/package.json, packages/botonic-plugin-knowledge-bases/package.json, packages/botonic-react/package-lock.json, packages/botonic-react/package.json
no create events when is test integration
pubish all packages with botonic/core 0.28.1
=> Fix events in test integration

packages/botonic-core/src/core-bot.ts, packages/botonic-react/package.json, packages/botonic-react/src/shared/styles.ts, packages/botonic-react/src/webchat/components/conditional-animation.jsx, packages/botonic-react/src/webchat/header.jsx
Remove framer motion to reduce bundle by 72Kb and create a CSS animation instead.
=> botonic-react: remove framer motion

packages/botonic-plugin-dialogflow/tests/index.test.ts
Add message_id and bot_interaction_id to pass tests
=> plugin-dialogflow: fix tests

packages/botonic-react/src/webchat/trigger-button/styles.ts
Change position to fixed in UnreadMessagesCounter. 
When scrolling the page the counter has to scroll down with the trigger button.
=> botonic-react: position fixed in UnreadMessagesCounter

package-lock.json, packages/botonic-plugin-hubtype-analytics/package.json, packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-handoff-option.ts, packages/botonic-plugin-hubtype-analytics/src/index.ts, packages/botonic-plugin-hubtype-analytics/src/types.ts, packages/botonic-plugin-hubtype-analytics/tests/event-handoff.test.ts
HandoffOption event have queue_id and queue_name params optionals
Add test without this params
=> plugin-hubtype-analytics: HandoffOption evennt optional params 

package-lock.json, packages/botonic-react/package.json
* Upgrade deps (ua-parser-js and path-to-regexp) to fix 3 high vulnerabilities.
=> chore: update ua-parser-js

packages/botonic-react/src/contexts.tsx, packages/botonic-react/src/index-types.ts, packages/botonic-react/src/webchat-app.jsx, packages/botonic-react/src/webchat/webchat.jsx, packages/botonic-react/src/webchat/webview.jsx, packages/botonic-react/src/webview-app.tsx
Refactor to type closeWebview as an async function
=> botonic-react: type closeWebview as an async function

packages/botonic-core/src/models/legacy-types.ts
Add new attributes in request.input for push notifications from Hubtype desk
=> botonic-core: add attributes in input type for push notifications

packages/botonic-react/src/util/dom.js, packages/botonic-react/src/webchat/hooks/use-scroll-to-bottom.ts
* use querySelector instead of ref for checking when to scroll to bottom
=> fix: fix scroll to bottom via querySelector instead of ref

package-lock.json, packages/botonic-cli/README.md, packages/botonic-cli/package.json, packages/botonic-cli/src/util/bot-config.ts
Update regex to obtain @botonic/cli version for bot config
The old regex was looking only for versions with -alpha.X or -beta.X
=> Botonic cli regex bot config

package-lock.json, packages/botonic-core/package.json, packages/botonic-react/package.json
publish 0.30.1 for core and react
=> publish 0.30.1 for core and react

package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/webchat/input-panel/styles.ts
add padding to fix height when textarea grows
=> refactor(botonic-react): add padding to fix height

package-lock.json, packages/botonic-plugin-hubtype-analytics/package.json, packages/botonic-plugin-hubtype-analytics/src/types.ts, packages/botonic-plugin-hubtype-analytics/tests/event-webview.test.ts
Add an enum for webviewEndFailType
Fix test
=> plugin-hubtype-analytics: add an enum for webviewEndFailType

package-lock.json, packages/botonic-cli/package.json, packages/botonic-cli/src/analytics/credentials-handler.ts, packages/botonic-plugin-dialogflow/package.json, packages/botonic-plugin-dialogflow/src/index.ts, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/index.ts, packages/botonic-plugin-flow-builder/src/tracking.ts, packages/botonic-react/jest.config.js, packages/botonic-react/package.json, packages/botonic-react/src/components/message/index.jsx, packages/botonic-react/src/components/message/message-feedback.tsx, packages/botonic-react/src/util/webchat.js, packages/botonic-react/src/webchat/input-panel/index.tsx, packages/botonic-react/src/webchat/webchat.jsx
* Upgrade uuid dependency and use uuid v7 in needed packages.
=> tech-feat: botonic packages to use uuid v7

package-lock.json, packages/botonic-cli/README.md, packages/botonic-cli/package.json, packages/botonic-plugin-dialogflow/package.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-react/package.json
* Bump packages to use uuid v7
=> chore: bump packages using uuid v7

package-lock.json, packages/botonic-core/package.json, packages/botonic-core/src/handoff.ts
export interface HubtypeHandoffParams
=> botonic-core: export interface HubtypeHandoffParams

packages/botonic-react/src/components/index-types.ts
=> botonic-react: remove unused scrollbar props

CHANGELOG.md, package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-react/package.json
Update CHANGELOG and publish 0.30.4 for botonic-react and botonic-plugin-flow.builder
=> Publish 0.30.4

package-lock.json, packages/botonic-plugin-flow-builder/package.json
publish plugin-flow-builder 0.30.6 to remove a log
=> chore(plugin-flow-builder): publish 0.30.6

package-lock.json, packages/botonic-dx-bundler-rspack/.gitignore, packages/botonic-dx-bundler-rspack/README.md, packages/botonic-dx-bundler-rspack/baseline/rspack.config.js, packages/botonic-dx-bundler-rspack/baseline/rspack.config.ts, packages/botonic-dx-bundler-rspack/package.json, packages/botonic-dx-bundler-rspack/tsconfig.json
Create a new dx package that has the dependencies to build a project using as bundler rspack
It also contains a file rspack.config.ts. As explained in the README you have to copy this file to the root of the botonic project.
In the README you can also see the scripts to use rspack to build the project locally or to make a builder for production.
=> dx-bundler-rspack: create a dx package to build with rspack #BLT-1197 

package-lock.json, packages/botonic-dx-bundler-rspack/README.md, packages/botonic-dx-bundler-rspack/baseline/rspack.config.ts, packages/botonic-react/package.json, packages/botonic-react/src/components/element.jsx, packages/botonic-react/src/components/multichannel/multichannel-button.jsx, packages/botonic-react/src/components/multichannel/multichannel-carousel.jsx, packages/botonic-react/src/components/multichannel/multichannel-text.jsx, packages/botonic-react/src/components/multichannel/multichannel-utils.js, packages/botonic-react/src/components/multichannel/multichannel.jsx, packages/botonic-react/src/components/multichannel/whatsapp/constants.ts, packages/botonic-react/src/components/whatsapp-button-list.tsx, packages/botonic-react/src/components/whatsapp-cta-url-button.tsx, packages/botonic-react/src/constants.js
@botonic/react
Remove string that refer to @botonic/react components as Text, Button, MultichannelText etc 
@botonic/dx-bundler-rspack
Remove comment
Update README
=>  Remove strings that refer components #BLT-1258

.github/workflows/botonic-common-workflow.yml, .github/workflows/botonic-docs-netlify-deploy.yml, .github/workflows/botonic-docs-tests.yml, docs/package-lock.json, docs/package.json
We have recieved the following email fron github:
`February 1st, 2025, we are closing down v1-v2 of actions/cache (read more about it in this changelog announcement) as well as all previous versions of the @actions/cache package in actions/toolkit. Attempting to use a version of the @actions/cache package or actions/cache after the announced deprecation date will result in a workflow failure. If you are pinned to a specific version or SHA of the cache action, your workflows will also fail after February 1st.`
For this reason we have to update all actions/cache v1 or v2 dependencies in all repos to v4 which we are using in other workflows. 
=> chore: update github action dependency #PLA-2658

package-lock.json, packages/botonic-react/package.json, packages/botonic-react/src/components/whatsapp-media-carousel.tsx, packages/botonic-react/src/components/whatsapp-product-carousel.tsx, packages/botonic-react/src/components/whatsapp-product-list.tsx, packages/botonic-react/src/util/functional.ts, packages/botonic-react/tests/components/whatsapp-media-carousel.test.jsx, packages/botonic-react/tests/components/whatsapp-product-carousel.test.jsx, packages/botonic-react/tests/components/whatsapp-product-list.test.jsx, packages/botonic-react/tests/utils.test.js
Done:
- Converted snake_case props into camelCase in these components:
- Whatsapp Product List
- Whatsapp Product Carousel
- Watsapp Media Carousel
- Removed unused dependency
This pull request...
=> React: use camelCase in component props

package-lock.json, packages/botonic-core/src/models/legacy-types.ts, packages/botonic-react/package.json, packages/botonic-react/src/components/index.ts, packages/botonic-react/src/components/whatsapp-media-carousel.tsx, packages/botonic-react/src/components/whatsapp-product-carousel.tsx, packages/botonic-react/src/components/whatsapp-product-list.tsx, packages/botonic-react/src/util/functional.ts, packages/botonic-react/tests/components/__snapshots__/whatsapp-media-carousel.test.jsx.snap, packages/botonic-react/tests/components/__snapshots__/whatsapp-product-carousel.test.jsx.snap, packages/botonic-react/tests/components/whatsapp-media-carousel.test.jsx, packages/botonic-react/tests/components/whatsapp-product-carousel.test.jsx, packages/botonic-react/tests/components/whatsapp-product-list.test.jsx, packages/botonic-react/tests/utils.test.js
Added [Whatsapp Product Carousel](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-message-templates/product-card-carousel-templates) component to Botonic
Component used to send a Whatsapp Carousel containing products of a Whatsapp Catalog
```
render() {
return (
<WhatsappProductCarousel
templateName='test_whatsapp_product_carousel_v1'
templateLanguage='en_US'
cards={[
{
catalogId: '891387976146180',
productRetailerId: 'kvtkmes4jb',
},
{
catalogId: '891387976146180',
productRetailerId: 'b887ibxbur',
},
]}
bodyParameters={[
{
type: 'text',
text: 'Pepito',
},
{
type: 'text',
text: 'Hubtype Bot',
},
]}
/>
)
}
```
=> React/Core: added Whatsapp Product Carousel component to Botonic

package-lock.json, packages/botonic-core/src/models/legacy-types.ts, packages/botonic-react/package.json, packages/botonic-react/src/components/index.ts, packages/botonic-react/src/components/whatsapp-media-carousel.tsx, packages/botonic-react/src/components/whatsapp-product-carousel.tsx, packages/botonic-react/src/components/whatsapp-product-list.tsx, packages/botonic-react/src/util/functional.ts, packages/botonic-react/tests/components/__snapshots__/whatsapp-media-carousel.test.jsx.snap, packages/botonic-react/tests/components/__snapshots__/whatsapp-product-carousel.test.jsx.snap, packages/botonic-react/tests/components/__snapshots__/whatsapp-product-list.test.jsx.snap, packages/botonic-react/tests/components/whatsapp-media-carousel.test.jsx, packages/botonic-react/tests/components/whatsapp-product-carousel.test.jsx, packages/botonic-react/tests/components/whatsapp-product-list.test.jsx, packages/botonic-react/tests/utils.test.js
Added [Whatsapp Product List](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/sell-products-and-services/share-products/) component to Botonic
Component used to send a list of products of a Whatsapp Catalog.
```
render() {
return (
<WhatsappProductList
body='Product list sent from the bot'
catalogId='891387976146180'
header='Take a look to our products'
sections={[
{
title: 'section one',
productItems: [
{ productRetailerId: '5kpzivmbul' },
{ productRetailerId: 'kvtkmes4jb' },
],
},
{
title: 'section two',
productItems: [{ productRetailerId: 'p6ng7fghmh' }],
},
]}
/>
)
}
```
=> React/Core: added Whatsapp Product List component to Botonic

package-lock.json, packages/botonic-core/src/models/legacy-types.ts, packages/botonic-react/src/components/index.ts, packages/botonic-react/src/components/whatsapp-media-carousel.tsx, packages/botonic-react/src/components/whatsapp-product-carousel.tsx, packages/botonic-react/src/components/whatsapp-product-list.tsx, packages/botonic-react/src/components/whatsapp-product.tsx, packages/botonic-react/src/util/functional.ts, packages/botonic-react/tests/components/__snapshots__/whatsapp-media-carousel.test.jsx.snap, packages/botonic-react/tests/components/__snapshots__/whatsapp-product-carousel.test.jsx.snap, packages/botonic-react/tests/components/__snapshots__/whatsapp-product-list.test.jsx.snap, packages/botonic-react/tests/components/__snapshots__/whatsapp-product.test.jsx.snap, packages/botonic-react/tests/components/whatsapp-media-carousel.test.jsx, packages/botonic-react/tests/components/whatsapp-product-carousel.test.jsx, packages/botonic-react/tests/components/whatsapp-product-list.test.jsx, packages/botonic-react/tests/components/whatsapp-product.test.jsx, packages/botonic-react/tests/utils.test.js
Added [Whatsapp Product](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/sell-products-and-services/share-products/) component to Botonic
Component used to sent one product of the WhatsApp catalog.
```
render() {
return (
<WhatsappProduct
body='Product sent from the bot'
catalogId='891387976146180'
productId='p6ng7fghmh'
/>
)
}
```
=> React/Core: added Whatsapp Product component to Botonic

package-lock.json, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/index.ts
To work in local development the urls needs trailing slash
=> plugin-flow-builder: add final slash in flows url

packages/botonic-plugin-flow-builder/CHANGELOG.md, packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
=> feat(btonic-plugin-flow-builder): Use the queue's availability endpoint from External API #PLA-2771

package-lock.json, packages/botonic-core/package.json, packages/botonic-core/src/models/legacy-types.ts
Add interface for inputs with type: `case_event_agent_message_created`, `case_event_queue_position_changed`, 
`case_event_status_changed`
=> refactor(core): add interfaces for input event

package-lock.json, packages/botonic-core/CHANGELOG.md, packages/botonic-core/package.json, packages/botonic-core/src/core-bot.ts, packages/botonic-core/src/handoff.ts, packages/botonic-core/src/models/legacy-types.ts, packages/botonic-core/tests/core-bot/core-bot.test.ts, packages/botonic-core/tests/handoff.test.ts, packages/botonic-plugin-flow-builder/CHANGELOG.md, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx, packages/botonic-plugin-hubtype-analytics/package.json, packages/botonic-plugin-knowledge-bases/package.json, packages/botonic-react/package.json
Remove code to not create cases from provider accounts flagged as test
=> botonic-react & plugin-flow-builder: allow creating test cases #BLT-1491

package-lock.json, packages/botonic-react/CHANGELOG.md, packages/botonic-react/package.json, packages/botonic-react/src/webchat/webview/index.tsx
WebviewRequestContext wrapp all WebviewContainer to fix close webview from deafult header
=> feat: WebviewRequestContext wrapp all WebviewContainer

packages/botonic-core/src/models/legacy-types.ts, packages/botonic-plugin-flow-builder/src/index.ts, packages/botonic-plugin-flow-builder/src/types.ts
Allow infer type from BotContext to session.user.extra_data
=> core & plugin-flow-builder: allow infer type of user.extra_data #BLT-1592

packages/botonic-core/CHANGELOG.md, packages/botonic-core/src/models/legacy-types.ts
Change `session._hubtype_case_status` for `session._hubtype_case_resolution`
=> feat(botonic-core): change _hubtype_case_status for _hubtype_case_resolution

package-lock.json, packages/botonic-core/CHANGELOG.md, packages/botonic-core/package.json, packages/botonic-core/src/models/legacy-types.ts, packages/botonic-plugin-flow-builder/CHANGELOG.md, packages/botonic-plugin-flow-builder/package.json, packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
Use BotContext in routes function and RequestMatcher.
Add webview and target in FlowButton
=> Use bot context in routes and matcher

.github/workflows/botonic-publish.yml
=> fix: botonic-publish action 

.github/workflows/botonic-publish.yml, package-lock.json, packages/botonic-core/package.json, packages/botonic-plugin-google-translation/package.json, packages/botonic-plugin-segment/package.json
bump versions of core, google-translation, segment after fail test to publish from github action
=> botonic: bump core, google-translation, segment

package-lock.json, packages/botonic-react/CHANGELOG.md, packages/botonic-react/package.json, packages/botonic-react/src/components/carousel.tsx
fix arrows position for carousel, when left or right is 0 we need to align at right or left
=> fix: fix carousel arrows position

package-lock.json, packages/botonic-plugin-ai-agents/package.json, packages/botonic-plugin-ai-agents/src/agent-builder.ts, packages/botonic-plugin-ai-agents/src/context.ts, packages/botonic-plugin-ai-agents/src/index.ts, packages/botonic-plugin-ai-agents/src/openai.ts, packages/botonic-plugin-ai-agents/src/runner.ts, packages/botonic-plugin-ai-agents/src/tools/index.ts, packages/botonic-plugin-ai-agents/src/types.ts
=> Refactor: AI Agent plugin reorganized

package-lock.json, package.json, packages/botonic-plugin-ai-agents/package.json, packages/botonic-plugin-ai-agents/src/index.ts, packages/botonic-plugin-ai-agents/src/openai.ts, packages/botonic-plugin-ai-agents/src/runner.ts, packages/botonic-plugin-ai-agents/src/types.ts
- Fix CustomTool Typing
- Increase memory length
=> Fix: CustomTool Typing + Increase Memory Length

package-lock.json, packages/botonic-core/CHANGELOG.md, packages/botonic-core/package.json, packages/botonic-core/src/handoff.ts
Store case rating for test integration
=> botonic-core: store case rating in test integrations #BLT-1772

package-lock.json, packages/botonic-dx-bundler-rspack/package.json
Only update package.json to reflect that we are using the rspack 1.4
=> dx-bundler-rspack: bump @rspack dependencies to ^1.4.x

packages/botonic-plugin-ai-agents/src/index.ts, packages/botonic-plugin-ai-agents/src/types.ts
=> Feat: Improve plugin-ai-agent Typing for Cotext
