- packages/botonic-core/.eslintrc.js
- packages/botonic-core/.prettierrc
- packages/botonic-core/babel.config.js
- packages/botonic-core/index.d.ts
- packages/botonic-core/package-lock.json
- packages/botonic-core/package.json
- packages/botonic-core/src/handoff.js
- packages/botonic-core/src/index.js
- packages/botonic-react/.eslintrc.js
- packages/botonic-react/.prettierrc
- packages/botonic-react/babel.config.js
- packages/botonic-react/index.d.ts
- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/components/carousel.jsx
* chores: Add types for typescript projects which use botonic core & react. Now core & react can be compiled (added dev dependencies), but only its sources will be exported, and so it should not affect pure JS projects.
* chores: eslint & prettier config for core/react
* fix: carousel was not passing its props to Message component
* feature: New storeCaseRating to store the rating given by the customer to the agent
> Add types to core/react. storeCaseRating

- packages/botonic-cli/src/botonicAPIService.ts
- packages/botonic-cli/src/commands/deploy.ts
- packages/botonic-cli/src/commands/new.ts
So far there was no way to force a rebuild when there were no changes on the bot code.
This is necessary eg. when a dependency changes
> feature(cli): rebuild with -f

- packages/botonic-react/src/components/button.jsx
- packages/botonic-react/src/webchat/webchat.jsx
One of the requirements of HP was that options of persistent menu open urls directly
> Persistent menu button url

- packages/botonic-react/src/components/button.jsx
I was using more code that I needed, the logic of this is for buttons of the persistent menu that once clicked the menu has to be closed
> fix: simplify code only deleting 'else'

- packages/botonic-react/src/components/carousel.jsx
- packages/botonic-react/src/components/message.jsx
In this branch I've adjusted the size of the bot icon because it was too big. I also have deleted the pointerStyles from bot because the logo have it.
Because the reduction of the icon I've had to move a little bit the carousel to the left.
> refactor(react/style): change size of bot icon and adapt carousel

- packages/botonic-react/src/webchat/header.jsx
- packages/botonic-react/src/webchat/webchat.jsx
- packages/botonic-react/src/webchat/webchatDev.jsx
- header.jsx: add a styled component button for closing the webchat when is a default header
- webhcat.jsx: Here we send to child component(header.jsx) the method for closing the webchat.
- webchatDev.jsx: When we want to serve our webchat instead of passing a custom header we want to see the dropdown menu with the options "Show session" & "Keep session on reload"
> add(react): close webchat button for default headers

- packages/botonic-core/src/hubtype-service.js
- packages/botonic-react/src/webchat-app.jsx
- packages/botonic-react/src/webchat/webchat.jsx
The goal of this PR is to enable our webchat to get messages sent from the server while the user has been offline.
In order to achieve this we need to store the ID (in localstorage) of the latest message we got and send it on pusher startup.
> feat: unread messages

- docs/4.tutorials-and-examples/6.custom-webchat.mdx
This PR fixes a typo that is present on the documentation
> docs: fix typos on custom webchat

- packages/botonic-nlu/package.json
- packages/botonic-plugin-nlu/package.json
Just updated tensorflow js to the latest version (2.0 or 1.2.11). I've tested it in my machine without problems.
> chore(nlu/plugin-nlu): upgrade deps to tfjs 2.0

- packages/botonic-plugin-contentful/package-lock.json
- packages/botonic-plugin-contentful/package.json
- packages/botonic-plugin-contentful/src/time/schedule.ts
- packages/botonic-plugin-contentful/tests/time/schedule.test.ts
Contentful TimeRange model did not allow entering 24:00 and our code did not accept 00:00 as the end of a range.
So we modified the code so that when the end of a range is 0, it's transformed into 24:00
Also there was a bug where timeranges just after midnight could not be correctly compared
> fix(contentful): TimeRange to support ending at 24h

- packages/botonic-core/package-lock.json
- packages/botonic-core/src/router.js
Right now we couldn't execute routes dynamic routes in deeper flows, because in our @botonic/core router we weren't taking into account that we could receive an array of routes or a function.
```
export const routes = ({ input, session }) => {
return [
{
path: 'hi',
text: /^hi$/i,
action: Hi,
childRoutes: [
{
path: 'pasta',
payload: /^pasta$/i,
action: Pasta,
childRoutes: routes2(input, session),
},
],
},
]
}
```
```
export const routes2 = ({ input, session }) => {
return [{ path: 'cheese', payload: /^cheese$/i, action: Cheese }]
}
```
Now it will work as expected.
> fix(core): allow nested dynamic routes

- packages/botonic-react/src/msg-to-botonic.jsx
- packages/botonic-react/tests/msgToBotonic.test.jsx
When a Text had empty text and no buttons nor replies,
it generated a bad React object, which caused runtime error:
"Objects are not valid as a React child"
> fix(react): msgsToBotonic bug for empty text

- packages/botonic-cli/templates/blank/src/index.js
- packages/botonic-cli/templates/blank/tests/app.test.js
- packages/botonic-cli/templates/childs/src/index.js
- packages/botonic-cli/templates/childs/tests/app.test.js
- packages/botonic-cli/templates/custom-webchat/src/actions/not-found.js
- packages/botonic-cli/templates/custom-webchat/src/index.js
- packages/botonic-cli/templates/custom-webchat/src/routes.js
- packages/botonic-cli/templates/custom-webchat/tests/app.test.js
- packages/botonic-cli/templates/dynamic-carousel/src/index.js
- packages/botonic-cli/templates/dynamic-carousel/tests/app.test.js
- packages/botonic-cli/templates/handoff/src/index.js
- packages/botonic-cli/templates/handoff/tests/app.test.js
- packages/botonic-cli/templates/intent/src/index.js
- packages/botonic-cli/templates/intent/tests/app.test.js
- packages/botonic-cli/templates/nlu/src/index.js
- packages/botonic-cli/templates/nlu/tests/app.test.js
- packages/botonic-cli/templates/tutorial/src/index.js
- packages/botonic-cli/templates/tutorial/tests/app.test.js
- packages/botonic-react/src/botonicTester.js
**Fixes #432** 
Fixed templates that were using old "app.js" as reported by @ericmarcos.
Changed tests for template `custom-webchat` as the test has no correspondence with the current code.
> fix(templates): fix tests for all templates

- packages/botonic-react/src/webchat-app.jsx
- packages/botonic-react/src/webchat/hooks.js
- packages/botonic-react/src/webchat/webchat.jsx
I have added a new feature to call webchat public api to clear the messages of the chat.
So for example, within the developers browser console, `Botonic.clearMessages()` will delete the all the messages of the chat, or if used with the other listeners we can do something like:
```
export const webchat = {
onInit: app => {
app.clearMessages()
app.open()
}
}
```
to automatically clear messages once the webchat is loaded.
> feat(react): add clearMesages public api for webchat

- packages/botonic-react/src/webchat/webview.jsx
**Fixes #431** 
Currently we had the webviews inside an iframe to allow to develop with OAuth2 flows in botonic serve. Since we have seen that it is not a very common use case at the moment, we return to the original way of rendering the webviews (with div) in order to give more importance of previewing correctly the styles of the webview in serve. 
I have created a component that can receive the prop `asframe` if we need to move back again to the iframe or to make it easier if we want to make it configurable from outside (we need to discuss it).
> fix(react): return to original way of rendering webviews in serve

- packages/botonic-react/src/utils.js
- packages/botonic-react/src/webchat/components/styled-scrollbar.jsx
- packages/botonic-react/src/webchat/components/styled-scrollbar.scss
- packages/botonic-react/src/webchat/hooks.js
- packages/botonic-react/src/webchat/message-list.jsx
- packages/botonic-react/src/webchat/webchat.jsx
As mentioned in #541 PR, I just added:
1. **Adjusting class name / id to prevent conflicts** --> Added a new class 'botonic-scrollable-content'
2. **Adding the smooth scroll CSS to this adjusted class name / ID** --> Add css overwriting default simplebar class wrapped by the new 'botonic-scrollable-content'
Now should not produce conflicts with outer pages.
> fix: fix outer-page-scrolling-bug

- packages/botonic-cli/.eslintrc.js
- packages/botonic-cli/package.json
- packages/botonic-cli/tsconfig.json
- packages/botonic-core/.eslintrc.js
- packages/botonic-core/babel.config.js
- packages/botonic-core/package.json
- packages/botonic-plugin-contentful/.eslintrc.js
- packages/botonic-plugin-contentful/.eslintrc_slow.js
- packages/botonic-plugin-contentful/package.json
- packages/botonic-plugin-contentful/tsconfig.eslint.json
- packages/botonic-plugin-dynamodb/.eslintrc.js
- packages/botonic-plugin-dynamodb/.eslintrc_slow.js
- packages/botonic-plugin-dynamodb/package.json
- packages/botonic-plugin-dynamodb/tsconfig.eslint.json
- packages/botonic-react/.eslintrc.js
- packages/botonic-react/babel.config.js
- packages/botonic-react/package.json
.eslintrc*.js were not being formatted by prettier.
Split in 2 commits because an extra tsconfig file is required to avoid an eslint error when specifying the eslintsrc files to test in the eslint command with wildcards https://github.com/typescript-eslint/typescript-eslint/issues/967#issuecomment-531817014
> Chore(dynamo/contentful)eslint on .eslintrc*.js

- packages/botonic-cli/src/commands/deploy.ts
- packages/botonic-core/src/constants.js
- packages/botonic-react/src/components/multichannel/multichannel-utils.js
- packages/botonic-react/src/webview.jsx
- packages/botonic-react/tests/helpers/test-utils.jsx
Hubtype API has changed the name of the Official Whatsapp Business API provider, from "whatsappnew" to "whatsapp". Updating the parts of botonic that are affected by this change.
> refactor: rename 'whatsappnew' to 'whatsapp'

- .prettierrc
- examples/hubtype_demo/package-lock.json
- examples/hubtype_demo/package.json
- package-lock.json
- package.json
- packages/botonic-cli/src/commands/deploy.ts
- packages/botonic-cli/src/utils.ts
- packages/botonic-cli/templates/blank/package.json
- packages/botonic-cli/templates/childs/package.json
- packages/botonic-cli/templates/custom-webchat/package.json
- packages/botonic-cli/templates/dynamic-carousel/package.json
- packages/botonic-cli/templates/handoff/package.json
- packages/botonic-cli/templates/intent/package.json
- packages/botonic-cli/templates/nlu/package.json
- packages/botonic-cli/templates/tutorial/package.json
- packages/botonic-cli/tsconfig.json
- packages/botonic-plugin-contentful/jest.config.js
- packages/botonic-plugin-contentful/package.json
- packages/botonic-plugin-contentful/src/contentful/delivery/cache.ts
- packages/botonic-plugin-contentful/src/tools/translators/csv-import.ts
- packages/botonic-plugin-contentful/tsconfig.eslint.json
- packages/botonic-plugin-dynamodb/jest.config.js
- packages/botonic-plugin-dynamodb/package.json
- packages/botonic-plugin-dynamodb/src/infrastructure/track.ts
- packages/botonic-plugin-dynamodb/tsconfig.eslint.json
- eslint also .js files
- Upgrade to prettier 2.0
Prettier 2.0 changes the default (ie. recommended) value of arrowParens from "avoid" to "always". For the moment, I've set it to "avoid" to avoid massive changes in botonic-react. See https://www.infoq.com/news/2020/03/prettier-2-typescript-cli/ If we all agree we can force the parens for arrow functions in a different PR
> chore(contentful/dynamo/cli): eslint also .js files

- CHANGELOG.md
Added changelog for v0.11.0 for creating a release tag in github history (will be 0.11.0 tag).
> chore: add changelog for v0.11.0

- packages/botonic-plugin-contentful/package-lock.json
- packages/botonic-plugin-contentful/package.json
- packages/botonic-plugin-contentful/tests/nlp/stemmer.test.ts
- scripts/qa/lint-all-packages.sh
- scripts/qa/lint-package.sh
1) node-nlp did not correctly tokenize "covid-19"
Upgrade it so that it has incorporated this patch https://github.com/axa-group/nlp.js/pull/419
2) pre-commit script was not aborting when "npm run lint" returned non 0
> fix: fix 'covid-19' tokenization in Portuguese & fix pre-commit

- packages/botonic-plugin-contentful/package-lock.json
- packages/botonic-plugin-contentful/package.json
* publish 0.11.2, as it's required by a bot which needs the fix in Catalan Tokenizer (#649)
*now we publish also src to be able to debug typescript from bots
> chore(contentful): bump 0.11.2

- packages/botonic-cli/README.md
- packages/botonic-cli/package-lock.json
- packages/botonic-cli/package.json
- packages/botonic-cli/src/commands/deploy.ts
I managed to reproduce the following error by creating manually a `tmp` file in my bot's project directory.
```shell
? Do you want to create a new Bot? Yes
? Bot name: borar65
✔ Building...
[    ] Creating bundle...Deploy Error { Error: EEXIST: file already exists, mkdir 'tmp'
at Object.mkdirSync (fs.js:757:3)
at Run.createBundle (/usr/local/lib/node_modules/@botonic/cli/lib/commands/deploy.js:222:12)
at Run.deploy (/usr/local/lib/node_modules/@botonic/cli/lib/commands/deploy.js:302:24)
at process._tickCallback (internal/process/next_tick.js:68:7) errno: -17, syscall: 'mkdir', code: 'EEXIST', path: 'tmp' }
[==  ] Creating bundle...^C
```
Taking a deeper look on it, it seems that sometimes we have the residual `tmp` directory if a deploy failed previously at certain point or we abort the …
> fix: make sure there are no residual tmp files

- packages/botonic-core/src/handoff.js
I allowed doing a handoff with in this casuistic: 
`agentId` without `queueId` 
but not for 
`email` without `queueId`
I have removed the validation checking the queue.
> fix: allow also only agent emails on handoff

- packages/botonic-core/index.d.ts
- packages/botonic-core/src/handoff.js
- packages/botonic-core/src/index.js
**UPDATED: Renamed `ranges` to `vacation_ranges` to be more explicit**
* Added new method to read agent vacations ranges.
Usage:
```
import { getAgentVacationRanges } from "@botonic/core";
const res = await getAgentVacationRanges(session, {
agentId: "SOME_AGENT_ID",
});
for (let range of res.ranges){
....
}
```
Then in the bot we will receive the ranges with start_date, end_date in timestamp format (can be managed easily with Date or libraries like moment)
> feat(core): get agent vacations ranges

- package-lock.json
- package.json
- packages/botonic-react/.eslintrc.js
- packages/botonic-react/src/components/message.jsx
- packages/botonic-react/src/webchat/session-view.jsx
- packages/botonic-react/src/webchat/webchat.jsx
- Disabled the rule "hook is called conditionally" where the condition was constant. Despite https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level , when the condition is fixed I don't think there should be an issue.
- Plugin added to root because IDEs may require plugins to be in some folder as eslint
> chore(react): eslint plugin for react hooks

- packages/botonic-core/index.d.ts
- packages/botonic-core/src/router.js
- packages/botonic-core/src/router.test.js
- packages/botonic-react/src/index.d.ts
* avoid error log when input.payload is empty
* add retryAction to botonic-core and botonic-react types
* when input.payload was empty, a console.error prined "ERROR getOnFinishParams"
> Avoid error log empty payload

- .github/pull_request_template.md
Leave sections commented in PR template file. You can now simply add your descriptions.
> fix: add comments to annoying pr templates

- packages/.eslintrc.js
- packages/botonic-core/package-lock.json
- packages/botonic-core/package.json
- packages/botonic-core/src/hubtype-service.js
- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/webchat-app.jsx
- packages/botonic-react/src/webchat/hooks.js
- packages/botonic-react/src/webchat/webchat-reducer.js
- packages/botonic-react/src/webchat/webchat.jsx
* Added methods with @guinii  to set a `lastMessageUpdate` in order to be read after and ensure all the messages are loaded in the enduser side in the right way.
If the agent was the last to write in a chat, the information of some messages was missing if the enduser closed the tab of Botonic.
Store and keep updaing a lastMessageUpdate timestamp to keep tracking messages to be updated correctly.
> fix: updating last messages depending on last message update

- .editorconfig
- package.json
- packages/botonic-plugin-contentful/src/cms/callback.ts
- packages/botonic-plugin-contentful/src/cms/contents.ts
- packages/botonic-plugin-contentful/src/contentful/contents/button.ts
- packages/botonic-plugin-contentful/src/contentful/contents/carousel.ts
- packages/botonic-plugin-contentful/src/contentful/contents/follow-up.ts
- packages/botonic-plugin-contentful/src/contentful/contents/startup.ts
- packages/botonic-plugin-contentful/src/contentful/contents/text.ts
- packages/botonic-plugin-contentful/src/contentful/contents/url.ts
- packages/botonic-plugin-contentful/src/contentful/delivery-api.ts
- packages/botonic-plugin-contentful/src/index.ts
- packages/botonic-plugin-contentful/src/util/index.ts
- packages/botonic-plugin-contentful/src/util/objects.ts
* new content cloners
* type contentful entry fields as undefineable as they should be
* ValueObject (Stringable & Equatable) implemented in Callback & ContentId
* followUp fields is now readonly to ensure immutability
> Contentful/ chore and util improvements 1

- packages/botonic-core/package-lock.json
- packages/botonic-core/package.json
- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/components/multichannel/multichannel.jsx
- packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-wrapper.test.jsx.snap
- Multichannel sometimes was not setting the keys of the contained components
- Bump version to alpha so that we can use multichannel changes
- don't copy Multichannel props to created Text to avoid error "React does not recognize the `firstIndex` prop on a DOM element...."
> fix(react): set child keys in multichannel wrapper

- packages/botonic-react/src/keyboard-resizer.js
- packages/botonic-react/src/utils.js
- packages/botonic-react/src/webchat/components/styled-scrollbar.scss
- packages/botonic-react/src/webchat/message-list.jsx
- packages/botonic-react/src/webchat/webchat.jsx
Added a general solution to try to solve iPhone keyboard issues.
* Added function to detect if device is an iPhone.
* Added handlers to act when input is focused/blurred and do a visual hack to avoid iPhone "intelligent" keyboards to apply visual side effects.
* Refactored into `keyboard-resizer.js` and using `window.visualViewport` as the preferable way to retrieve the window height when keyboard is shown.
* Set overscroll-behavior to contain to have "independent" scrolling bars.  
Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
* Try to limit scroll boundaries and prevent scrolling whole window.
Some …
> fix: handle keyboard issues for Safari Iphones

- packages/botonic-react/src/components/button.jsx
- packages/botonic-react/src/webchat/components/persistent-menu.jsx
- packages/botonic-react/src/webchat/webchat.jsx
Adds a bottom border radius for the persistent menu.
When the persistent menu is open, the bottom radius of the webchat is always zero even if the webchat radius is not.
Pass the webchat border radius to the persistent menu and assigns it to the  bottom radius of the close button.
> feat(react): add borderRadius for persistentMenu

- packages/botonic-react/src/components/message.jsx
- packages/botonic-react/src/utils.js
- packages/botonic-react/src/webchat/components/common.jsx
- packages/botonic-react/src/webchat/header.jsx
- packages/botonic-react/src/webchat/message-list.jsx
- packages/botonic-react/src/webchat/webchat.jsx
* Added method `isURL` to verify if string is URL.
* Added utility method `resolveImage` to automatically know if we need to handle the images with static assets or if it's just a plain URL.
Actually devs were not able to set with a URL the following webchat properties:
* `message.bot.image`
* `header.image`
* `intro.image`
* `triggerButton.image`
Encapsulate the logic in `resolveImage` function.
* See `Context` section.
Code example:
```
export const webchat = {
theme: {
triggerButton: {
image: "https://domain.com/my-logo.png",
},
message: {
bot: {
image: "https://domain.com/my-logo.png",
},
},
header: {
image: …
```
> fix(react): allow also urls for webchat properties

- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/components/markdown.js
- packages/botonic-react/src/components/message.jsx
- packages/botonic-react/src/components/multichannel/multichannel-text.jsx
- packages/botonic-react/src/components/text.jsx
- packages/botonic-react/src/constants.js
- packages/botonic-react/tests/components/__snapshots__/text.test.jsx.snap
- packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-carousel-multibutton.test.jsx.snap
- packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-carousel.test.jsx.snap
- packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-text.test.jsx.snap
- packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-wrapper.test.jsx.snap
- packages/botonic-react/tests/components/render-markdown.test.jsx
- packages/botonic-react/tests/components/text-serialization.test.jsx
* Improve `Text.serialize` method.
* Added a markdown renderer for Webchat. After trying different libraries (react-markdown, markdown-to-jsx, ...), I found this is in the best ones https://www.npmjs.com/package/markdown-it (also used by MD Editors like https://stackedit.io/). Demo here: https://markdown-it.github.io/
* Added a way to customize styles for markdown.
* Configure renderer in order to support linking for links
* Updated snapshots and add unit tests for Markdown rendering and Text serialization.
Many users requested to be able to render markdown in Webchat channel.
**How to style Markdown in webchat?**
You can pass …
> feat(react): markdown support

- packages/botonic-cli/templates/blank/webpack.config.js
- packages/botonic-cli/templates/childs/webpack.config.js
- packages/botonic-cli/templates/custom-webchat/webpack.config.js
- packages/botonic-cli/templates/dynamic-carousel/webpack.config.js
- packages/botonic-cli/templates/handoff/webpack.config.js
- packages/botonic-cli/templates/intent/webpack.config.js
- packages/botonic-cli/templates/nlu/webpack.config.js
- packages/botonic-cli/templates/tutorial/webpack.config.js
- packages/botonic-react/src/components/button.jsx
- packages/botonic-react/src/components/message.jsx
- packages/botonic-react/src/utils.js
- packages/botonic-react/src/webchat/components/styled-scrollbar.scss
- packages/botonic-react/src/webchat/webchat.jsx
I will add in this PR fixes I found before 0.12.0 release
* `markdown` prop should not be stored for all messages (only text messages).
* Set the webchat scrollbar to bottom when webchat is open (behavior: 'auto' for "jumping" directly to position, behavior:'smooth' to do it smoothly. 
Removed the css property as with `scrollTo` can be done programatically (not supported natively by Safari, see https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo) if it is necessary, then a polyfill should be used: https://www.npmjs.com/package/scroll-behavior-polyfill
* Added `cleanOnceBeforeBuildPatterns: ['dist']` to avoid race …
> pre-release-fixes

- scripts/upgrade-deps.sh
Script to upgrade all dependencies of all botonic packages.
Most dev dependencies are common for all packages. It's nice to have a single script to upgrade them all, and do any disk cache flush necessary to avoid conflict after upgrading dependencies which are backwards incompatible.
> chore: script to upgrade dependencies

- packages/botonic-react/src/components/markdown.js
- packages/botonic-react/src/components/message.jsx
- packages/botonic-react/tests/components/render-markdown.test.jsx
* Extract function `withLinksTarget` to be used by markdown and link renderers.
* Configure a linksRenderer (note you can initialize MarkdownIt with the 'zero' preset and enable only the required features) to linkify enduser inputs
* Add unit tests
* Tested locally in "prod" webchat mode.
As discussed in the demo, Markdown should not be applied for enduser inputs except for URLs patterns (we still want the enduser URL inputs to be clickable by default).
Before rendering the message, check if this is from `user` and apply `renderLinks` to transforms raw url text into corresponding anchor tags if necessary.
Doesn't need …
> fix(react): parse only links for enduser inputs

- packages/botonic-react/src/webview.jsx
- packages/botonic-react/src/webview.template.html
Use of MessengerExtensions instead of custom SDK.
A custom SDK was used to handle webviews close events, but it was outdated and it started to fail. By using the up to date sdk that facebook provides we are up to date again.
> fix(react): Webviews close correctly using MessengerExtensions

- packages/botonic-nlu/package-lock.json
- packages/botonic-nlu/package.json
- packages/botonic-nlu/src/file-utils.js
* Fix nlu to not process hidden files.
With latest templates we included `.gitkeep` file to make it easier for the developer to have the directory structure already initialized, the nlu was processing this file if not removed, causing errors on predictions in `botonic serve` mode.
> fix(nlu): nlu to not process hidden files

- packages/botonic-core/package-lock.json
- packages/botonic-core/package.json
- packages/botonic-core/src/hubtype-service.js
- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/webchat-app.jsx
* Modified webchat `render` logic to render it depending on visibility.
Coordinate with backend in order to determine whether webchat should be visible or not.
**API Description**:
Added `visibility` endpoint to determine if webchat should be visible or not.
Webchat visibility is determined by the following webchat settings:
* Checkbox is set to visible
* Requester url is in whitelisted domains
* Queue linked to webchat is open
Webchat will still be visible in the following cases:
* No settings defined (webchat which don't have these values set, previous versions)
* Whitelisted urls list is empty, `[]`
**Checks won't be done …
> feat(core/react): dynamically resolve webchat visibility

- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/components/message.jsx
* Call renderlinks only on text elements, bypass React elements.
When rendering a custom message with user props, it was treated as if it can only be a text. This was breaking a custom rate React component rendered from the user perspective.
> fix: only render links coming from text elements

- packages/botonic-plugin-inbenta/package-lock.json
- packages/botonic-plugin-inbenta/package.json
- packages/botonic-plugin-inbenta/src/index.js
Added a session token to Inbenta search queries to track user actions.
Added a source info (webchat, whatsapp...) to Inbenta search queries to know the origin source of the query.
Inbenta noticed us that we were not using session tracking and told us that it's preferred to do so to track user actions by the final client.
Adding this features, the final client will be able to track all the questions and answers made by the user through the bot.
They wanted to to add the source information in order to know from which integration each query comes from.
We obtain the session token on the first search query done by the user and it's saved in the bot's session (`inbentaSessionToken` parameter) for future uses.
The session token is been added to the queries headers in order to track them …
> feat(plugin-inbenta): add session token and source to Inbenta queries

- packages/botonic-react/src/webchat/components/persistent-menu.jsx
- packages/botonic-react/src/webchat/webchat.jsx
`CustomPersistenMenu` uses `isComponentVisible` to close when it detects a click outside the PersistenMenu
`CustomPersistenMenu` does not close when user clicks outside the PersistenMenu
Move `CustomPersistenMenu` form `webchat.jsx` to `persistent-menu.jsx`
> fix(react): useComponentVisible with CustomPersistentMenu

- packages/botonic-cli/templates/blank/package.json
- packages/botonic-cli/templates/blank/webpack.config.js
- packages/botonic-cli/templates/childs/package.json
- packages/botonic-cli/templates/childs/webpack.config.js
- packages/botonic-cli/templates/custom-webchat/package.json
- packages/botonic-cli/templates/custom-webchat/webpack.config.js
- packages/botonic-cli/templates/dynamic-carousel/package.json
- packages/botonic-cli/templates/dynamic-carousel/webpack.config.js
- packages/botonic-cli/templates/handoff/package.json
- packages/botonic-cli/templates/handoff/webpack.config.js
- packages/botonic-cli/templates/intent/package.json
- packages/botonic-cli/templates/intent/webpack.config.js
- packages/botonic-cli/templates/nlu/package.json
- packages/botonic-cli/templates/nlu/webpack.config.js
- packages/botonic-cli/templates/tutorial/package.json
- packages/botonic-cli/templates/tutorial/webpack.config.js
- packages/botonic-react/package.json
- packages/botonic-react/src/components/message.jsx
- packages/botonic-react/src/components/timestamps.jsx
- packages/botonic-react/src/constants.js
**Note**
In render section (return) the only relevant changes are: https://github.com/hubtype/botonic/pull/841/files#diff-a05365ee2d7479e601dd64cc443ef010R276-R282. The rest of changes within this return are due to wrapping it all inside a fragment `<></>`.
* Removed `moment` dependency. Managed default `webchat.botonic.js` size by 170KB.
* Refactored timestamps.
* Modify and adapt api for defining timestamps.
A needed action in order to keep reducing webchat bundle sizes.
Timestamps are disabled by default.
You can enable them easily by:
* Setting `theme.message.timestamps.enable` to `true`. The format displayed by default for …
> fix(react): refactor and remove moment dep

- packages/botonic-core/src/hubtype-service.js
- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/components/message.jsx
- packages/botonic-react/src/constants.js
- packages/botonic-react/src/webchat-app.jsx
- packages/botonic-react/src/webchat/hooks.js
- packages/botonic-react/src/webchat/messages-reducer.js
- packages/botonic-react/src/webchat/webchat.jsx
- packages/botonic-react/tests/webchat/usewebchat.test.js
* Added functionality to support missed ~messages~ user inputs from enduser.
* Enduser messages are displayed with less opacity until they are correctly delivered to the server.
When enduser ~messages~ inputs were not delivered correctly, we weren't trying to resend them from `Botonic`-> `Hubtype`. The purpose of this PR is to have a very first approach of this system that sets the basis for keep improving these functionalities.
`resendUnsentInputs` will be triggered:
* after hubtype service has been initialized
* after webchat has been opened
* if an online connection has been detected with `useNetwork` hook.
* Make use of a …
> feat(react): handle missed enduser messages when connectivty is regained

- packages/botonic-core/package-lock.json
- packages/botonic-core/package.json
- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
Bumping core (0.14.0-alpha.0) and react (0.14.0-alpha.2) to alpha versions to use latest changes:
[Minor improvements](https://github.com/hubtype/botonic/pull/845)
* Deep merging of theme properties at top-level in order to have properly merged the properties coming from webchat/index.js and the ones defined in index.html.
* Refactor mobile webchat configs and allow mobileStyle
* Add message classNames to every message to be able to select them via css/scss.
[Improved offline support](https://github.com/hubtype/botonic/pull/838)
`resendUnsentInputs` will be triggered:
* after hubtype service has been initialized
* after webchat …
> chore: bump alphas for core and react with latest updates

- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/webchat/hooks.js
- packages/botonic-react/src/webchat/webchat.jsx
* Fix name in default initial state.
* Fix cover component: if cover component is shown, disable user input.
When cover component is shown on first interaction, user input should be disabled. This should be the expected behavior, as the purpose of the component is to retrieve information before the user starts interacting with webchat.
**Before:**
**Now:**
> fix(react): disable text input on Cover Component shown

- scripts/qa/lint-package.sh
lint-package.sh (called by pre-commit) was returnnig failure code when npm run lint failed
> chore: pre-commit ignored lint errors

- packages/botonic-plugin-contentful/package-lock.json
- packages/botonic-plugin-contentful/package.json
- packages/botonic-plugin-contentful/src/contentful/multi-environment.ts
- packages/botonic-plugin-contentful/tests/contentful/multi-environment.test.ts
ContentfulOptions.cmsLocale was lost in MultiEnvironmentFactory because we were cloning
the options fields but not its functions
-  has unit tests
> fix(contentful): MultiEnvironmentFactory to clone functions in options

- packages/botonic-plugin-contentful/jest.setup.js
- packages/botonic-plugin-contentful/src/time/schedule.ts
- packages/botonic-plugin-contentful/src/time/timezones.ts
- packages/botonic-plugin-contentful/tests/contentful/contents/date-range.test.ts
- packages/botonic-plugin-contentful/tests/time/schedule.test.ts
- packages/botonic-plugin-contentful/tests/time/time.helper.ts
- packages/botonic-plugin-contentful/tests/time/timezones.test.ts
Fix bug in Contentful Schedule, where schedule was miscalculating around midnight. It was not taking the timezone offset into account to calculate the weekday.
Bug only afftected for schedules which are open after midnight.
Since JS does not allow setting the TZ of a date, I had to apply the offset to a date and check weekday on it.
-  has unit tests
> fix(contentful): schedule was miscalculating around midnight

- packages/botonic-react/src/components/custom-message.jsx
Add `key` prop to `WrappedComponent` for `customMessages` in order to avoid getting the warning of:
> Warning: Each child in a list should have a unique "key" prop
When calling `msgsToBotonic()` to render multiple messages using a customMessage no key was set in the wrapping element for the customMessage and a warning was appearing in console.
Added the `key` prop with the `msg.key` value to `WrappedComponent`.
> Add key prop to WrappedComponent for customMessages

- packages/botonic-core/src/handoff.js
- packages/botonic-core/src/index.js
Added the export of `getAvailableAgentsByQueue` and remove no needed body from request.
Couldn't use the method `getAvailableAgentsByQueue` because was not exported.
> Botonic Core - Export getAvailableAgentsByQueue

- packages/botonic-plugin-contentful/src/cms/contents.ts
- packages/botonic-plugin-contentful/src/cms/context.ts
- packages/botonic-plugin-contentful/src/cms/visitors/message-visitors.ts
- packages/botonic-plugin-contentful/src/contentful/contents/button.ts
- packages/botonic-plugin-contentful/src/manage-cms/fields.ts
- packages/botonic-plugin-contentful/src/tools/validate-all-contents.ts
- packages/botonic-plugin-contentful/tests/tools/validate-all-contents.test.ts
Flag so that  ContentValidator only validates contents which are reachable.
Check empty text in Text contents
Some contents are not available for some locales. We don't want ContentValidator to complain when they have empty fields.
Added a flag in Context to to automatically fix the buttons when no shortText is available. Setting this flag is now possible to detect these cases.
ContentsValidator is a useful class because contentful dashboard allow leaving contents in an inconsistent state.
See how to use in unit test https://github.com/hubtype/botonic/blob/master/packages/botonic-plugin-contentful/tests/tools/validate-all-contents.test.ts
> feat(contentful): content validator only if reachable

- packages/botonic-react/src/components/button.jsx
Rename theme property `hoverText` to `hoverTextColor` in `button.jsx` so changing button's text color on hover could work
Changing the text color of a button when the mouse was over it (`:hover`) wasn't working.
There are 2 different variable names that match the same theme property, `hoverTextColor` in [`constants.js`](https://github.com/hubtype/botonic/blob/master/packages/botonic-react/src/constants.js#L80) and `hoverText` in [`button.jsx`](https://github.com/hubtype/botonic/blob/master/packages/botonic-react/src/components/button.jsx#L82). 
I decided to use `hoverTextColor` because it's more representative of the usage of the property and also because that's the one that appears in the [documentation](https://docs.botonic.io/templates/template-custom-webchat/#webchat-styles)
The pull …
> fix(react): fix change button text color on hover

- packages/botonic-plugin-contentful/bin/l10n/import-from-translators.sh
- packages/botonic-plugin-contentful/src/contentful/delivery-api.ts
- packages/botonic-plugin-contentful/src/manage-cms/fields.ts
- packages/botonic-plugin-contentful/src/tools/l10n/csv-export.ts
- packages/botonic-plugin-contentful/src/tools/l10n/csv-import.ts
- packages/botonic-plugin-contentful/src/tools/l10n/export-csv-for-translators.ts
- packages/botonic-plugin-contentful/src/tools/l10n/import-csv-from-translators.ts
- packages/botonic-plugin-contentful/tests/tools/l10n/__fixtures__/contentful_es-pl.csv
- packages/botonic-plugin-contentful/tests/tools/l10n/csv-export.test.ts
- packages/botonic-plugin-contentful/tests/tools/l10n/csv-import.test.ts
* In tools for import/export content texts for translators, we had forgotten the URLs. Now added
* Also, now URLs are automatically converted to the target country. eg. when importing to fr_LU URLs such as https:/.../es/...html are transformed to https:/.../lu/...html
- [has unit tests
> feat(contentful): im/export URLS for translators

- packages/botonic-cli/templates/dynamodb/babel.config.js
- packages/botonic-cli/templates/dynamodb/package.json
- packages/botonic-cli/templates/dynamodb/src/actions/hi.jsx
- packages/botonic-cli/templates/dynamodb/src/index.js
- packages/botonic-cli/templates/dynamodb/src/locales/index.js
- packages/botonic-cli/templates/dynamodb/src/nlu/nlu.config.json
- packages/botonic-cli/templates/dynamodb/src/plugins.js
- packages/botonic-cli/templates/dynamodb/src/routes.js
- packages/botonic-cli/templates/dynamodb/src/webchat/index.js
- packages/botonic-cli/templates/dynamodb/src/webviews/index.js
- packages/botonic-cli/templates/dynamodb/tests/__mocks__/fileMock.js
- packages/botonic-cli/templates/dynamodb/tests/__mocks__/styleMock.js
- packages/botonic-cli/templates/dynamodb/tests/app.test.js
- packages/botonic-cli/templates/dynamodb/webpack.config.js
A new bot template has been added to cli which tests using botonic dynamoDB plugin from a JS bot. 
Using typescript packages from JS projects has some gotchas. This template demostrates how to solve them
Maybe in the FAQ or troubleshooting section:
See//https://github.com/babel/babel/issues/8900 (exports is not defined)
This needs to be added to babel-loader in webpack.config.js
`sourceType: 'unambiguous', `
This happens because the plugin is not exported within a "default" key. You must ensure that only the core and react dependencies are not excluded.
```
const babelLoaderConfig = {
test: /\.(js|jsx)$/,
// important to exclude @botonic/dynamo. Otherwise, the plugin does not export the
// class within a "default" key, and you'd get "Uncaught TypeError: Plugin is not a constructor" …
```
> feat(cli): template of js bot using dynamo plugin

- packages/botonic-react/src/webchat/webchat.jsx
Fixed a bug reported that cause some styles not showing up as the upper level Webchat props were not deep merged initially in `webchat.jsx`.
> fix(react): missing theme props in first theme merge

- packages/botonic-react/src/webchat-app.jsx
- packages/botonic-react/src/webchat/webchat.jsx
Make the methods `openCoverComponent`, `closeCoverComponent` and `toggleCoverComponent` available through `Botonic` object in browser so the `coverComponent` can be shown/hide manually.
Once the user has gone through the `coverComponent`, there is no way to show it again without not removing the cookies.
Make the methods `openCoverComponent`, `closeCoverComponent` and `toggleCoverComponent` available both in `webchatRef` and `WebchatApp`.
> feat(react): Enable coverComponent toggle through Botonic

- packages/botonic-react/src/components/custom-message.jsx
This PR fixes a crash that happened when using Custom Message Types together with Reply component.
Imagine you have this custom message:
```javascript
import React from 'react'
import { WebchatContext } from '@botonic/react'
import { customMessage } from './custom-message'
class MyMessage extends React.Component {
static contextType = WebchatContext
render() {
return (
<>
<button
onClick={() =>
this.context.sendText(`Bye!`)
}
>Click me!</button>
<p>{this.props.children}</p>
</>
)
}
}
export default customMessage({
name: 'my-message',
component: MyMessage,
})
```
Now you can use it in your actions like this:
```javascript
import React from 'react'
import { Reply } from '@botonic/react'
import MyMessage from '../webchat/MyMessage'
export const CalendarAction = props => (
<MyMessage>
Hi …
```
> fix(react): custom message types to support Reply

- packages/botonic-react/src/webchat/webchat.jsx
It seems that we bumped automatically the dependency with dependabot for `react-textarea-autosize` and sending inputs in the text area where not working. I have seen that they have changed the api from `inputRef` to `ref`. You can see here how to pass the ref in the new version: https://www.npmjs.com/package/react-textarea-autosize#how-to-focus
> fix(react): text area not working

- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/constants.js
- packages/botonic-react/src/dev-app.jsx
- packages/botonic-react/src/webchat-app.jsx
- packages/botonic-react/src/webchat/webchat.jsx
- packages/botonic-react/tests/webchat/storage.test.jsx
Define where to store the `botonicState` using the variable `storage`
In some cases it may be better to store the `botonicState` in the `sessionStrorage` or not storing it
Change [@rehooks/local-storage](https://www.npmjs.com/package/@rehooks/local-storage)  for [react-storage-hooks](https://www.npmjs.com/package/react-storage-hooks) since it allows to store the application state in the `sessionStorage` or in the `localStorage`
By default the `botonicState` will be stored in the `localStorage`. 
Code to change the `storage`:
```
export const webchat = {
storage: {localStorage|sessionStorage|null} 
}
```
difference between …
> feat(react): config storage

- scripts/bump-version.sh
Automate even more package dependency updates for templates and botonic packages with deps to other botonic packages to speed up the process and minimize potential errors.
For example, for the next release we can do:
For preparing rc versions, we can run the bash script:
`$ ./bump-version.sh 0.15.0-rc.0 rc`
will leave the dependencies for templates, react and plugin-nlu in the following format:
**./botonic-react/package.json**
`"@botonic/core": "0.15.0-rc.0"`
For definitive versions, we can run the bash script:
`$ ./bump-version.sh 0.15.0`
will leave the dependencies …
> chore: improve bump versions script

- packages/botonic-core/src/index.d.ts
- packages/botonic-core/src/index.js
- packages/botonic-react/src/components/whatsapp-template.jsx
Adapt WhatsappTempletes and create a new message type named `whatsapptemplate`.
WhatsappTempletes were send as text
If rendered in the browser it shows a message with the name and the spacename, if rendered in node it sends all properties to the message with whatsapptemplate message type
`WhatsappTemplate` component allows to send whatsapp templates in the bot actions
Properties:
required: name, namespace, language
non-required: header, body, footer
Example:
In `./actions/example-whatsappTemplate.js`
```
import React from 'react'
import { WhatsappTemplate } from '@botonic/react'
export default class extends React.Component {
render() {
return (
<WhatsappTemplate
name={'out_of_office'}
namespace={'d32863cc_3dd6_3e84_74c0_38d758fc60f6'}
language={'en'}
header={''}
body={{
type: 'body', …
```
> refactor(react): whatsappTemplate

- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/components/custom-message.jsx
Avoid customMessage to crash if they have bad children. Some bots may store no-react objects in children
> fix(react): customMessage not to crash if bad children

- doc-botonic/docs/components/components-carousel.md
- packages/botonic-cli/templates/tutorial/src/actions/carousel.js
The original url for the Snatch picture in carousel example returns a 404, I propose a new pic taken from wikimedia
The carousel example looks unfinished because the picture is not there.
replace the old pic url by a working one
N/A
doesn't need tests because it is a really simple change and I have checked it manually
> original url for pic in carousel example returns 404

- packages/botonic-cli/scripts/postinstall.js
Use the correct env var (`BOTONIC_DISABLE_ANALYTICS`) to check if telemetry is enabled or not.
This bug caused "Installed Botonic CLI" events being sent despite of having telemetry disabled.
> fix(cli): fix env var name to disable telemetry

- packages/botonic-react/src/dev-app.jsx
- packages/botonic-react/src/index.d.ts
- packages/botonic-react/src/index.js
- packages/botonic-react/src/webchat-app.jsx
- packages/botonic-react/src/webchat/index.d.ts
- packages/botonic-react/src/webchat/index.js
* Types for botonic-react WebChat & WebChatDev
* New getBotonicApp() to access the instance of WebChat on the browser
Currently to access the webchat app from a bot webchat in typescript, you have to do:
```
// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
//@ts-ignore
Botonic.getMessages()
```
and you don't get the type of Botonic. 
Now this is solved with getBotonicApp()
Copy "COntext" section above in documentation.
Cannot be tested without a browser
> React/ getBotonicApp

- packages/botonic-react/src/webchat-app.jsx
Trigger `onMessage()` when a message is sent by the bot in deployed bots.
The function `onMessage()` was not being triggered in the deployed bots when the messages where sent by the bot.
> fix(react): trigger onMessage in deployed bot messages

- packages/botonic-react/src/constants.js
- packages/botonic-react/src/dev-app.jsx
- packages/botonic-react/src/index.d.ts
- packages/botonic-react/src/webchat-app.jsx
- packages/botonic-react/src/webchat/webchat.jsx
- packages/botonic-react/tests/webchat/storage.test.jsx
Add a new webchat setting `storageKey` that indicates what key name to use in order to store the webchat state in localStorage (or sessionStorage).
It can be any "stringable" object, or a function, in that case the return value of the function will be used. If a falsy object is passed then the default value "botonicState" will be used.
Note: I also took the chance to refactor a little bit the "storage" functionality by removing some unnecessary code.
Some clients need to have different webchat SDKs under the same domain. For example:
* customer.com/help --> Bot about FAQs
* customer.com/product --> Live agent chat for pre-sales
The problem is that localStorage is defined at domain level, so different instances of the webchat SDK would end up sharing the state (history of messages, etc), …
> feat(react): add 'storageKey' webchat setting #BOT-133

- packages/botonic-plugin-contentful/src/cms/cms-dummy.ts
- packages/botonic-plugin-contentful/src/cms/cms-error.ts
- packages/botonic-plugin-contentful/src/cms/cms-log.ts
- packages/botonic-plugin-contentful/src/cms/cms-multilocale.ts
- packages/botonic-plugin-contentful/src/cms/cms.ts
- packages/botonic-plugin-contentful/src/cms/transform/cms-filter.ts
- packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
- packages/botonic-plugin-contentful/src/contentful/contents/contents.ts
CMS.contents & CMS.topContents now use generics so that now they can return the specific subtype of Content desired
> refactor(contentful): CMS.(top)contents to use generics

- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/webchat-app.jsx
Add missing `storageKey` attribute in constructor.
`storageKey` was missing in `WebchatApp` constructor. I think it could be working when calling it from `index.html` but not when calling directly inside `webchat/index.js`.
> fix(react): fix missing storageKey in constructor

- .github/workflows/codeql-analysis.yml
Added github Action to enable Github code scanning
* https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository
* https://github.com/features/security
> enable code-scanning

- packages/botonic-core/src/hubtype-service.js
- packages/botonic-react/src/webchat-app.jsx
- packages/botonic-react/src/webchat/webchat.jsx
Be more consistent when resending inputs. 
* Filter now takes into account that `unsentInput` comes as a message property, not only the ack set to 0.
* Explicitly handle unsent messages by adding the ack 0.
* Once the message is updated remove unnecessary `unsentInput` property from a message.
We were having lots of these messages in the server: `Exception: 'message' not found in imp event data: ...`... This happened when in fact a message was sent properly but due to some race condition the `ack` continued being set to 0 and had no `unsentInput` property.
**E.g:**
```
for (const message of this.unsentInputs()) { // this.unsentInputs() --> Sometimes returns some messages without unsentInput property
await this.postMessage(this.user, message.unsentInput) // --> was being called with …
```
> fix(core/react): make sending unsent inputs more consistent

- packages/botonic-core/src/router.js
- packages/botonic-core/src/router.test.js
The function `getRoute` now checks if the input matches with a childRoute
Some tests of `botonic/core` were failing because the function `getRoute` wasn't checking the childRoutes
Call `getRoute` recursively to check if the input matches with a childRoute
> Fix/check childRoutes in getRoute

- packages/botonic-cli/src/botonicapiservice.ts
Fix calls to `/o/token` to follow current oauth specs
In oauth version 3.1.0 the bug that allowed making a post query with params was [fixed](https://github.com/oauthlib/oauthlib/pull/667). This caused a botonic login fail in this new package version in our backend, as it was using params.
It is retrocompatible as a middleware has been added in our backend to prevent that case.
Now we're using data instead of params
> Fix Issue: Params request fail in Oauth 3.1.0+

- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
Reverts hubtype/botonic#1076
Newest versions break some styles and have breaking changes: #973
> Revert "chore(deps): bump react-textarea-autosize from 7.1.2 to 8.3.0"

- packages/botonic-core/src/core-bot.js
- packages/botonic-core/src/index.d.ts
- packages/botonic-core/src/router.js
- packages/botonic-core/src/router.test.js
* Added new `request` matcher
* Check that `route.path` exists, causing 'cannot read path of undefined', failing with https://github.com/hubtype/botonic/pull/1072
To use this new matcher:
```javascript
{
path: 'hi',
request: request =>
request.input.data === 'hi' && request.session.organization === '',
action: Hi,
},
```
**- has unit tests**
> feat(core): add new request matcher, fix minor issues

- packages/botonic-react/src/webchat/webchat.jsx
Do not call onClose event on the first app render.
The first time the app is rendered and the webchat is closed, the `onClose` event is triggered but in fact we are not closing it. Adding a solution to this in order to only call it when the close button is clicked.
> fix(react): do not call onClose on very first render

- packages/botonic-react/src/util/error-boundary.jsx
Avoid circular dependency between util/errorboundary.jsx and components
> fix(react): avoid circular dependency

- packages/botonic-react/src/webchat/webchat.jsx
- packages/botonic-react/tests/webchat/storage.test.jsx
* Fixing issues when `botonicState` was corrupted for some reason (still not known) and session comes without `user.id`, this was making some bots to not even start the chat.
* Added test for this specific scenario. 
> fix(react): webchat to not crash if no user id

- packages/botonic-plugin-contentful/src/cms/contents.ts
- packages/botonic-plugin-contentful/src/contentful/contents/text.ts
- packages/botonic-plugin-contentful/src/render/botonic-converter.ts
- packages/botonic-plugin-contentful/tests/render/botonic-converter.test.ts
Remove the default assignment of `buttonsStyle` to `ButtonStyle.BUTTON` in `Text` and add a new option in `RenderOptions` to be able to specify the default value if no selection has been made in Contentful.
With these changes made, if no selection of button styling has been made in Contentful, you can change decide if you want to show all the buttons as buttons or as replies with just one parameter.
Now there is no way to show all buttons as replies unless you specify it in every button in Contentful.
Remove the default assignment of `buttonStyle` to `ButtonStyle.BUTTON` in `Text` in favour of defaulting it when converting the `Text` to a `BotonisMsg`.
The pull request has unit test.
> Contentful - Make buttonStyle undefined if not specified + new RenderOption to specify default buttonStyle

- .github/workflows/botonic-cli-tests.yml
- .github/workflows/botonic-core-tests.yml
- .github/workflows/botonic-docs-tests.yml
- .github/workflows/botonic-nlu-tests.yml
- .github/workflows/botonic-plugin-contentful-tests.yml
- .github/workflows/botonic-plugin-dashbot-tests.yml
- .github/workflows/botonic-plugin-dialogflow-tests.yml
- .github/workflows/botonic-plugin-dynamo-tests.yml
- .github/workflows/botonic-plugin-google-analytics-tests.yml
- .github/workflows/botonic-plugin-inbenta-tests.yml
- .github/workflows/botonic-plugin-luis-tests.yml
- .github/workflows/botonic-plugin-nlu-tests.yml
- .github/workflows/botonic-plugin-segment-tests.yml
- .github/workflows/botonic-plugin-watson-tests.yml
- .github/workflows/botonic-react-tests.yml
- codecov.yml
1. **Setup codecov** for botonic:
- Configure initial codecov setup
- Upload coverage report to https://codecov.io/gh/hubtype/botonic
2. Trigger **Github workflows only when necessary**. 
1. Codecov
Configuring codecov will allow us to improve the coverage on every push (or at least keep it as the level of previous push)
The configuration in [codecov.yml](https://docs.codecov.io/docs/codecovyml-reference) includes an initial setup with the following:
- Minimum coverage of 40% threshold
- [Flags](https://docs.codecov.io/docs/flags) for the different projects in packages/ that have unit tests running. (Flags help us isolating reports in a monorepo setup)
You can see the reports in https://codecov.io/gh/hubtype/botonic
2. Trigger Github workflows only when necessary 
Prior to this PR, all …
> Codecov & Botonic workflows

- packages/botonic-react/tests/components/__snapshots__/text.test.jsx.snap
- packages/botonic-react/tests/components/text.test.jsx
Create 2 unit tests for Text component with markdown enabled/disabled
Since there were no tests for Text component with markdown enabled/disabled, we created 2 tests, one for enabled and another for disabled.
Add 2 jest tests to text.test.jsx file, along with their corresponding snapshot.
Tests are passing and coverage has increased
> create 2 tests for Text component (markdown enabled/disabled)

- .github/workflows/botonic-core-tests.yml
- .github/workflows/botonic-plugin-contentful-tests.yml
- .github/workflows/botonic-plugin-dynamo-tests.yml
- .github/workflows/botonic-react-tests.yml
Upload lcov report to codecov instead of clover one.
The clover report generated by Jest has issues with partial branch coverage and looks like it is not actively maintained (https://github.com/facebook/jest/issues/10262#issuecomment-733018346)
Since Jest generates lcov report too, we will use it to avoid problems with clover. 
In this PR, all workflows that upload reports to codecov, have bee updated to use lcov.
All workflows will use `file: ./packages/${{env.PACKAGE}}/coverage/lcov.info`
Verified that reports in codecov do not show previous problems with partial branch coverage. See https://codecov.io/gh/hubtype/botonic/commit/d4742e70e9d814fb698547e009ecca69c9563cdc
> Use lcov report for coverage since clover has issues and seems less maintained

- packages/botonic-core/jest.config.js
- packages/botonic-plugin-contentful/jest.config.js
- packages/botonic-plugin-dynamodb/jest.config.js
- packages/botonic-react/jest.config.js
Configure Jest to look for all files in src dir in order to measure coverage properly.
Same config has been propposed to bots-definition in https://github.com/metis-ai/bots-definition/pull/404
With the previous configuration, Jest would only look for items imported in the tests files, resulting in an unrealistic coverage. e.g. A src file without tests and not referenced by other tests, will not be taken into account for the coverage.
Adding src dir to the roots of the Jest configuration will force Jest to scan ALL src files no matter if they are imported or not.
In all jest config files, we have changed the line `roots: ['tests/'],` to `roots: ['src/', 'tests/'],`
Tested in `packages/botonic-react` folder with `npm test`:
After applying the changes, we observe that coverage has slighltly …
> Configure Jest to scan all files in src dirs when measuring coverage

- packages/botonic-react/src/components/index.d.ts
Make `mobileBreakpoint` and `mobileStyle` props optional in `ThemeProps`.
Using typescript, if `theme` prop is modified through `<WebchatSettings>`, this typescript error shows up:
```
TS2739: Type '{}' is missing the following properties from type 'ThemeProps': mobileBreakpoint, mobileStyle
```
This PR solves this problem.
> style(react): make mobileBreakpoint and mobileStyle props optional in ThemeProps

- packages/botonic-react/src/webchat/devices/device-adapter.js
- packages/botonic-react/src/webchat/webchat.jsx
* Scroll to bottom when focusing an input on non-iphone devices.
> fix(react): scroll to bottom on focus on non-iphone devices

- packages/botonic-plugin-contentful/src/nlp/stemmer.ts
- packages/botonic-plugin-contentful/src/nlp/stemmers/stemmer-hr.ts
- packages/botonic-plugin-contentful/src/nlp/stemmers/stemmer-uk.ts
- packages/botonic-plugin-contentful/src/typings.d.ts
- packages/botonic-plugin-contentful/tests/nlp/stemmers/stemmer-uk.test.ts
The stemmer used for Ukrainian had lookbehind regex that was not supported by Safari, so it has been implemented without including that type of unsupported regex.
Is trying to fix this bug reported by @vanbasten17 in [this issue](https://github.com/axa-group/nlp.js/issues/741).
The stemmer has been reimplemented in Botonic contentful but replacing the lookbehind regex.
> fix(contentful): Reimplementation of the stemmer-uk without lookbehind regex.

- docs/docs/components/components-message.md
- docs/docs/concepts/14.humanhandoff.md
- docs/docs/concepts/17.routes.md
- docs/docs/deployment/standalone-js-bundle.md
- docs/docs/webchat/webchat-compatibility.md
- docs/docs/webchat/webchat-storage.md
- docs/docs/webchat/webchat-style.md
- docs/docs/webchat/webchat.md
- docs/website/_redirects
- docs/website/sidebars.json
Updates in webchat section, request matcher added as well as info on storage key
Linear tasks: 
- BOT-162
- BOT-166
- BOT-174
> docs: updates from Linear tasks

- packages/botonic-plugin-contentful/README.md
Updated Botonic Contentful plugin readme to address recent breaking changes.
1. Following [this change](https://github.com/hubtype/botonic/commit/c820e2b32a6d5548f0d1dafd04392b0c5ce9401f) the instructions to setup the contentful plugin require updating as they do not reflect the need to specify the contentful export.json. The code samples also contain a few errors I have addressed.
2. Following this [breaking API change](https://github.com/hubtype/botonic/blob/e12f47c1f5bf8118b8f34ba3a422ba334ed42b6c/CHANGELOG.md#changed-6) I've also updated the code samples to reflect the renamed values.
Docs updated. Note that I've deliberately used the contentful CLI instead of the script as I wasn't sure about the locale work the script does (and the paths seemed to be incorrect). This is likely …
> Docs: update contentful-plugin setup readme

- .github/workflows/botonic-cli-tests.yml
- codecov.yml
- packages/botonic-cli/jest.config.js
- packages/botonic-cli/package-lock.json
- packages/botonic-cli/package.json
- packages/botonic-cli/src/botonic-examples.test.ts
Configure codecov in botonic-cli package
Currently code coverage is not being measured in botonic-cli, so we don't have a way in codecov of viewing the coverage of the whole Botonic project.
Configure codecov for the botonic-cli package in its correspondent workflow and add a flag for botonic-cli in codecov.yml file. <BR>
Also,  a very simple test has been created in order to allow Jest creating a coverage report.
The codecov info for botonic-cli is available in https://codecov.io/gh/hubtype/botonic/tree/54098619baca2409a3ac6239ada4d6079928e55f/packages/botonic-cli/src
> configure coverage in botonic-cli package  #BOT-229

- packages/botonic-cli/package.json
- packages/botonic-core/package.json
- packages/botonic-react/package.json
* Lib was not published to npm because of missing in "files" property of `package.json` in core/react.
> fix(core/react): include lib as files to be published

- packages/botonic-cli/README.md
- packages/botonic-cli/package.json
- packages/botonic-cli/scripts/postinstall.js
- packages/botonic-cli/src/utils.ts
* Add `flushAt: 1` parameter (The number of messages to enqueue before flushing.) when initializing Analytics to be sure we send the tracking events.
* Bump cli to 0.18.3
> chore(cli): do not enqueue tracking events, bump to 0.18.3

- packages/botonic-core/src/index.d.ts
- packages/botonic-react/src/index.d.ts
Fix return type for `input` method in `NodeApp` and `CoreBot`, these methods will return Promises.
> Fix return types for input method in NodeApp and CoreBot

- packages/botonic-react/src/components/document.jsx
- packages/botonic-react/src/constants.js
* Use a clickable button instead of previewing a document.
* Leave them customizable:
```
// Plain props
documentDownload: {
text: 'Descarregar',
style: {
color: 'black',
},
},
// function
documentDownload: from => {
return {
text: `Descarregar`,
style: { color: from === 'user' ? 'black' : 'blue' },
}
},
```
> chore(react): clickable link to document download

- .github/workflows/botonic-nlu-tests.yml
- .github/workflows/botonic-plugin-nlu-tests.yml
- .gitignore
- codecov.yml
- packages/botonic-plugin-nlu/jest.config.js
- packages/botonic-plugin-nlu/package-lock.json
- packages/botonic-plugin-nlu/package.json
- packages/botonic-plugin-nlu/tests/environment-utils.test.ts
Configure botonic-plugin-nlu package to be taken into account when measuring coverage
Currently, we cannot compare the coverage of the whole botonic project with previous versions since codecov is not configured for all the packages.
This change will allow us to track the coverage of the nlu plugin with codecov.
- Configure codecov flag
- Configure workflow to upload coverage results
- Configure jest in botonic-plugin-nlu 
- Include a test to trigger coverage
Coverage can be seen in codecov: https://codecov.io/gh/hubtype/botonic/tree/4021c7af5c6b2732bbc11128bf6255b0fd881da3/packages/botonic-plugin-nlu/src
> Chore/codecov plugin nlu #PLA-309

- packages/botonic-nlp/src/tasks/ner/process/processor.ts
- packages/botonic-nlp/tests/helpers/tasks/ner/helper.ts
- packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
- packages/botonic-nlp/tests/tasks/ner/process/processor.test.ts
- packages/botonic-nlp/tests/tasks/ner/storage/config-storage.test.ts
**Depends on #1377.** Please, review it first. :warning: 
The `generateInput` method of `Processor` needs to pad the sequence so it matches the defined maxLength.
The sequence generated by the `generateInput` method of `Processor` was not padded. So it can result in a sequence which length exceeds `maxLength`. 
Padding the sequence before it was returned.
> fix(processor): ner processor needs to pad sequence

- packages/botonic-core/src/hubtype-service.js
- packages/botonic-react/src/components/message.jsx
- packages/botonic-react/src/index.d.ts
- packages/botonic-react/src/webchat-app.jsx
- packages/botonic-react/src/webchat/index.d.ts
- packages/botonic-react/src/webchat/messages-reducer.js
- packages/botonic-react/src/webchat/webchat.jsx
* Solve issue regarding enduser not receiving some agent messages when connection was lost.
* Moving onConnectionRegained logic within HubtypeService. Every time the event subcription_succeeded is received, we can asure that the auth call has been done. Hence, onConnectionRegained should be called at that point.
* Pusher headers are not refreshed automatically, only when `HubtypeService.init()` is called. So when the state of pusher is `connecting` we must be sure to update the corresponding headers.
Considerations:
* The first approach of destroying pusher and then initialize it again in `onConnectionRegained` breaks the capability of pusher to detect that the application has been reconnected.
* The process is the following:
Connecting --> update auth headers --> Connected --> Do auth …
> fix(core/react): retrieve agent messages after connection loss and HubtypeService refactor

- codecov.yml
Disable codecov comments is PR's for all projects in this repo
Codecov's comments in PRs are noisy and not really helpful, so we agreed to remove them from the PRs
Include `comment: false` in `codecov.yml` file
Created a mock PR to see comments do not appear anymore: https://github.com/hubtype/botonic/pull/1402
> chore: disable codecov's comments in PRs #PLA-387

- packages/botonic-cli/src/commands/train.ts
- packages/botonic-cli/tests/commands/train.test.ts
Botonic now has two different NLP task:
1.  Text Classification
2. Named Entity Recognition
The `botonic train` command needs a way to let the user decide the desired task for training the model. Or whether train a model for each of the possible tasks.
This PR gives to the user the option of selecting the task(s) of the training process.
The `train` command now has a `task` flag where the user can define the desired task. If no flag is defined, a model for each of the tasks is trained. 
By now, the only task flag values allowed are:
- `ner`
- `text-classification`
Examples:
- `botonic train` : Trains a **Named Entity Recognition** model and also a **Text Classifier** model (all possible Botonic tasks).
- `botonic train --task=ner` : Only a **Named Entity Recognition** model is trained. …
> feat(cli): task flag in botonic train command

- packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
**Depends on #1379.** Please, review it first. :warning: 
Models need to be stored by their locale.
Since we want Botonic NLP to allow having different models for different locales, storing them by their locale is needed.
> feat(ner): model stored by locale

- packages/botonic-plugin-ner/src/postprocess/prediction-processor.ts
- packages/botonic-plugin-ner/tests/postprocess/prediction-processor.test.ts
**Depends on #1393.** Please, review it first. :warning: 
A `PredictionProcessor` has been implemented to process the output tensor generated by the model prediction.
The `PredictionProcessor` takes the sequence and the output tensor of the model to generate an array that contains the recognized entities.
The `PredictionProcessor` maps the sequence with the output tensor to get the recognized entities and the corresponding confidences for all possible entity labels.
> feat(ner-plugin): Postprocess implemented

- .github/workflows/botonic-plugin-dialogflow-tests.yml
- codecov.yml
- packages/botonic-plugin-dialogflow/jest.config.js
- packages/botonic-plugin-dialogflow/package-lock.json
- packages/botonic-plugin-dialogflow/package.json
- packages/botonic-plugin-dialogflow/src/index.ts
- packages/botonic-plugin-dialogflow/src/types.ts
- packages/botonic-plugin-dialogflow/tests/index.test.ts
- packages/botonic-plugin-dialogflow/tsconfig.json
Configure the following in botonic-plugin-dialogflow:
- Convert index.js to typescript
- Add Jest config and create a unit test
- Use codecov to track coverage
In order to track coverage for botonic, we needed to configure jest, create a test and configure codecov.
Also, since this package is quite small, we also migrated it to typescript.
This PR includes migrating botonic-plugin-dialogflow package to TS
- has unit tests? It includes a simple unit test to check coverage
- has integration tests: I tested manually with a bot and real dialogflow configuration
Big thanks to @marcrabat for helping me with this one!
> Chore/dialogflow config ts jest codecov #PLA-375

- packages/botonic-core/src/hubtype-service.js
- packages/botonic-core/src/hubtype-service.test.js
Depends on #1360 
* Throw an exception when webchat has lost user or appId from session.
* Small HubtypeService refactor to simplify the code
* HubtypeService.init() to fail when user or appId are missing 
* Simple test for HubtypeService
So far we we were skipping silently.  and it took to long to diagnose it
Cleanup code, reject the Promise when there are issues
Added unit tests for happy and sad paths of init methos. 
> feat(core): improvements in HubtypeService

- packages/botonic-nlp/package-lock.json
- packages/botonic-nlp/package.json
- packages/botonic-plugin-ner/package-lock.json
- packages/botonic-plugin-ner/package.json
- packages/botonic-plugin-ner/src/process/text-processor.ts
- packages/botonic-plugin-ner/tests/helper/tools-helper.ts
Due to the Codifier refactor previously done, all Codifier instances should be replaced by their corresponding encoder in `plugin-ner`.
> refactor(plugin-ner): Codifier replaced by LabelEncoder

- packages/botonic-nlp/src/tasks/text-classification/storage/config-storage.ts
- packages/botonic-nlp/src/tasks/text-classification/storage/types.ts
- packages/botonic-nlp/tests/helpers/tasks/text-classification/constants-helper.ts
- packages/botonic-nlp/tests/helpers/tasks/text-classification/model/config.json
- packages/botonic-nlp/tests/tasks/text-classification/storage/config-storage.test.ts
Implementation of the class that `loads` and `stores` the configuration of a trained model.
The configuration needs to be:
- **Loaded** to configure the model that will be used.
- **Stored** so the trained model can be used later.  
> feat(nlp): Text Classification - Storage

- packages/botonic-core/package.json
- packages/botonic-react/package.json
1.  Added README.md to core & react distribution
1. eslint import was not finding @botonic/core types from typescript projects
* root core index.d.ts was not distributed
* added "types" entry in package.json for core & react
> chore(core/react): fix types distribution

- packages/botonic-core/src/types/index.d.ts
Remove `RouteRequest` type in favour of using `BotRequest` instead in `Routes` type.
As you can see [here](https://github.com/hubtype/botonic/blob/master/packages/botonic-core/src/core-bot.js#L62), `CoreBot` is passing all 3 attributes declared in `BotRequest` type (`input`, `session` and `lastRoutePath`) in the `routes` function so having `RouteRequest` as the argument's type for the `routes` function was no correct.
> style(core): remove RouteRequest type replace it with BotRequest

- packages/botonic-core/README.md
- packages/botonic-eslint-config/README.md
- packages/botonic-eslint-config/index-ci.js
- packages/botonic-eslint-config/index.js
- packages/botonic-eslint-config/package.json
Eslint shareable configuration package.
Unifying the eslint configuration will simplify the eslint configuration of new botonic projects, specially those outside the "packages" folder (which at least inherit the eslint dependencies from the root folder). 
As specified in the [official documentation](https://eslint.org/docs/developer-guide/shareable-configs)
For a project to use this [eslint](https://eslint.org/) configuration, you'll need to:
* Add `extends: '@botonic/eslint-config/index.js',` to your .eslintrc.js
* If you can afford eslint to be slower (eg from your CI pipeline) to detect more issues, add '@botonic/eslint-config/index-ci.js'
* Add this script to your package.json: ` "lint": "eslint_d --fix --quiet 'src/**/*.js*' 'src/**/*.ts' "`.
* Execute `npm run lint`
Please check the …
> chore(eslint-config): shareable eslint config package

- packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
- packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts
- packages/botonic-nlp/tests/tasks/text-classification/botonic-text-classifier.test.ts
Remove getters and setters of preprocessing engines.
No need for getters and setters for preprocessing engines needed. If an engine modification is required, then it should be implemented directly into the `Preprocess` class.
> refactor(nlp): Remove Getters & Setters #BOT-330

- packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
- packages/botonic-nlp/src/tasks/ner/models/types.ts
- packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts
- packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
- packages/botonic-nlp/tests/tasks/text-classification/botonic-text-classifier.test.ts
The way the model is created has been split into two steps:
- `createModel()` method refactored to return the created model.
- `setModel()` method needs to be called to set the model we want to use for training, evaluation, and predictions.
In this way, a user can decide to directly import a custom model. Also, **in the future**, if Botonic's community develops models for NLP tasks, this would be easily imported this way.  
If a user wants to use a template model from Botonic, the code would look something like:
```typescript
const embeddingsStorage = await DatabaseStorage.with(
constantsHelper.LOCALE,
constantsHelper.EMBEDDINGS_TYPE,
constantsHelper.EMBEDDINGS_DIMENSION
)
const model = await classifier.createModel(
TEXT_CLASSIFIER_TEMPLATE.SIMPLE_NN,
embeddingsStorage
) …
```
> feat(nlp): importModel method #BOT-336

- packages/botonic-nlp/src/tasks/ner/process/prediction-processor.ts
- packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
- packages/botonic-nlp/tests/tasks/ner/process/prediction-processor.test.ts
- packages/botonic-plugin-ner/src/process/prediction-processor.ts
- packages/botonic-plugin-ner/tests/process/prediction-processor.test.ts
Filter the entities recognized as `NEUTRAL` because these ones must not be returned to the user.
The `NEUTRAL` label is used for labeling tokens that are not entities.
> refactor(nlp, plugin-ner): Filter Neutral Entities #BOT-341

- packages/botonic-plugin-text-classification/src/utils/environment-utils.ts
- packages/botonic-plugin-text-classification/src/utils/locale-utils.ts
- packages/botonic-plugin-text-classification/tests/utils/locale-utils.test.ts
**Depends on #1472 .** Please, review it first. ⚠️ 
Implementing the utils of the text-classification plugin.
Functions contained in `utils` will be used during the plugin's code.
The `detectLocale` function needs from the text which we want to predict the locale and a whitelist of locales:
```typescript
const detectedLocale = detectLocale('Guess the locale of this sentence', ['en', 'es', 'it', 'ru'])
```
> feat(plugin-text-classification): Plugin Utils implementation #BOT-343

- packages/botonic-plugin-contentful/exports/contentful-export.json
- packages/botonic-plugin-contentful/src/cms/callback.ts
- packages/botonic-plugin-contentful/src/cms/cms-error.ts
- packages/botonic-plugin-contentful/src/cms/exceptions.ts
- packages/botonic-plugin-contentful/tests/cms/cms-error.test.ts
- packages/botonic-plugin-contentful/tests/cms/exceptions.test.ts
- packages/botonic-plugin-contentful/tests/contentful/contents.test.ts
- packages/botonic-plugin-contentful/tests/contentful/contents/carousel.test.ts
- packages/botonic-plugin-contentful/tests/contentful/contents/text.test.ts
- packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful.test.ts
- packages/botonic-plugin-contentful/tests/tools/validate-all-contents.test.ts
Improvements in CmsException:
* Message now includes resourceId so that CMS.contents & CMS.topContents also report it.
* Removed "Due to: " to separate exception msg from reason
Oftentimes contentful contents get corrupted (broken links to deleted or archived contents).
It's very important that the error reporting that we get when loading/validating broken contents is as detailed and clean as possible
> feat(contentful): improve error reporting

- .github/workflows/botonic-cli-tests.yml
- .github/workflows/botonic-core-tests.yml
- .github/workflows/botonic-nlu-tests.yml
- .github/workflows/botonic-plugin-contentful-tests.yml
- .github/workflows/botonic-plugin-dialogflow-tests.yml
- .github/workflows/botonic-plugin-dynamo-tests.yml
- .github/workflows/botonic-plugin-nlu-tests.yml
- .github/workflows/botonic-react-tests.yml
Due to https://about.codecov.io/security-update/, we need to update codecov's action to https://github.com/codecov/codecov-action/releases/tag/v1.4.1
- no because... it is just a change in our ci pipeline
- doesn't need tests because...  it is just a change in our ci pipeline
> chore: update codecov's action version #PLA-442

- packages/botonic-plugin-contentful/jest.config.js
Transpile escape-string-regexp 5.0 when run from jest
After upgrading from escape-string-regexp 4.0 to 5.0, we got this error when running tests: 
```
2021-04-28T14:35:50.2003261Z   ● Test suite failed to run
2021-04-28T14:35:50.2003929Z 
2021-04-28T14:35:50.2004617Z     Jest encountered an unexpected token
2021-04-28T14:35:50.2005114Z 
2021-04-28T14:35:50.2006246Z     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
2021-04-28T14:35:50.2006967Z 
2021-04-28T14:35:50.2007817Z     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
2021-04-28T14:35:50.2008852Z 
2021-04-28T14:35:50.2009817Z     Here's what you can do:
2021-04-28T14:35:50.2011521Z      • If you are trying to …
```
> chore(contentful): escape-string-regexp 5.0 needs transpilation

- packages/botonic-eslint-config/index.js
- packages/botonic-eslint-config/package.json
Avoid eslint errors in expect asserts within conditionals or lambda callbacks
#1488 caused jest/no-conditional-expect due to upgrade to latest eslint-plugin-jest
Turn jest/no-conditional-expect eslint error to warn
> chore(eslint-config): turn jest/no-conditional-expect to warn

- packages/botonic-plugin-text-classification/src/index.ts
- packages/botonic-plugin-text-classification/src/model/model-selector.ts
Some fixes have been resolved:
- Variable correctly renamed.
- `build` method from ModelSelector returned an incorrect new instance. 
The build method generated an error on the chatbot when trying to get the correct model for predicting the intent of the user's input message.
> fix(plugin-text-classification): Minor Fixes

- packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
- packages/botonic-nlp/src/tasks/text-classification/botonic-text-classifier.ts
- packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
- packages/botonic-nlp/tests/tasks/text-classification/botonic-text-classifier.test.ts
The `compile` method from `BotonicNer` and `BotonicTextClassifier` was unnecessary because its content could be moved inside the constructor.
The simpler these classes are the better for the final user.
> refactor(nlp): remove compile fron BotonicNer and BotonicTextClassifier #BOT-337

- packages/botonic-nlp/src/tasks/ner/models/bilstm-model.ts
- packages/botonic-nlp/src/tasks/text-classification/models/constants.ts
- packages/botonic-nlp/src/tasks/text-classification/models/simple-nn.ts
When creating a bot with plugins for Text Classification and NER tasks we get an error.
This error is caused because models used for both tasks have the same names for some layers.
**Solution**: Renaming the model layers to have different names for each task.
> refactor(nlp): Ner and Text Classification model layers renamed #BOT-381

- packages/botonic-nlp/src/dataset/dataset.ts
- packages/botonic-nlp/src/dataset/input-data-parser.ts
- packages/botonic-nlp/src/dataset/input-data-reader.ts
- packages/botonic-nlp/src/tasks/intent-classification/botonic-intent-classifier.ts
- packages/botonic-nlp/src/tasks/intent-classification/models/simple-nn.ts
- packages/botonic-nlp/src/tasks/intent-classification/process/prediction-processor.ts
- packages/botonic-nlp/src/tasks/intent-classification/process/processor.ts
- packages/botonic-nlp/src/tasks/intent-classification/storage/types.ts
- packages/botonic-nlp/tests/dataset/dataset.test.ts
- packages/botonic-nlp/tests/dataset/input-data-parser.test.ts
- packages/botonic-nlp/tests/dataset/input-data-reader.test.ts
- packages/botonic-nlp/tests/helpers/constants-helper.ts
- packages/botonic-nlp/tests/helpers/data/buy-product.yaml
- packages/botonic-nlp/tests/helpers/data/return-product.yaml
- packages/botonic-nlp/tests/helpers/models/intent-classification/en/config.json
- packages/botonic-nlp/tests/helpers/tools-helper.ts
- packages/botonic-nlp/tests/tasks/intent-classification/botonic-intent-classifier.test.ts
- packages/botonic-nlp/tests/tasks/intent-classification/models/simple-nn.test.ts
- packages/botonic-nlp/tests/tasks/intent-classification/process/prediction-processor.test.ts
- packages/botonic-nlp/tests/tasks/intent-classification/process/processor.test.ts
- packages/botonic-nlp/tests/tasks/intent-classification/storage/config-storage.test.ts
- packages/botonic-nlp/tests/tasks/ner/process/processor.test.ts
- In the input file, we had a field named class which has been replaced for intent.
- `InputData` and `ParsedData` had a `classes` field that has been renamed to `intent`.
- `Sample` class field has been renamed to intent.
- Some parameters named class or classes have been renamed to intent or intents respectively.
(Usages of all fields that have been renamed have also been renamed)
> refactor(nlp): rename input class field to intent BOT-400

- packages/botonic-cli/src/commands/train.ts
Task flag in train command renamed from `text-classification` to `intent-classification`.
> refactor(cli): text-classification task renamed to intent-classification #BOT-399

- packages/botonic-nlp/src/tasks/index.ts
- packages/botonic-nlp/src/tasks/intent-classification/botonic-intent-classifier.ts
- packages/botonic-nlp/src/tasks/ner/botonic-ner.ts
- packages/botonic-nlp/src/tasks/nlp-task-config.ts
- packages/botonic-nlp/tests/tasks/intent-classification/botonic-intent-classifier.test.ts
- packages/botonic-nlp/tests/tasks/ner/botonic-ner.test.ts
`BotonicIntentClassifier` and `BotonicNer` constructors have been updated. Now they need a config interface to be initialized.
We want to simplify the main NLP classes by using a configuration interface.  
> Refactor(nlp): NLP Tasks constructors refactored #BOT-329

- packages/botonic-nlp/package.json
- packages/botonic-plugin-intent-classification/src/model/intent-classifier.ts
- packages/botonic-plugin-intent-classification/src/process/prediction-processor.ts
- packages/botonic-plugin-intent-classification/src/process/text-processor.ts
- packages/botonic-plugin-intent-classification/src/utils/environment-utils.ts
- packages/botonic-plugin-ner/src/process/prediction-processor.ts
- packages/botonic-plugin-ner/src/process/text-processor.ts
- packages/botonic-plugin-ner/src/utils/environment-utils.ts
* Remove imports pointing to modules (this makes the bundle to include Node deps). This is an implementation detail that has to be taken into account when developing nlp plugins.
* Done for plugin-intent-classification
* Done for plugin-ner 
* Safe check for process env (not included anymore in Webpack5 unless it is defined with external plugins)
Plugin intent classification and ner were not working when run in serve mode.
> Fix(plugin-ner, plugin-intent-classification): fix imports to work with serve mode

- .github/workflows/botonic-cli-tests.yml
- .github/workflows/botonic-core-tests.yml
- .github/workflows/botonic-nlu-tests.yml
- .github/workflows/botonic-plugin-contentful-tests.yml
- .github/workflows/botonic-plugin-dialogflow-tests.yml
- .github/workflows/botonic-plugin-dynamo-tests.yml
- .github/workflows/botonic-plugin-intent-classification-tests.yml
- .github/workflows/botonic-plugin-nlu-tests.yml
- .github/workflows/botonic-react-tests.yml
Configure codecov action to use latest @v1 version available as https://github.com/codecov/codecov-action#usage recommends
After experimenting some security issues and following suggestion by @dpinol, we will use codecov's latest @v1 version. 
- no because the modified file is only used in ci
> chore: set codecov github action version to v1 #PLA-499

- packages/botonic-plugin-contentful/src/nlp/keywords.ts
- packages/botonic-plugin-contentful/src/nlp/normalizer.ts
- packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful.test.ts
- packages/botonic-plugin-contentful/tests/nlp/keywords.test.ts
- packages/botonic-plugin-contentful/tests/nlp/normalizer.test.ts
Now Normalizer will remove the dots only when an acronym is detected.
Tokenizer splits acronyms in several words and it makes difficult to match "ok" with "o.k"
An AcronymPreprocessor is now executed as first step of our Normalizer so that we do this conversion. It will also be applied to stopwords, keywords,...
```
//acronyms
['o.k.', 'ok'],
['o.k', 'ok'],
['o.k ', 'ok '],
['o.k ', 'ok '],
['U.S.A', 'USA'],
['o.k, vale', 'ok, vale'],
//not acronyms
['.a.', '.a.'],
['U..A', 'U..A'],
['a. opcion', 'a. opcion'],
['no separators', 'no separators'],
['final dot.', 'final dot.'],
```
Now Normalizer will remove the dots only when an acronym is detected. Works like "o.k.", "o.k" and "ok" will be normalized to the same stem.
> Contentful/Make acronyms agnostic to dots #CUS-271

- packages/botonic-nlp/package.json
NLP package main points to lib/index.js so we can use it like:
```typescript
import { Preprocessor, Dataset, BotonicNer } from '@botonic/nlp'
```
> feat(nlp): main points to lib/index.js

- packages/botonic-dx/.gitignore
- packages/botonic-dx/README.md
- packages/botonic-dx/baseline/babel.config.js
- packages/botonic-dx/baseline/prettier.config.js
- packages/botonic-dx/baseline/tsconfig.json
- packages/botonic-dx/baseline/tsconfig.tests.json
- packages/botonic-dx/package.json
- packages/botonic-dx/sample-config/.prettierrc.js
- packages/botonic-dx/sample-config/package.json
- packages/botonic-dx/sample-config/tsconfig.json
- packages/botonic-eslint-config/.gitignore
- packages/botonic-eslint-config/index.js
- packages/botonic-eslint-config/package.json
#1465 created a @botonic/dx & @botonic/eslint-config PoC. After testing it in new projects, many issues were detected.
This PR solves these issues. There were many, but the main ones were:
* run prettier con config .js, .json, .md and css files
* avoid "node/no-unpublished-import" eslint errors when importing dev dependencies from tests
* allow requires on .js files 
More issues fixes at #1602
> botonic Developer Experience (DX) 2/3

- packages/botonic-core/package.json
- packages/botonic-core/src/types/index.d.ts
- packages/botonic-react/src/components/index.d.ts
- packages/botonic-react/src/index.d.ts
Fix types:
- @botonic/core:
- Add `data` as a possible matcher attribute in `Route` interface.
- @botonic/react:
- Add autodisable props in `ButtonProps` interface.
- Fix `setTyping` argument type and `getThemeProperty` returned value type.
- Fix type for `action` and `retryAction` in Route to allow both class and functional components in routes.
Also, remove duplicated entry (`types`) in `package.json` file.
Improve typings
- @botonic/core:
- Since [all Input attributes](https://github.com/hubtype/botonic/blob/master/packages/botonic-core/src/router.js#L237) can be set as matchers, `data` was the one missing.
- @botonic/react:
- Since the theme props can be of different types, I've changed the type of the returned value of `getThemeProperty` to `any`.
> Core & React: Fix types

- packages/botonic-plugin-google-translate/README.md
- packages/botonic-plugin-google-translate/jest.config.js
- packages/botonic-plugin-google-translate/package-lock.json
- packages/botonic-plugin-google-translate/package.json
- packages/botonic-plugin-google-translate/src/access-token.ts
- packages/botonic-plugin-google-translate/src/google-translate-api-service.ts
- packages/botonic-plugin-google-translate/src/index.ts
- packages/botonic-plugin-google-translate/src/language-detector.ts
- packages/botonic-plugin-google-translate/src/options.ts
- packages/botonic-plugin-google-translate/tsconfig.eslint.json
- packages/botonic-plugin-google-translate/tsconfig.json
Creation of `botonic-plugin-google-translate` that detects the language of the user input text.
If you have a Google Translate API in Google Cloud, now you can use it to detect the language of the user input text.
To use this plugin, you need to provide some of your credentials to have access to the Google Translate API:
- `Private Key Id`
- `Private Key`
- `Client Email`
- `Project Id`
You can define a `whitelist` into plugin options to only accept specific languages as detection. In case none of the defined languages is the detected one, 'en' would be set as default.
> Creation of botonic-plugin-google-translate #BOT-430

- docs/website/package.json
- package.json
- packages/botonic-dx/package.json
- packages/botonic-plugin-nlu/package-lock.json
- packages/botonic-plugin-nlu/package.json
* typescript 4.3 introduces a new [check](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3-rc/#always-truthy-promise-checks) to detect missing awaits
> Upgrade typescript from 4.2.x to 4.3.x

- packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
- packages/botonic-plugin-contentful/src/contentful/delivery/cache.ts
- packages/botonic-plugin-contentful/src/contentful/delivery/client-api.ts
- packages/botonic-plugin-contentful/src/util/exceptions.ts
- packages/botonic-plugin-contentful/tests/contentful/delivery/cache.test.ts
- packages/botonic-plugin-contentful/tests/contentful/delivery/mock-client.helper.ts
if contentful calls cache fails, don't cache the error. It's better to return the previous successful result than the new error
This refers to the old (with time expiration) cache that we have to avoid hitting contentful too oftern. It does **not** refer to the [new cache](#1639) that remembers forever the last successful result to be provided whenever contentful call fails. 
Actually this is already a feature of the memoization library that we use (memoizee), but it required setting the option `promise: true`
> feat(contentful): if memoization fails, don't cache the error

- packages/botonic-plugin-contentful/README.md
- packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
- packages/botonic-plugin-contentful/src/contentful/delivery/fallback-cache.ts
- packages/botonic-plugin-contentful/src/plugin.ts
- packages/botonic-plugin-contentful/src/tools/l10n/import-updater.ts
- packages/botonic-plugin-contentful/src/util/backoff.ts
- packages/botonic-plugin-contentful/src/util/memoizer.ts
- packages/botonic-plugin-contentful/tests/contentful/delivery/fallback-cache.test.ts
- packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-asset.test.ts
- packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-entry.test.ts
- packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful.test.ts
- packages/botonic-plugin-contentful/tests/util/memoizer.test.ts
Depends on #1640. :warning:  **Please review it first**
Use memoization to remember forever the last successful invocation for each combination of arguments, and use its result whenever Contentful fails.
Contentful failing during 1h on 2021/6/8 and 2021/6/9.
* Create a generic Memoizer class with several strategies. 
* Create a decorator (FallbackCachedClientApi) around the Contentful API class which uses the Memoizer fallbackStrategy.
* Compose the new decorator within the existing decorator (CachedClientApi) which avoids recent calls.
FallbackCachedClientApi does not use the memoization library used by CachedClientApi (memoizee) because this library does not allow directly accessing the cache. 
The contentful plugin by default uses memoization to remember forever the last successful …
> feat(contentful): memoizer #BOT-467

- packages/botonic-plugin-contentful/bin/import-contentful-models.sh
Fix the `import-contentful-models.sh` script to load the import file correctly (the `file_to_import` argument was not used in the script)
The `import-contentful-models.sh` was loading the file to import properly.
> fix(contentful): use of 1st argument (file_to_import)

- packages/botonic-core/src/handoff.js
- packages/botonic-core/src/types/handoff.d.ts
Added timeout argument to 2 of the API calls to backend. If approach is approved, it should be added to the rest of API calls
* In case a call to backend hangs for many seconds, timeout ensures that the bot is able to react (eg. providing an error message or retrying) before the AWS lambda timeout aborts the bot invocation.
Added in a context argument (like in contentful plugin) so that more options can be added in the future
TODO
- doesn't need tests because it's a call to backend
> feat(core): add optional timeout to getOpenQueues & storeCaseRating

- packages/botonic-react/src/components/multichannel/index.d.ts
- packages/botonic-react/src/components/multichannel/multichannel-button.jsx
- packages/botonic-react/src/components/multichannel/multichannel-carousel.jsx
- packages/botonic-react/src/components/multichannel/multichannel-text.jsx
- packages/botonic-react/src/components/multichannel/multichannel-utils.js
- packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-button.test.jsx.snap
- packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-carousel-multibutton.test.jsx.snap
- packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-carousel.test.jsx.snap
- packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-text.test.jsx.snap
- packages/botonic-react/tests/components/multichannel/multichannel-button.test.jsx
- packages/botonic-react/tests/components/multichannel/multichannel-carousel-multibutton.test.jsx
- packages/botonic-react/tests/components/multichannel/multichannel-carousel.test.jsx
- packages/botonic-react/tests/components/multichannel/multichannel-text.test.jsx
Added new attributes (`buttonsAsText` and `buttonsTextSeparator`) in `text` prop for `Multichannel` component in order to decide to display `<Button>` components as text or as buttons in whatsapp.
Also, allow to display buttons pointing to webviews alongside other buttons (now webview buttons needed to be alone within a `<Text>` component)
Allow `@botonic/react` `Multichannel` component to be able to display real buttons in whatsapp.
Since only 3 buttons (postback buttons) per message are allowed in whatsapp, if we detect more than 3 buttons within a message we're splitting the message in multiple messages in order to ensure all buttons will be displayed.
Since buttons pointing to URLs are not allowed in whatsapp, they will be displayed as text (the same way it's done right now).
Here are …
> feat(react): Display <Button> components as normal buttons in whatsapp

- packages/botonic-core/src/models/events/connections/index.ts
- packages/botonic-core/src/models/events/index.ts
- packages/botonic-core/src/models/events/message/buttons.ts
- packages/botonic-core/src/models/events/message/carousel.ts
- packages/botonic-core/src/models/events/message/custom.ts
- packages/botonic-core/src/models/events/message/element.ts
- packages/botonic-core/src/models/events/message/index.ts
- packages/botonic-core/src/models/events/message/location.ts
- packages/botonic-core/src/models/events/message/media.ts
- packages/botonic-core/src/models/events/message/replies.ts
- packages/botonic-core/src/models/events/message/text.ts
- packages/botonic-core/src/models/user.ts
* Adding data models proposal into `@botonic/core` (note that some definitions may be susceptible to be changed) without conflicting with current `@botonic/core` functionality.
* Defining data models for botonic full stack.
* We defined the most simple data models for botonic full-stack. Each model it's being composed by extending from more basics interfaces (MessageEvent, ConnectionEvent, ...) and defining attributes more specifically in the very bottom interfaces (TextMessageEvent, ConnectionEvent, ...)  For these models it's important to:
1. Be able to have all the event details in separated fields to have the data as plain as possible in the database (will be useful for analytics concerns).
2. Be able to have dynamic resolution of typings.
To achieve both objectives, the purposed …
> Full stack/chore(core): add data models for botonic 1.0

- packages/botonic-plugin-intent-classification/src/index.ts
- packages/botonic-plugin-intent-classification/src/model/model-selector.ts
- packages/botonic-plugin-intent-classification/src/options.ts
- packages/botonic-plugin-ner/src/index.ts
- packages/botonic-plugin-ner/src/model/model-selector.ts
- packages/botonic-plugin-ner/src/options.ts
* Support for nlp plugins in botonic full-stack project.
MODELS_BASE_URL will be defined when the lambda of the bot is deployed under an env variable `process.env.MODELS_BASE_URL` and defined by webpack when it's run in development mode under `MODELS_BASE_URL`.
> chore(ner/intent): support for botonic full-stack

- packages/botonic-api/package-lock.json
- packages/botonic-api/package.json
- packages/botonic-api/src/data-provider/dynamodb-data-provider.ts
- packages/botonic-api/src/data-provider/index.ts
- packages/botonic-api/src/data-provider/local-data-provider.ts
Use of [node-json-db](https://www.npmjs.com/package/node-json-db) package to store data locally (users, events and connections) when no data provider is set.
Also I've done these improvements:
- Fixed some missing types and functions (`getUsers` and `getEvents)` in `DataProvider` interface and its implementations.
- Refactored `dataProviderFactory` to always return a `DataProvider`.
- Bump version of @botonic/api to `1.0.0-alpha.1`
We were facing an issue while storing data locally in memory because rest and websocket were storing their data independently and we need to have it together. 
> Full stack/api local json db

- packages/botonic-api/src/data-provider/dynamodb-data-provider.ts
- packages/botonic-api/src/data-provider/index.ts
- packages/botonic-api/src/data-provider/local-data-provider.ts
- packages/botonic-api/src/rest/routes/bot-input.ts
- packages/botonic-api/src/rest/routes/index.ts
Persist user/events data in `bot-input` endpoint using the `DataProvider`.
Also, I've changed the `bot` argument `rest/routes` is receivinig to be directly the `NodeApp` (see [related PR](https://github.com/hubtype/botonic/pull/1731)) instead of an object containing other unused attributes.
User and events data was not stored when received from the `bot-input` endpoint.
Instead of adding a `getUserByProviderId` method I preferred to add a generic method (`getUserByField`) to search users by any field.
@ericmarcos @vanbasten17 @marcpdw if you're ok with this implementation maybe it will be nice to deprecate the `getUserByWebsocketId` method and use `getUserByField` instead.
Also, to make the code cleaner, I've add all `bot-input` endpoint's code into a sepparate file, the same way we …
> Full stack: Persist user/events data in bot-input endpoint

- packages/botonic-core/src/models/user.ts
- packages/botonic-core/src/router.test.js
Add missing `providerId` attribute in User interface as an optional attribute.
Also, modified the existing `websocketId` attribute to optional.
Fix lint error (`no-conditional-expect`) in test.
Improvement of types in the full-stack version.
> Full stack: Add providerId in User interface

- packages/botonic-react/src/components/multichannel/multichannel-text.jsx
- packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-text.test.jsx.snap
- packages/botonic-react/tests/components/multichannel/multichannel-text.test.jsx
Fix condition to display an extra message with webview buttons in whatsapp when there are more than 3 buttons within a message (whatsapp max. allowed buttons per message)
In whatsapp, an extra message with the `buttonsTextSeparator` text was displayed if a whatsapp message containing more than 3 buttons didn't contain any webview button.
> fix(react): Fix condition to show extra message with webview buttons in whatsapp

- packages/botonic-core/package-lock.json
- packages/botonic-core/package.json
- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
* Bumping to 0.19.0 beta versions of core/react containing the new multichannel features, raw component, mixed with new botonic 1.0 code.
> Chore/bump to 0.19 beta

- packages/botonic-react/src/components/multichannel/multichannel-text.jsx
- packages/create-botonic-app/template/api/src/rest/app.ts
- packages/create-botonic-app/template/bot/src/actions/Welcome.js
- packages/create-botonic-app/template/bot/src/index.js
- packages/create-botonic-app/template/bot/src/nlp/data/en/business.order.status.yaml
- packages/create-botonic-app/template/bot/src/nlp/data/en/business.product.search.yaml
- packages/create-botonic-app/template/bot/src/nlp/data/en/smalltalk.farewell.bye.yaml
- packages/create-botonic-app/template/bot/src/nlp/data/en/smalltalk.farewell.courtesy.yaml
- packages/create-botonic-app/template/bot/src/nlp/data/en/smalltalk.greeting.courtesy.yaml
- packages/create-botonic-app/template/bot/src/nlp/data/en/smalltalk.greeting.hi.yaml
- packages/create-botonic-app/template/bot/src/nlp/data/en/smalltalk.thanks.yaml
- packages/create-botonic-app/template/bot/src/routes.js
:warning: Depends on #1730 
Small improvement by exporting only the `NodeApp` in `bot/src/index.js`. No need to export de config passed to the `NodeApp` since it's already inside it.
Small improvement to make clearer what the bot is exporting.
> refactor(create-botonic-app): Export only the NodeApp in bot/src/index.js

- packages/botonic-plugin-contentful/package-lock.json
- packages/botonic-plugin-contentful/package.json
- packages/botonic-plugin-contentful/src/cms/cms-dummy.ts
- packages/botonic-plugin-contentful/src/cms/cms-error.ts
- packages/botonic-plugin-contentful/src/cms/cms-log.ts
- packages/botonic-plugin-contentful/src/cms/cms-multilocale.ts
- packages/botonic-plugin-contentful/src/cms/cms.ts
- packages/botonic-plugin-contentful/src/cms/transform/cms-filter.ts
- packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
- packages/botonic-plugin-contentful/src/contentful/search/keywords.ts
- packages/botonic-plugin-contentful/src/search/search-by-keywords.ts
- packages/botonic-plugin-contentful/src/search/search.ts
- packages/botonic-plugin-contentful/src/util/measurer/node-performance-measurer.ts
- packages/botonic-plugin-contentful/tests/search/search-by-keywords.test.ts
- Adding `paging` parameter in `searchByKeywords` the same way it's done with `topContents`.
- Fixed an error with the `perf_hooks` dependency that was making the bot's webpack to fail when compiling.
Contentful requests have a limit of 100 contents and some times there's a need to obtain more than 100 contents when searching by keywords.
If no paging object is passed to `searchByKeywords` the default one (with a limit of 1000) wil be set.
> feat(contentful): add paging in searchByKeywords

- packages/botonic-plugin-contentful/jest.config.js
- packages/botonic-plugin-contentful/package-lock.json
- packages/botonic-plugin-contentful/package.json
Downgrade `escape-string-regexp` package to version `4.0.0` to avoid various execution and compiling problems (see [this issue](https://github.com/sindresorhus/escape-string-regexp/issues/34)).
The version `5.0.0` of this package [breaks compatibility](https://github.com/sindresorhus/escape-string-regexp/releases/tag/v5.0.0) with the previous version because now is a pure ESM. 
With version `5.0.0` of `escape-string-regexp`, to be able to execute Contentful plugin's code in jest or through webpack there's a need to transpile it and it can't be executed through ts-node because it throws an error.
> chore(contentful): downgrade escape-string-regexp to version 4.0.0

- packages/botonic-api/package-lock.json
- packages/botonic-api/package.json
- packages/botonic-api/src/data-provider/dynamodb-data-provider.ts
- packages/botonic-api/src/data-provider/index.ts
- packages/botonic-api/src/data-provider/local-data-provider.ts
- packages/botonic-api/src/rest/routes/events.ts
- packages/botonic-api/src/rest/routes/users.ts
- packages/botonic-api/src/rest/routes/validation/common.ts
- packages/botonic-api/src/rest/routes/validation/events.ts
- packages/botonic-api/src/rest/routes/validation/users.ts
- Implementation of users routes for CRUD operations. No authentication is done so far.
- Added validations to the parameters received in the requests using `express-validator`.
- Added missing method `deleteUser` in the `DataProvider` interface and its implementations.
- Add validation in patch and put routes to ensure the ID received in the param is the same as the one received in the body.
- Refactor validations to unify common validations for events and users endpoints.
The api endpoint of users were not implemented yet.
The same way it has been done with events endpoint, all the data validation has been done based on the user type declaration.
For the `patch` request, in order to take advantage of all the validantions done, a method has been implemented to transform all fields to …
> feat(api): implement /users endpoint

- packages/botonic-cli/package-lock.json
- packages/botonic-cli/package.json
- packages/botonic-cli/src/analytics/telemetry.ts
- packages/botonic-cli/src/commands/deploy.ts
- packages/botonic-cli/src/commands/destroy.ts
- packages/botonic-cli/src/constants.ts
- packages/botonic-pulumi/package-lock.json
- packages/botonic-pulumi/package.json
- packages/botonic-pulumi/src/pulumi-runner.ts
* Added extra arguments to deploy command to determine to which cloud provider the bot is deployed.
* Added @botonic/pulumi as CLI's dependency
* Added deploy/destroy commands in PulumiRunner class for simplicity and move build commands to pulumi package.
* Upgraded pulumi/pulumi and pulumi/aws dependencies to use latest versions.
We needed a way to choose where to deploy our bot now that we have the option of deploying it to AWS in Botonic 1.0.
Calling `botonic deploy` or `botonic deploy hubtype` will fallback to current functionality.
In new Botonic 1.0 project the following file should be added in the root directory:
**aws.config.js**
```
exports.default = {
region: 'eu-west-1',
profile: 'my-profile-name',
projectName: 'myProject',
tags: {
Scope: 'Botonic-1.0',
Maintainer: …
```
> feat(cli/pulumi): add deploy command to aws/hubtype to Botonic CLI

- packages/botonic-api/src/rest/routes/events.ts
- packages/botonic-api/src/rest/routes/users.ts
- packages/botonic-api/src/rest/routes/validation/common.ts
- packages/botonic-api/src/rest/utils/paginator.ts
Add proper pagination to GET method in `/users` and `/events` endpoints:
- Refactor pagination params: use `page/pageSize` instead of `limit/offset`.
- Return a paginated response using an object like this one:
```
{
"previous": "<link to previous page>",
"next": "<link to next page>",
"count": <total number of records>,
"results": [{...record1}, {...record2}, ...]
}
```
`/users` and `/events` endpoints had pagination but were not returning a proper paginated response.
Create a `Paginator` class that handles all the pagination logic.
> feat(api): add proper pagination to endpoints

- packages/botonic-pulumi/jest.config.js
- packages/botonic-pulumi/package-lock.json
- packages/botonic-pulumi/package.json
- packages/botonic-pulumi/src/aws/cache-invalidator.ts
- packages/botonic-pulumi/src/aws/deployment-stacks.ts
- packages/botonic-pulumi/src/aws/rest-server.ts
- packages/botonic-pulumi/src/aws/static-webchat-contents.ts
- packages/botonic-pulumi/src/pulumi-runner.ts
- packages/botonic-pulumi/tests/detect-updated-objects.test.ts
- packages/botonic-pulumi/tsconfig.json
* Do invalidate cache for updated S3 objects after deploying Botonic 1.0 full-stack.
As a cache system, cloudfront caches the requested origin objects for some time. This had as a consequence that after modifying static assets (`index.html, webchat.botonic.js, ...`) the changes were not instantly applied so several time had to pass to see the effects ([outdated content](https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-serving-outdated-content-s3/)).
In order to tell cloudfront to request again these files when the web content is loaded, we have to do what is called [cache invalidation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html).
There are some different ways to solve this problem:
* Creating dynamic providers with Pulumi.
* …
> feat(pulumi): cache invalidations for updated static assets

- packages/botonic-pulumi/src/aws/deployment-stacks.ts
- packages/botonic-pulumi/src/aws/index.ts
- packages/botonic-pulumi/src/aws/websocket-server.ts
- packages/botonic-pulumi/src/index.ts
- packages/botonic-pulumi/src/pulumi-runner.ts
* Limited the amount of valid characters for combinations of `projectName` + `stackName`.
Some of AWS components (buckets, lambdas, ...) has a limitation in their names length of ~64 characters. As we append a generated prefix (combination of project name + stack name) to name the components and make them easy to identify, sometimes this maximum was hit.
Define a reasonable total maximum string length of 30 (30 + 1 from separator) and throw asap to not continue propagating this error when deploying in Botonic 1.0.
> fix(pulumi): throw error when exceeding name chars threshold

- .pre-commit-config.yaml
- .secrets.baseline
- Configure [detect-secrets](https://github.com/Yelp/detect-secrets) in a pre-commit hook so that it checks for secrets in Git
it is useful to check that we don't commit secrets to github accidentally
Configured in the pre-commit to avoid committing NEW secrets both locally and in ci.
We also include a baseline (.secrets.baseline) that contains all secrets that currently exist in the repo and which should be checked. 
- no because... **[provide a reason]**
- doesn't need tests because... **[provide a reason]**
> ci: configure detect-secrets #PLA-673

- packages/botonic-core/package.json
- packages/botonic-core/tsconfig.esm.json
- packages/botonic-core/tsconfig.json
* Distribute `@botonic/core` package as  `/lib/cjs` and `lib/esm`. (ref: https://blog.logrocket.com/publishing-node-modules-typescript-es-modules/)
* Added `sideEffects` flag to false to facilitate webpack to tree-shake the library.
Distributing it with CJS will allow us to use it in environments like Node.js, whereas esm will allow us to use it in browser and applications using webpack.
Despite having the following two lines declared @botonic/core:
```
"main": "./lib/cjs/index.js",
"module": "./lib/esm/index.js",
```
when using webpack, the resolved library will depend on how we import the code.
**e.g.:**
```
import { isFunction } from '@botonic/core' // --> will load automatically /lib/esm version of the code.
console.log(isFunction)
```
by compiling this with webpack in production …
> chore(core): cjs and esm distribution of core, enable @botonic/core tree-shaking

- .github/workflows/botonic-cli-tests.yml
- .github/workflows/botonic-nlu-tests.yml
- .github/workflows/botonic-plugin-dialogflow-tests.yml
- .github/workflows/botonic-plugin-intent-classification-tests.yml
- .github/workflows/botonic-plugin-ner-tests.yml
- .github/workflows/botonic-plugin-nlu-tests.yml
Sometimes publish-unit-test-result-action fails when dependabot opens the PR. See [example](https://github.com/hubtype/botonic/pull/1872/checks?check_run_id=3590602290): 
mark 'Publish Unit Test Results' step with `continue-on-error: true` so that ci workflow continues even test results step fails.
> ci: do not fail even that publish test reports fails #PLA-719

- .github/workflows/pre-commit.yml
- .secrets.baseline
- packages/botonic-plugin-contentful/src/util/backoff.ts
- scripts/qa/lint-d-ts.sh
- scripts/qa/lint-package.sh
Configure pre-commit checks to run in github actions
Before, the checks only ran in local
Include a specific workflow for this
Will be triggered on every PR action
> ci: configure pre-commit workflow #PLA-695

- packages/botonic-plugin-hubtype-babel/README.md
- packages/botonic-plugin-hubtype-babel/src/index.ts
The Inference endpoint now returns all predicted intents with their corresponding confidences, so we need to readapt the `plugin-hubtype-babel` to:
- Correctly get the intent and confidence.
- Add all intents to request input.
> feat(babel): Adapt Botonic Babel plugin to multiple intents #DAT-87

- packages/botonic-core/src/handoff.ts
- packages/botonic-core/tests/handoff.test.ts
Added a new function (`withAutoIdleMessage`) in `HandoffBuilder` in order to allow the developer to set the automatic message to be displayed once the case has been set to IDLE status.
A case is set to IDLE status if the user is not responding to the agent and we want to allow the bot to be able to set an automatic message to be displayed to the user once the case is set to IDLE so the user will be notified about the status change and the agent can be focused in other cases meanwhile.
`new HandoffBuilder(session).withAutoIdleMessage('messate to be displayed in IDLE status')`
> feat(core): Allow to set an auto idle message in Handoff Builder

- packages/botonic-core/src/core-bot.ts
- packages/botonic-react/src/components/index.d.ts
- packages/botonic-react/src/index.d.ts
- packages/botonic-react/src/webchat/webchat.jsx
Allow user input preprocess in the `blockInputs` configuration in order to sanitize the user input if needed.
Also, removed `BotOptions` interface to use `CoreBotConfig` instead.
Some text detection through regular expressions are easier if you can remove certain characters from the text before searching for matches (for example phone or credit card numbers)
Added a `preprocess` attribute in `blockInputs` option in webchat configuration that will be executed before doing the matches of the regular expressions to detect blocking words.
> feat(react): Allow user input preprocess in blockInputs

- packages/botonic-core/src/pusher-utils.ts
- packages/botonic-react/package-lock.json
- packages/botonic-react/src/components/button.jsx
Add class names to buttons depending on their type.
It can be useful sometimes to apply different styles depending on the button's destination (payload, url...) but without having fixed classes this is not possible.
Add a fixed class name to custom buttons and to normal buttons depending on the active attribute they have as a destination.
Classes created:
- `button-custom`
- `button-payload`
- `button-url`
- `button-path`
- `button-webview`
> feat(react): Add class names to buttons

- packages/botonic-core/package-lock.json
- packages/botonic-core/package.json
- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
Bump `@botonic/react` and `@botonic/core` packages to version `0.20.3` to englobe these changes:
- Fixed class names for buttons (#2220)
- User input preprocess in BlockInputs (#2219)
- Set auto idle message in HandoffBuilder (#2218)
Publish new patch version `0.20.3` for `@botonic/core` and `@botonic/react`
> chore(core/react): bump versions to 0.20.3

- packages/botonic-core/src/handoff.ts
- packages/botonic-core/tests/handoff.test.ts
Added 2 new functions in `HandoffBuilder`:
- `withForceAssignIfNotAvailable`: `True` by default. Allow to not assign the case (and set it in waiting status) to the selected agent if he is not available.
- `withAutoAssignOnWaiting`: `False` by default. Allow to assign the case automatically to an agent when the case is in the waiting queue.
We want to be able to:
- Not assign cases to away/busy agents (`forceAssignIfNotAvailable`)
- Allow the agents to not assign the cases in waiting queue manually and let the system assign them automatically.
- `forceAssignIfNotAvailable`: `new HandoffBuilder(session).withForceAssignIfNotAvailable(false)`
- `autoAssignOnWaiting`: `new HandoffBuilder(session).withAutoAssignOnWaiting(true)`
> feat(core): Handoff improvements (autoAssignOnWaiting and forceAssignIfNotAvailable)

- .pre-commit-config.yaml
- .secrets.baseline
Fix failing pre-commit config for [yelp's detect-secrets
](https://github.com/Yelp/detect-secrets)
Current config is failing because github is not accepting cloning repos with  `git:/...`
Use https to clone detect-secrets repo in .pre-commit-config.yaml
> chore(ci): fix failing pre-commit config

- .pre-commit-config.yaml
- packages/botonic-plugin-contentful/package-lock.json
- packages/botonic-plugin-contentful/package.json
- packages/botonic-plugin-contentful/src/cms/transform/message-content-filters.ts
- packages/botonic-plugin-contentful/src/contentful/cms-contentful.ts
- packages/botonic-plugin-contentful/src/contentful/contents/follow-up.ts
- packages/botonic-plugin-contentful/src/render/botonic-converter.ts
Allow document content model to be used as a followup.
Document content model was not allowed as a followup.
- doesn't need tests
> feat(plugin-contentful): add document as a followup

- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/webchat/use-storage-state-hook.js
- packages/botonic-react/tests/helpers/in-memory-storage.js
- packages/botonic-react/tests/webchat/storage.test.jsx
Refactor the `useStorageState` function to be more flexible and allow other types of storage than `localStorage` and `sessionStorage`.
There was no possibility to create a custom in-memory storage for Botonic.
Instead of using the `useLocalStorage` and `useSessionStorage` hooks from [react-use-storage](https://github.com/leny/react-use-storage) package we've copied the `useStorage` function of this same package to be more flexible and allow other type of storages.
> refactor(react): Allow storage other than localStorage and sessionStorage

- packages/botonic-plugin-hubtype-babel/package.json
- packages/botonic-plugin-hubtype-babel/src/hubtype-babel-api-service.ts
- packages/botonic-plugin-hubtype-babel/src/index.ts
- packages/botonic-plugin-hubtype-babel/src/options.ts
Now host where to run inference can be defined on `plugin-hubtype-babel` options.
Before this change, the plugin was always running inference on production. We also want to try the plugin in other environments.
Defined an optional variable that allows that indicates the host where to run inference. If not defined the host used would be https://api.hubtype.com (production environment).
> Feature: Add host variable to plugin-hubtype-babel options #DAT-340

- packages/botonic-react/src/components/image.jsx
In order to be able to display in full size an image shared within the webchat an image previewer was implemented in Botonic in order to display a modal in the middle of the screen with the image once it was clicked.
The problem is that when we tried the full solution we were getting an error of "Invalid hook call" (https://reactjs.org/warnings/invalid-hook-call-warning.html)
What is happening because we are calling the image previewer as a function instead of as a component.
Clicking on an image in the Bot opens a pop up with the image where we can zoom in and out, click outside the image to close the pop up or through the top bar with menus.
> Fixing Image previewer

- packages/botonic-react/src/components/message.jsx
Wrap all `<button>` elements of a message within a `<div>` element.
All message buttons are rendered as `<button>` elements alongside the `<div>` element of the message content, and to be able to apply styles to all buttons as a block (not only to the button element) a wrapper element is needed.
Add the class `botonic-buttons-container` to this new wrapper `div` to be able to change its style easily.
> feat(react): Wrap all message buttons into a div

- packages/botonic-react/src/webchat/components/emoji-picker.jsx
- packages/botonic-react/src/webchat/devices/scrollbar-controller.js
- packages/botonic-react/src/webchat/webchat.jsx
- add an empty css class to the div containing the user input, this way it will be easier to modify the css of this div.
> Botonic React: add user-input css class

- packages/botonic-plugin-flow-builder/src/action.tsx
- packages/botonic-plugin-flow-builder/src/handoff.ts
- packages/botonic-plugin-flow-builder/src/index.ts
Changes: 
- Remove all "getOpenQueues" logic and open/closed messages.
- The Handoff function should just do a basic handoff
- Added missing options: withNote, withAgent
> Plugin Flow Builder - Make handoff simpler 

- packages/botonic-core/package-lock.json
- packages/botonic-core/package.json
- packages/botonic-core/src/models/events/message/contact.ts
- packages/botonic-core/src/models/events/message/message-event.ts
- packages/botonic-core/src/output-parser/factory.ts
- packages/botonic-core/src/output-parser/parsers.ts
- packages/botonic-core/tests/parsing/contact.test.tsx
Add a new Message Event Type for Contact messages (comming from WhatsApp channel for example).
Bump version to `0.21.2`.
The MessageParsingFactory was throwing an error for Contact messages because were unknown by the parser.
> feat(core): Add Contact Message Event type

- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/components/index.d.ts
- packages/botonic-react/src/constants.js
- packages/botonic-react/src/webchat/components/attachment.jsx
- packages/botonic-react/src/webchat/components/common.jsx
- packages/botonic-react/src/webchat/components/conditional-animation.jsx
- packages/botonic-react/src/webchat/components/emoji-picker.jsx
- packages/botonic-react/src/webchat/components/persistent-menu.jsx
- packages/botonic-react/src/webchat/components/send-button.jsx
- packages/botonic-react/src/webchat/webchat.jsx
This PR adds the feature to define in the bot the icons to send an emoji and attach a file as you can do with the send text button by declaring a custom component
I didn't want to modify more things but I think the css should also be refactored to reduce the number of nested divs with fixed paddings to separate the elements. As you can see in the image the custom buttons are not well aligned.
Before change icons
After change icons
You can define custom components for each button like this
> Feat: custom user input buttons

- packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
- packages/botonic-plugin-flow-builder/src/flow-builder-models.ts
- packages/botonic-react/package-lock.json
- fix(plugin-flow-builder): fixing PayloadLocal in button
- feat(plugin-flow-builder): adding payload to buttons
- chore(plugin-flow-builder): updating package lock
> Plugin flow builder - Adding payload to buttons

- docs/docs/deployment/hubtype.md
- docs/docs/getting-started.mdx
- docs/docs/project-structure.md
- docs/src/components/examples.js
- docs/src/css/custom.css
- docs/src/pages/examples/index.js
The examples page (live demos) was not working links. 
The bots have been deployed, and some adjustments have been made to the bots. See this [PR](https://github.com/hubtype/botonic-examples/pull/15).
Improved images of the documentation for the sections: 
- Installation and Quick Start 
- Understanding the Project
Before: 
With hover:
After: 
With hover:
Before: 
After: 
Before: 
After: 
I have changed the color when hovering over the card component. Too many blue colors make it difficult to see the content. Now only the buttons change color when hovering.
`Check example` to `Visit` has been renamed, as it is more explicit.
Also I have entered the button texts, as they were misaligned.
> Botonic - Improve documentation (website)

- packages/botonic-react/src/webchat/components/attachment.jsx
When the same attachment is uploaded twice, the second one will not trigger the `onChange` event
https://user-images.githubusercontent.com/86048542/236981295-c82db95e-7c65-49ad-9dae-03997ee107a4.mov
https://user-images.githubusercontent.com/86048542/236982343-a2a43d1d-b56a-43e9-82f9-8bb3f03dd0f8.mov
Solved it by emptying the input.value value
- doesn't need tests because... **[very very minor changes]**
> fix: when the same attachment is uploaded twice, the second one will not trigger the onChange event

- packages/botonic-plugin-flow-builder/package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/functions/index.ts
- packages/botonic-plugin-flow-builder/src/index.ts
This PR adds the logic to detect that a button is of type payload read the payload content and put the text defined as payload in the payload that the bot receives. 
This way for example we can make that after a Handoff a payload rating is sent and this executes an action of the bot that depends on the channel it will send a custom component (webchat) or if it is receiving the rating it will save it. It will also be used to open webviews (in whatsapp we will use tamplates as it is necessary to create a button with the webview attribute)
When you create a button in flow builder that has a payload, this is a content with a payload object and what was received in the bot was the id of this content
- doesn't need tests because... …
> Plugin flow builder: payloads

- package-lock.json
- packages/botonic-core/package-lock.json
- packages/botonic-core/package.json
- packages/botonic-core/src/core-bot.ts
- packages/botonic-core/src/models/events/message/message-event.ts
- packages/botonic-core/src/models/legacy-types.ts
- packages/botonic-core/src/output-parser/parsers.ts
- packages/botonic-core/src/routing/router.ts
- packages/botonic-core/tests/routing/router.match-route.test.ts
- packages/botonic-core/tests/routing/router.misc.test.ts
Avoid executing the bot when receiving a 'chatevent' because so far it's used only to send typing on/off notifications to the backend (using the bot as a messenger)
When the user types something in the webchat, a 'chatevent' message is sent to the bot as an input message and this was generating an error when using the bot locally because there is no parser for this type of messages. Also, the bot was being executed and there is no need to be executed
The bot will be executed anyway when a 'chatevent' is received so to avoid executing all the `input` logic, I've added an early return if the input received is of 'chatevent' type.
The pull request has no new tests but some old tests have been fixed.
> feat(core): Don't execute bot when receiving a 'chatevent' 

- package-lock.json
- packages/botonic-core/package-lock.json
- packages/botonic-core/package.json
- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/components/message.jsx
- packages/botonic-react/src/components/multichannel/multichannel-text.jsx
- packages/botonic-react/src/util/webchat.js
Downgrade the `react` version to `16.14.0` to avoid conflicts with other `@botonic/react` packages.
Bump `@botonic/core` and `@botonic/react` versions to `0.22.0`.
There were some issues when using the latest alpha and beta versions in bots due to the use of `react` 17.
We will `switch` to react 17 once we're sure everything is working as expected with this version.
> chore(react/core): Downgrade react to version 16 + bump package versions to 0.22.0

- .pre-commit-config.yaml
- packages/botonic-plugin-flow-builder/package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action.tsx
- packages/botonic-plugin-flow-builder/src/api.ts
- packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/flow-carousel.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/flow-element.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/flow-text.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/nodes.ts
- packages/botonic-plugin-flow-builder/src/handoff.ts
- packages/botonic-plugin-flow-builder/src/helpers.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/types.ts
Multiple things have been done in this PR:
- Add pre-commit to the Flow Builder plugin.
- Fix the URL buttons issue to make them point correctly to the URL instead of to the content ID.
- Create a new `FlowBuilderApi` class to handle all the accesses to the flow instead of doing it in the plugin itself.
The URL buttons were not correctly generated in Botonic and they were pointing to the content ID instead of pointing to the URL.
Trying to solve this issue I came accross with a limitation of how the contents were being retreived from the flow and how the plugin was generating the final content to be sent to Botonic, that's why I ended up doing a refactor of this part.
The process of generating the flow contents (`FlowButton`, `FlowText`, etc.) was not being done within those clases but …
> Flow builder plugin: Fix url buttons + refactor

- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/components/message.jsx
- packages/botonic-react/src/constants.js
- packages/botonic-react/src/contexts.jsx
- packages/botonic-react/src/index-types.ts
- packages/botonic-react/src/webchat/hooks.js
- packages/botonic-react/src/webchat/messages-reducer.js
- packages/botonic-react/src/webchat/trigger-button/index.tsx
- packages/botonic-react/src/webchat/trigger-button/styles.ts
- packages/botonic-react/src/webchat/webchat-reducer.js
- packages/botonic-react/src/webchat/webchat.jsx
Be able to show in the trigger button the number of received and unread messages. I consider a message unread when I receive it and the webchat is closed.
In local is not working well as the message sets the ack to 1 directly.
Display a notification with the number of unread messages. 
CustomTriggerButton
DefaultTriggerButton
Each time the action of webchatReducer addMessageComponent is called if the webchat is closed and the message ack is 0, I increment the state of unreadMessages by 1. When I reset unreadMessages
The div displaying unread messages has className='trigger-notifications' to be able to adjust the css
> Trigger Button with notifications

- packages/botonic-react/src/components/image.jsx
- packages/botonic-react/src/util/environment.js
- packages/botonic-react/src/webchat/webchat.jsx
If the user sends an image through the bot it is not rendered correctly. This fails because staticAsset only renders images from a public URL. 
User attaches an image to the webchat
(first commit only works in local) In order to render an image within a message, add the `bolb` format in the isURL function which is used by staticAsset.
(second commit) To make the first render after attaching an image you can use the input.data which contains the base 64 string of the image. If you reload the webchat this string will no longer be used , in the localStorage message the url where the image was uploaded is saved.
> botonic-react: render images sent to the bot by user

- packages/botonic-react/src/components/index-types.ts
- packages/botonic-react/src/util/environment.js
add the type of imagePreviewer in the ThemeProps.
So when using the image preview plugin we don't get the type error in webchat/index.ts
> botonic-react: add imagePreviewer in ThemeProps

- packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-agent-rating.ts
- packages/botonic-plugin-hubtype-analytics/src/index.ts
- packages/botonic-plugin-hubtype-analytics/src/types.ts
Fixed typo in getLanguage option.
- doesn't need tests
> Plugin Hubtype Analytics: fix get language typo

- packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-agent-rating.ts
- packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-bot-knowladge-base.ts
- packages/botonic-plugin-hubtype-analytics/src/index.ts
- packages/botonic-plugin-hubtype-analytics/src/types.ts
Add the event to track when the bot response is created by a knowledge base
It is now possible to connect a bot to a knowledge base (previously uploaded to the dashboard) we want to track when this response is being used
> Plugin Hubtype Analytics: create knowledge base event

- packages/botonic-core/src/hubtype-service.ts
- packages/botonic-core/src/utils.ts
- packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
- packages/botonic-plugin-flow-builder/src/utils.ts
- Deploy bot in prod/qa/dev with with environment variables set hubtype/infrastructure repository deploy_bot_etc functions.
- Makes a fix to the isBrowser function to solve a problem detected a few days ago in some websites where process.env existed inside the browser.
The getWebpackEnvVar function did not work correctly and ended up always putting the production url and the production pusher key
instead of using the getWebpackEnvVar function, I read directly process.env and if this is undefined, the HUBTYPE_API_URL or PUSHER_KEY of the production will be used.
> Feature: deploy bot in prod/qa/dev

- packages/botonic-plugin-knowledge-bases/README.md
Fix package name in `README` file.
The `README` had wrong package name.
> docs(plugin-knowledge-bases): fix wrong npm package name

- packages/botonic-plugin-knowledge-bases/package-lock.json
- packages/botonic-plugin-knowledge-bases/package.json
- packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
- packages/botonic-plugin-knowledge-bases/src/index.ts
- packages/botonic-plugin-knowledge-bases/src/types.ts
Add a new `question` attribute into the Knowledge Bases responses.
This new attribute was added in the response to see the standalone question used to get the response from ChatGPT.
> feat(knowledge-bases): add question attribute in the response

- packages/botonic-plugin-contentful/src/contentful/contents/contents.ts
- Allow requesting up to 2000 contents with the `topContents` method
- Some clients have more than 1000 contents of type text on Contentful and they are not able to visualize all of them in the flow builder because there is a limit per request of 1000
- When we detect that there are more than 1000 contents we make the request again to get the next 1000 contents
> Feat: increase the limit of contents in topContents method

- packages/botonic-plugin-contentful/package-lock.json
- packages/botonic-plugin-contentful/package.json
- packages/botonic-plugin-contentful/tests/contentful/manage/manage-contentful-environment.ts
- packages/botonic-plugin-contentful/tests/plugin.test.ts
In the free Contentful account where we have everything related to testing, now we can only have master and 2 environments. We had a test that creates and deletes an environment. This test was failing because there was not enough space. I have merged 2 environments into one (deleting the testx environment after copying all the content to manage-contentful.
Released plugin version 0.23.1
> Contentful plugin publish 0.23.1

- packages/botonic-plugin-hubtype-babel/src/hubtype-babel-api-service.ts
- packages/botonic-plugin-hubtype-babel/src/index.ts
- packages/botonic-plugin-hubtype-babel/src/options.ts
Read HUBTYPE_API_URL from process.env.HUBTYPE_API_URL or use production api (https://api.hubtype.com) if it is undefined 
This is how it is used in the rest of the plugins and core
Reading this url from the environment variable and if it is not set to use the default production api, it is no longer necessary to pass the host through the plugin constructo
> Plugin hubtype babel: read HUBTYPE_API_URL from process.env

- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
- packages/botonic-react/src/webchat/hooks/use-typing.ts
- packages/botonic-react/src/webchat/webchat.jsx
When doing a handoff you need to have the userInput of the webchat enable and this is not always the case for all bots. 
From the flow builder plugin always enable userInput when do a handoff.  
If no other message is sent with the WebchatSettings the typing is set to true. That's why I also modify @botonic/react to set it to false when updating the WebchatSettings.
> Plugin flow builder: open user input in webchat when do handoff

- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
- packages/botonic-react/src/components/custom-message.jsx
- packages/botonic-react/src/webchat-app.jsx
- packages/botonic-react/src/webchat/hooks/use-typing.ts
- packages/botonic-react/src/webchat/message-list/scroll-button.tsx
- packages/botonic-react/src/webchat/message-list/unread-messages-banner.tsx
- packages/botonic-react/src/webchat/webchat.jsx
This PR fixes two issues introduced in version 0.24.0 of @botonic/react.
1) Custom components did not have the customMessage name as className.
2) The ScrollButton and BannerUnreadMessages components rendered nothing if this feature was not used. 
1) Custom components did not have the customMessage name as className. This happened because the deserialize function of the Custom component did not pass the new sentBy and isUnread attributes. 
As these attributes were not serialised in the Message component, a check was made to define the className that verified that the CustomMessage was sent by the bot. Prior to version 0.24.0 if from (sentBy now) was not defined then SENDERS.bot was set by default.
2) The ScrollButton and BannerUnreadMessages components rendered nothing if this feature was …
> Fix: className in CustomMessage, avoid render undefined in ScrollButton and BannerUnreadMessages

- CHANGELOG.md
- packages/botonic-plugin-flow-builder/package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/action/intent.ts
- packages/botonic-plugin-flow-builder/src/action/keyword.ts
- packages/botonic-plugin-flow-builder/src/action/user-input.ts
- packages/botonic-plugin-flow-builder/src/api.ts
- packages/botonic-plugin-flow-builder/src/constants.ts
- packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/bot-action.ts
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/index.ts
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/node-types.ts
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/nodes.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/types.ts
- adds the functionality to use BotActionNode created in the FlowBuilder frontend.
- add a function to getPayloadParams in JSON format when receiving a payload.
- add a base type for payloadParams 
A BotAction node can target 4 types of nodes: Button, Handoff, Keyword and Intent
When the target is a Button (from Text, Carousel or WhatsappButtonList) or a Handoff in the botonicInit function of the plugin-flow-builder we must obtain the payload defined in the BotAction node and replace it. This way when the user clicks on a button or executes a handoff the payload will be the correct one.
With Keywords and Intents it is different, what we want is that when the bot executes the routes, the payload is already in the request so that the route of the action indicated by the payload is executed. …
> plugin-flow-builder: handle bot action on the flow builder plugin #BLT-483

- CHANGELOG.md
- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/components/message/index.jsx
When a message is sent by the agent it must have the same styles as a message sent by the bot
When the feature of being able to change the image in the agent messages was added, the SENDERS.agent was added.
It was necessary to change the order of the conditional to apply the bot styles to non-user messages.
> Fix: agent message styles use botMessageStyle

- packages/botonic-plugin-flow-builder/package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/function.ts
- packages/botonic-plugin-flow-builder/src/functions/conditional-queue-status.ts
- packages/botonic-plugin-flow-builder/src/index.ts
Now in the FlowBuilder frontend we can have queue conditionals, which check if there are available agents with a check box. This generates a conditional queue with 3 outputs.
The node with 3 outputs will look like this
```typescript
{
id: 'b0b61028-b683-4ea6-ba7d-b79ca160e438',
code: 'CONDITIONAL_QUEUE',
meta: { x: 358.20617669934023, y: 352.83848058278346 },
follow_up: null,
target: null,
flow_id: '8d527e7d-ea6d-5422-b810-5b4c8be7657b',
type: 'function',
content: {
action: 'check-queue-status',
arguments: [
{
type: 'boolean',
name: 'check_available_agents',
value: true,
},
{
locale: 'en',
values: [
{
type: 'string',
name: 'queue_id',
value: 'e7a2304d-f73c-409d-b272-239a9b8a9e0e',
},
{ type: 'string', name: 'queue_name', value: 'General' },
],
},
],
result_mapping: [
{
result: 'open', …
```
> plugin-flow-builder: check if agents are available in conditional queue 

- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/components/custom-message.jsx
- packages/botonic-react/src/webchat/messages-reducer.ts
- packages/botonic-react/tests/components/__snapshots__/custom-message.test.jsx.snap
Fixes a bug that occurred when developing locally. The bug is that the css class was not added to the custom message. This happened because the sentBy is not set as local is rendered directly in the browser.
> botonic-react: in custom messages set for default sentBy to bot

- CHANGELOG.md
- packages/botonic-plugin-flow-builder/package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/api.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
Add a function to resolve from a locale received from the bot to a locale/language of the flow array. 
Before we had this function if the bot passed as locale `es-ES` and the flow was only set to `es` the plugin failed and the bot did not return a reply. If we had a bot that used generic English `en` for all countries and the plugin received an `en-ES` locale the plugin failed and the bot did not return a reply.
The bot will always pass a locale e.g: `es-ES`, `en-ES`, `ca-ES`
If the plugin has flow for this locale it will use it, otherwise it will look for flow for simple language `es`, `en`, `ca`
> plugin-flow-builder: resolve the bot's locale by searching the flow's locale array

- packages/botonic-plugin-flow-builder/package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list-row.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list-section.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list.tsx
- packages/botonic-plugin-flow-builder/src/index.ts
Be able to use bot actions in whatsapp button list
The bot actions connected to a whatsapp button list were not working.
Apply the logic used in the button also in the row of the whatsapp button list.
> plugin-flow-builder: be able to use bot actions in whatsapp button list

- packages/botonic-plugin-flow-builder/src/functions/conditional-country.ts
- packages/botonic-plugin-flow-builder/src/functions/conditional-provider.ts
- packages/botonic-plugin-flow-builder/src/functions/index.ts
Now in the FlowBuilder frontend we can define a country conditional, which checks which country the bot has defined in session.user.extra_data.country to follow the flow.
The node with 4 outputs
```
{
"id": "39eaa899-00b9-4251-aec1-bc70264cb33a",
"code": "",
"is_code_ai_generated": false,
"meta": {
"x": -203.16711080845553,
"y": 797.2281904144527
},
"follow_up": null,
"target": null,
"flow_id": "8d527e7d-ea6d-5422-b810-5b4c8be7657b",
"type": "function",
"content": {
"action": "check-country",
"arguments": [],
"result_mapping": [
{
"result": "default",
"target": {
"id": "9d171089-82b0-409b-ac2c-93ddc289fb7e",
"type": "image"
}
},
{
"result": "CA",
"target": {
"id": "3e51200b-a385-4758-ab09-9978ca6888b3",
"type": "text"
}
},
{
"result": "FR",
"target": {
"id": …
```
> plugin-flow-builder: country conditional function

- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/constants.ts
- packages/botonic-plugin-flow-builder/src/content-fields/flow-text.tsx
- packages/botonic-plugin-flow-builder/src/functions/conditional-bot-variable.ts
- packages/botonic-plugin-flow-builder/src/functions/index.ts
- packages/botonic-plugin-flow-builder/src/utils.ts
Add the function to resolve custom conditional node. 
This allows to check any variable(string, boolean, number) inside `request.session.user.extra_data`
These conditionals have one output for each check plus a `default`. 
When the variable being tested is a boolean the false and default output is the same. This resolves the case where you are testing a boolean that is currently undefined.
You can use variables that are nested in objects within extra_data. 
For example if you have the following extra_data object:
```typescript
const extra_data = {
isLoggedIn: true,
numberOfBags: 1,
vehicle: 'bike',
booking: {
payment: {
isPaid: false,
type: 'cash',
},
},
}
```
You can access any variable by specifying the name with a string. If nested as isPaid or type the string must be dotted as if you …
> plugin-flow-builder: add custom conditional

- packages/botonic-plugin-flow-builder/src/api.ts
- packages/botonic-plugin-flow-builder/src/constants.ts
Being able to define keywords as regular expressions in the flow builder frontend, using the RegExp /pattern/flags format.
If the plugin detects that the keyword is a regular expression it will apply this in the user input, otherwise it will do the logic that was done until now to check if the exact word is in the user input.
The keyword node until now could only pass words and what it checked was if the user input contained that word exactly as it was written, including upper and lower case.
With this new feature we can use regex to do pattern matching.
First it checks if the keyword is a regex if so it applies the regex on the user input. Otherwise it will do the logic that was done until now looking if the user input contains this word written as in the keyword node.
By using regex on …
> plugin-flow-builder: resolve regex in keywords

- packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
- packages/botonic-plugin-knowledge-bases/src/index.ts
Add in the api response the attribute is_faithful which indicates if the IA is trustworthy (has no hallucinations).
If this parameter is false we pass the hasKnowledge to the bot as false so that it does not use the response generated by the AI.
> plugin-knowledge-bases: add is_faithful param in api response

- CHANGELOG.md
- packages/botonic-core/src/models/legacy-types.ts
- packages/botonic-react/jest.config.js
- packages/botonic-react/src/components/button.jsx
- packages/botonic-react/src/components/index.ts
- packages/botonic-react/src/components/multichannel/multichannel-text.jsx
- packages/botonic-react/src/components/multichannel/multichannel-utils.js
- packages/botonic-react/src/components/whatsapp-cta-url-button.tsx
- packages/botonic-react/src/util/webviews.ts
- packages/botonic-react/tests/components/__snapshots__/whatsapp-cta-url-button.test.jsx.snap
- packages/botonic-react/tests/components/multichannel/__snapshots__/multichannel-carousel.test.jsx.snap
- packages/botonic-react/tests/components/whatsapp-cta-url-button.test.jsx
[Whatsapp Docs](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-messages?content_id=EhJZ0uS1mCvxd14#cta-url-buttons)
Added support for WhatsappCTAUrlButton by creating a new component.
Right now we didn't have a way to send a button with a webview in Whatsapp without showing the entire webview url or urls
Multichannel implemenation will be replacing only texts coming with 1 button at this moment to this new created component, so this has to be taken in consideration when designing flows.
Usage with URLs:
```
export class TestAction extends React.Component {
static contextType = RequestContext
render() {
return (
<WhatsappCTAUrlButton
header='This is a header'
body='This is **CTA Url Body**'
footer='This is a footer'
displayText='Go to Hubtype' …
```
> feat(react): WhatsappCTAUrlButton

- CHANGELOG.md
- package-lock.json
- packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/flow-whatsapp-cta-url-button.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/node-types.ts
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/nodes.ts
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/whatsapp-cta-url-button.ts
- packages/botonic-plugin-flow-builder/src/content-fields/index.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-react/src/components/whatsapp-cta-url-button.tsx
Now we can have a whatsapp node containing a single button that redirects to a URL. When the plugin receives the JSON that defines a node of this type it will use a WhatsappCTAUrlButton from @botonic/react to render it.
Example of JSON defining this node
```
{
"id": "a0898927-42f6-45a5-8c6a-66bdd92f0e13",
"code": "test url",
"is_code_ai_generated": false,
"meta": {
"x": -80.59924537568803,
"y": -221.97477364675905
},
"follow_up": null,
"target": null,
"flow_id": "8d527e7d-ea6d-5422-b810-5b4c8be7657b",
"type": "whatsapp-cta-url-button",
"content": {
"text": [
{
"message": "this is a text",
"locale": "es"
},
{
"message": "this is a text",
"locale": "it"
}
],
"header": [
{
"message": "this is a header",
"locale": "es"
}
],
"footer": [
{
"message": "this is a footer",
"locale": "es"
}
], …
```
> plugin-flow-builder: add whatsapp CTA url button

- .github/workflows/botonic-plugin-flow-builder-tests.yml
- package-lock.json
- packages/botonic-plugin-flow-builder/babel.config.js
- packages/botonic-plugin-flow-builder/jest.config.js
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/api.ts
- packages/botonic-plugin-flow-builder/src/constants.ts
- packages/botonic-plugin-flow-builder/src/content-fields/flow-button.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/button.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
- packages/botonic-plugin-flow-builder/tests/bot-action.test.ts
- packages/botonic-plugin-flow-builder/tests/helpers/flows.ts
- packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
- packages/botonic-plugin-flow-builder/tsconfig.tests.json
When using a Bot Action node with parameters that is connected to a follow up. It is easy to exceed the character limit allowed by Telegram (64bytes = 64 characters).
When connecting a BotActionNode to a button the payload will be ba|BotActionNodeUUID|source_x
In the pre function of the plugin: first the |source_x is removed, then if a payload starting with ba| is detected the BotActionNode is obtained using the botActionNodeUUID and the payload is replaced by the payload plus the parameters defined in the BotActionNode.
When we get to the bot routes we have the payload with the parameters.
In the action we can continue using the getPayloadParams function as we did before.
Add config for jest and github action
Add test for first interaction 
Add test for bot action node
> plugin-flow-builder: bot action limit characters

- packages/botonic-plugin-flow-builder/src/content-fields/index.ts
- packages/botonic-plugin-flow-builder/tests/helpers/flows/basic.ts
- packages/botonic-plugin-flow-builder/tests/messages/flow-button-list.test.ts
- packages/botonic-plugin-flow-builder/tests/messages/flow-carousel.test.ts
- packages/botonic-plugin-flow-builder/tests/messages/flow-image.test.ts
- packages/botonic-plugin-flow-builder/tests/messages/flow-text.test.ts
- packages/botonic-plugin-flow-builder/tests/messages/flow-url-button.test.ts
- packages/botonic-plugin-flow-builder/tests/messages/flow-video.test.ts
Add tests for each type of message 
- Text
- Carousel
- Image
- Video
- WhatsApp button list
- Whatsapp CTA URL button
Keywords are used to reach the node to be tested
This PR only contains tests of the different types of messages
> plugin-flow-builder: test different types of messages

- packages/botonic-react/src/webview-app.tsx
When closing facebook messenger webviews the payload was sent but the webview did not close.
Add fallback to close the window in case the MessengerExtensions are not available
> botonic-react: Fix webviews not closing on fb #PLA-2162

- CHANGELOG.md
- package-lock.json
- packages/botonic-core/package.json
- packages/botonic-core/src/handoff.ts
- packages/botonic-dx/package.json
- packages/botonic-plugin-hubtype-babel/package.json
- packages/botonic-plugin-hubtype-babel/src/index.ts
- packages/botonic-plugin-knowledge-bases/package.json
- packages/botonic-plugin-knowledge-bases/src/index.ts
- packages/botonic-react/package.json
publish alpha versions:
- @botonic/core: 0.26.1-alpha.0
- @botonic/plugin-hubtype-babel: 0.26.1-alpha.2
- @botonic/plugin-knowledge-bases: 0.26.1-alpha.0
- @botonic/react: 0.26.2-alpha.0
- @botonic/plugin-flow-builder: 0.26.2-alpha.0
> Botonic version 0.26.x-alpha before 0.27.0

- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/common.ts
- packages/botonic-plugin-flow-builder/src/tracking.ts
* Updated plugin flow builder to use is_meaningful node
> fix(plugin-flow-builder): add is meaningful node tracking #874

- package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action/fallback.ts
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/common.ts
- packages/botonic-plugin-flow-builder/src/tracking.ts
- packages/botonic-plugin-hubtype-analytics/package.json
- packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-custom.ts
- packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-fallback.ts
- packages/botonic-plugin-hubtype-analytics/src/types.ts
- packages/botonic-plugin-hubtype-analytics/tests/event-custom.test.ts
- packages/botonic-plugin-hubtype-analytics/tests/event-fallback.test.ts
* Removed outdated interface https://github.com/hubtype/botonic/pull/2851/commits/c737dc18eb99c6cf9f1f0124719a319e0379b8bb
* Added customSensitiveFields in EventCustom https://github.com/hubtype/botonic/pull/2851/commits/80927b6c9ddd924f1807463cee8b43855ffb78df
* Added userInput in EventFallback https://github.com/hubtype/botonic/pull/2851/commits/ab1f5ad4a53990343e05ab5760dc431232489802
* Call plugin-flow-builder's trackEvent fallback with user input field https://github.com/hubtype/botonic/pull/2851/commits/3f704fc5d7baf10b3742aae682c557825feb9f9b
* Added is_meaningful tracking https://github.com/hubtype/botonic/pull/2851/commits/5372468a0a79b03765054ddfa905c1f2ffd53e94
> fix: update Custom, Fallback and FlowNode (is_meaningful) events with missing fields and use them #BLT-888

- package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/tracking.ts
Create the flowThreadId in the tracking function if it does not exist.
When tracking content the flowThreadId is required in the backend.
If this happens in a conversation that already existed before adding the plugin the bot does not go through the function getStartContents, which is where this flowThreadId is generated and at the time of tracking the content fails because this value is not undefined.
> plugin-flow-builder: fix uuid for flowThreadId 

- packages/botonic-react/src/components/multichannel/multichannel-text.jsx
Add params in WhatsappCTAURLButton when replacing a Button that leads to a webview with params using the Multichannel component
> botonic-react: add params in WhatsappCTAURLButton when use it inside Multichannel

- package-lock.json
- packages/botonic-react/package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/util/environment.js
- packages/botonic-react/tests/utils.test.js
Changed how `staticAsset` function is searching for the script to resolve the assets path.
The function is only searching for scripts that end with "webchat.botonic.js" so if the webchat file has another name it won't work.
Change the query done in the function to check that the script contains "webchat.botonic.js"
Added unit tests to test the function.
> Botonic-React: change staticAsset function + add unit tests

- package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action/first-interaction.ts
- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
- packages/botonic-plugin-flow-builder/src/action/payload.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/user-input/index.ts
- packages/botonic-plugin-flow-builder/src/utils.ts
- packages/botonic-plugin-flow-builder/tests/__mocks__/knowledge-base.ts
- packages/botonic-plugin-flow-builder/tests/first-interaction.test.ts
- packages/botonic-plugin-flow-builder/tests/helpers/flows/basic.ts
- packages/botonic-plugin-flow-builder/tests/helpers/flows/knowledge-base.ts
- packages/botonic-plugin-flow-builder/tests/knowledge-base.test.ts
If the user sends a text that matches a keyword, smart intent or intent in the first interaction, the bot's response is the contents of the start conversation followed by the contents of the match.
If the bot has an active knowledge base after trying to match the above and not getting a match, it will attempt to respond using the knowledge base. If it has sufficient knowledge and the response is faithful the bot will display the start contents followed by the response generated using the knowledge base.
We want the bot in platforms that are not proactive (such as Whatsapp) where the user is the first to write, if the user asks something in the first inbox, the bot will solve it the first time. But the initial contents have to be shown because they usually contain the GDPR and the AI …
> plugin-flow-builder: resolve keywords, smart intents and intents in first interaction

- packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
Avoid sending the WebcatSettings message when the channel isn't webchat or local development
> plugin-flow-builder: avoid send webchatsettings when channel in't webchat

- package-lock.json
- packages/botonic-plugin-flow-builder/README.md
- packages/botonic-plugin-flow-builder/package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/webview/contents-context.ts
- packages/botonic-plugin-flow-builder/src/webview/index.ts
- packages/botonic-plugin-flow-builder/src/webview/types.ts
- packages/botonic-plugin-flow-builder/src/webview/use-webview-contents.ts
- The functions `getTextContent` and `getImageSrc` return an empty string if it does not find the value.
- The `useWebviewContents` hook accept an object mapContents. This object relates the names the developer wants for each content to the contentID of each content. Using this object the hook returns a contents object with all the contents. 
The hook useWebviewContents now returns a contents object which is like the mapContents passed as a parameter but with the relation `key: fetchedContent`
An important point is to have the `contents` object typed the same as the `mapContents`
To have the `contents` typed like the `mapContents` it is necessary create `MyWebviewContentsContext` outside the webview component and export it to be able to use it inside the components. 
To create this …
> plugin-flow-builder: create contents with map

- CHANGELOG.md
- packages/botonic-core/src/core-bot.ts
- packages/botonic-core/src/handoff.ts
- packages/botonic-core/src/models/legacy-types.ts
- packages/botonic-core/tests/core-bot/core-bot.test.ts
- packages/botonic-core/tests/handoff.test.ts
- packages/botonic-core/tests/helpers/core-bot.ts
- packages/botonic-core/tests/helpers/routing.ts
- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
- packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
- packages/botonic-plugin-hubtype-analytics/src/index.ts
- packages/botonic-plugin-hubtype-analytics/tests/helpers/index.ts
* Type `is_test_integration` in `Session`.
* Avoid calling botonic-plugin-hubtype-analytics when bot has `session.is_test_integration` set to true.
* Do call smart intents inference with use_latest parameter set to false if bot has `session.is_test_integration` set to true.
* Flow Builder plugin to fetch only draft version of the flow if bot has `session.is_test_integration` set to true.
* FB Plugin and core coordinated to being able to execute a first input with a simulation of the handoff, and a preceding input to emulate the on finish payload after this faked handoff.
This PR contains the needed implementations in the botonic side to avoid test integration bots to produce not expected data and pollute metrics, this is, not calling analytics, faking handoff, ... if bots are of this …
> Feat/handle preview for is_test_integration apps

- packages/botonic-core/src/core-bot.ts
- packages/botonic-core/src/handoff.ts
- Refactor the core-bot, create small functions and reuse the runInput function inside the runFollowUpTestIntegrationInput function.
- Avoid storeRatingCase when is_test_integration is true
> Fix bot action after handoff in test integration preview

- package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/botonic-tester.jsx
* Replace `unescape.decode()` function by a simpler one with a list of well-known HTML Entities. This dependency is only used for using BotonicInput/OutputTesters and can be easily replaced by a function.
* Remove unused dependencies `qrcode.react` and `he` (which come from previous 1.0 test version of botonic)
> botonic-react: remove unescape, qrcode.react and he dependencies

- CHANGELOG.md
- package-lock.json
- packages/botonic-plugin-knowledge-bases/package.json
- packages/botonic-plugin-knowledge-bases/src/hubtype-knowledge-api-service.ts
- packages/botonic-plugin-knowledge-bases/src/index.ts
- packages/botonic-plugin-knowledge-bases/src/types.ts
Update endpoint to `/knowledge_base/inference/` 
This endpoint use source ids instead of source names
> plugin-knowledge-bases: update api endpoint to use source ids #BLT-983

- package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/webchat/webchat.jsx
* Removed react's `use-async-effect` and `reconnecting-websocket` dependencies.
> botonic-react: remove use-async-effect dependency

- packages/botonic-cli/src/botonic-api-service.ts
- packages/botonic-cli/src/commands/deploy.ts
- packages/botonic-cli/src/util/bot-config.ts
- packages/botonic-cli/tests/commands/deploy.test.ts
- Not read or write the bot.config.json file, just get the bot config values to send them in the post when deploying.
- Use the ora spinner to give feedback to the user: Getting bot config...
> botonic-cli: no read/write bot.config.json

- packages/botonic-react/src/webchat/actions.ts
- packages/botonic-react/src/webchat/hooks/use-webchat.ts
- packages/botonic-react/src/webchat/index-types.ts
- packages/botonic-react/src/webchat/webchat-reducer.ts
Removing code from botonic 1.0, not useful anymore
> refactor: remove jwt code logic

- CHANGELOG.md
- packages/botonic-react/src/node-app.jsx
Remove the getConfig function that is run to get the response from the botonic-config lambda.
In the new version of cli we will create the bot configuration at the moment of deploying, it will be saved in the database and will be updated in each deploy. We will not only have the plugins configuration.
> botonic-react: remove getConfig function #BLT-1036

- CHANGELOG.md
- package-lock.json
- packages/botonic-core/src/core-bot.ts
- packages/botonic-core/src/handoff.ts
- packages/botonic-core/src/models/legacy-types.ts
- packages/botonic-core/tests/core-bot/core-bot.test.ts
- packages/botonic-core/tests/handoff.test.ts
- packages/botonic-plugin-flow-builder/src/action/first-interaction.ts
- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/action/payload.ts
- packages/botonic-plugin-flow-builder/src/api.ts
- packages/botonic-plugin-flow-builder/src/constants.ts
- packages/botonic-plugin-flow-builder/src/content-fields/flow-bot-action.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/bot-action.ts
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/node-types.ts
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/nodes.ts
- packages/botonic-plugin-flow-builder/src/content-fields/index.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/tests/bot-action.test.ts
- packages/botonic-react/src/webchat/utils.ts
- packages/botonic-react/src/webchat/webchat.jsx
Be able to use bot-action nodes at any point in the flow builder. For example as follow ups, after a conditional, at the start of a flow etc
The request.input should be immutable. To avoid modifying the request.input in the lambda execution, FlowBuilderAction.botonicInit function accepts as a second parameter the contentID to indicate which content has to be rendered. This contentID is the unique text that is defined in the flow builder frontend. This way you don't need to get the UUID of the content and modify the request.input.payload to indicate to the plugin which content to render.
Bot-action nodes could only be used connected to a button or after a handoff.
With this solution it will be possible to make flow in a simpler way. There are several use cases in which the flow is greatly …
> plugin-flow-builder: bot action as follow up, first node in a flow, after conditionals etc

- CHANGELOG.md
- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/api.ts
- packages/botonic-plugin-flow-builder/tests/payload.test.ts
When user clicks on old button that is no longer in the published flow, the bot will respond with fallback content.
Until now when the user clicked on an old button and the published flow no longer has this button the bot did not respond
If a content id is not found, the bot will respond with a fallback.
Add two tests to check contents displayed after click a button with payload
> plugin-flow-builder: when user clicks on old button send fallback #BLT-1070 

- packages/botonic-plugin-flow-builder/src/tracking.ts
Save the flow_thread_id in the session each time a new flowThreadId is generated
When a bot does not go through the conversation start of the flow, the plugin was not saving the flow_thread_id in the session.
> plugin-flow-builder: store in session every new flow_thread_id

- CHANGELOG.md
- packages/botonic-plugin-flow-builder/src/api.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/types.ts
- packages/botonic-plugin-flow-builder/src/webview/use-webview-contents.ts
- Resolve locale as a language when get webview contents. For example if locale is en-GB and your contents are only in en
- set organzation_id and bot_id in session when bot is in local development.
> improve flowbuilder webview contents #BLT-1131 

- packages/botonic-plugin-flow-builder/src/content-fields/flow-text.tsx
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
Use getAccessToken to get token for smart intents for work in local
> Smart intents in local

- package-lock.json
- packages/botonic-cli/README.md
- packages/botonic-cli/package.json
- packages/botonic-cli/src/botonic-api-service.ts
- packages/botonic-cli/src/commands/deploy.ts
- packages/botonic-cli/src/interfaces.ts
Add await when call getMoreBots
Remove duplicated call to getBots inside deployBotFromFlag function
Add generic type T to apiGet function
> cli: fix error fetching more bots

- packages/botonic-react/src/components/multichannel/multichannel-text.jsx
- packages/botonic-react/src/components/multichannel/whatsapp/markdown.ts
Apply the same whatsapp markdown for Facebook.
Replace markdown for links `[text](url)` for ` text: url` for both whatsapp and facebook
Facebook markdown https://www.facebook.com/help/147348452522644
Whatsapp markdown https://faq.whatsapp.com/539178204879377/?cms_platform=web
> botonic-react: messenger markdown not applied #BLT-1152 

- packages/botonic-react/src/components/multichannel/multichannel-text.jsx
- packages/botonic-react/src/components/multichannel/whatsapp/markdown-meta.ts
- packages/botonic-react/src/components/multichannel/whatsapp/markdown.ts
- packages/botonic-react/src/components/whatsapp-button-list.tsx
- packages/botonic-react/src/components/whatsapp-cta-url-button.tsx
- packages/botonic-react/tests/components/multichannel/markdown.test.js
Refactor to simplify the code used to apply markdown in Whatsapp and Facebook 
A sentence with bold and italic at the same time is not rendered correctly. For example in the following sentence the bold was not applied on the word `agentes`
`_Recuerda que si es por una incidencia en la entrega o recepción, puedes contactar con nuestros __agentes__ para que te ayuden lo antes posible_`
Instead of normalizing directly with the result * or _ now use the words &%BOLD%& and &%ITALIC%&
I have added the &% symbols at the beginning and end to make it less probable that this is written in the bot message.
Adds tests for several markdown use cases
> botonic-react: fix mixed markdowns used in the same text #BLT-1177 

- package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/components/index-types.ts
- packages/botonic-react/src/contexts.tsx
- packages/botonic-react/src/index-types.ts
- packages/botonic-react/src/webchat/cover-component/index.tsx
- packages/botonic-react/src/webchat/webchat.jsx
Create a separate file for the cover component (using typescript and reducing the size of the webchat file).
Add the toggleCoverComponent function in the WebchatContext to avoid having to pass the function using props
Removing the scroll in a previous PR was not rendering the cover component correctly
Use a conditional render to render the cover component or the webchat. It is not necessary to render the messages under the cover component.
> botonic-react: fix cover component in botonic react #BLT-1223

- package-lock.json
- packages/botonic-plugin-flow-builder/src/api.ts
- packages/botonic-plugin-flow-builder/src/constants.ts
- packages/botonic-plugin-flow-builder/src/index.ts
Avoid using getNodeById inside the isBotAction function to not show a log `Node with id X is not found` every time that bot received a custom payload
> plugin-flow-builder: not show log when check if payload is from bot action node

- package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action/index.tsx
Create `executeConversationStart` to allow handoffs and bot actions in typical WelcomeAction. 
If in a WelcomeAction you get the contents connected to the Conversation Start using 
```
const contents = pluginFlowBuilder.getStartContents()
```
but you do not execute the `FlowBuilderAction.botonicInit(request, contentID)` where contentID is `contents[0].code` neither the handoffs nor the bot actions are executed.
Now you can write WelcomeAction as: 
```
export class WelcomeAction extends FlowBuilderMultichannelAction {
static contextType = RequestContext
static async botonicInit(
request: BotRequest
): Promise<FlowBuilderActionProps> {
//extra logic
return await super.executeConversationStart(request)
}
}
```
> plugin-flow-builder: create executeConversationStart #BLT-1259

- package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-hubtype-analytics/package.json
- packages/botonic-plugin-hubtype-analytics/src/types.ts
@botonic/plugin-hubtype-analytics published in 0.30.2
Add a `needs_escalation` as a new WebviewEndFileType
@botonic/plugin-flow-builder published in 0.30.8
export type HtBotActionNode
> Add needs escalation as a webview end fail

- package-lock.json
- packages/botonic-react/package.json
- packages/botonic-react/src/webchat/hooks/use-scroll-to-bottom.ts
- packages/botonic-react/src/webchat/message-list/index.tsx
- packages/botonic-react/src/webchat/message-list/styles.ts
Replace the `behavior: 'smooth'` attribute set to the `scrollIntoView` calls for a `scroll-behavior: 'smooth'` CSS property set in the `ScrollableMessageList` component.
This way we ensure to have the same behavior as before without affecting the main website.
Under some circumstances, the `scrollIntoView` function with the smooth behavior was affecting the main website and the scroll was being also made there.
> feat(botonic-react): Replace scroll behavior in scrollIntoView for a CSS property

- CHANGELOG.md
- package-lock.json
- packages/botonic-plugin-flow-builder/CHANGELOG.md
- packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
- packages/botonic-plugin-flow-builder/src/user-input/intent.ts
- packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
- packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
- packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
- packages/botonic-plugin-flow-builder/tests/tracking/track-keyword.test.ts
- packages/botonic-plugin-flow-builder/tests/tracking/track-knowledge-base.test.ts
- packages/botonic-plugin-flow-builder/tests/tracking/track-smart-intent.test.ts
- packages/botonic-plugin-hubtype-analytics/CHANGELOG.md
- packages/botonic-plugin-hubtype-analytics/README.md
- packages/botonic-plugin-hubtype-analytics/package.json
- packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent-smart.ts
- packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-intent.ts
- packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-keyword.ts
- packages/botonic-plugin-hubtype-analytics/src/event-models/ht-event-knowledge-base.ts
- packages/botonic-plugin-hubtype-analytics/src/types.ts
- packages/botonic-plugin-hubtype-analytics/tests/event-intent-smart.test.ts
- packages/botonic-plugin-hubtype-analytics/tests/event-intent.test.ts
- packages/botonic-plugin-hubtype-analytics/tests/event-keyword.test.ts
- packages/botonic-plugin-hubtype-analytics/tests/event-knowledge-base.test.ts
- packages/botonic-react/CHANGELOG.md
@botonic/plugin-hubtype-analytics
- add flow_thread_id, flow_node_id and flow_id in nlu events (keywords, intents, smart intents and knowledgebase)
- remove nlu_keyword_id, is the same id used for flow_node_id
@botonic/plugin-flow-builder
- add flow_thread_id, flow_node_id and flow_id when generate an events for  keywords, intents, smart intents and knowledgebase
Tests updated in boths plugins
> plugin-hubtype-analytics: add attributes in nlu events #BLT-1318 

- package-lock.json
- packages/botonic-core/src/models/legacy-types.ts
- packages/botonic-react/package.json
- packages/botonic-react/src/components/index.ts
- packages/botonic-react/src/components/whatsapp-media-carousel.tsx
- packages/botonic-react/src/components/whatsapp-product-list.tsx
- packages/botonic-react/src/util/functional.ts
- packages/botonic-react/tests/components/__snapshots__/whatsapp-media-carousel.test.jsx.snap
- packages/botonic-react/tests/components/whatsapp-media-carousel.test.jsx
- packages/botonic-react/tests/components/whatsapp-product-carousel.test.jsx
- packages/botonic-react/tests/components/whatsapp-product-list.test.jsx
- packages/botonic-react/tests/utils.test.js
Added types for [whatsapp order](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/sell-products-and-services/receive-responses) input type.
This input will be received from the backend when the user presses the button "Make order".
> Core: added types for whatsapp order

- package-lock.json
- packages/botonic-core/src/models/legacy-types.ts
- packages/botonic-react/src/components/index.ts
- packages/botonic-react/src/components/whatsapp-catalog.tsx
- packages/botonic-react/src/components/whatsapp-media-carousel.tsx
- packages/botonic-react/src/components/whatsapp-product-carousel.tsx
- packages/botonic-react/src/components/whatsapp-product-list.tsx
- packages/botonic-react/src/components/whatsapp-product.tsx
- packages/botonic-react/src/util/functional.ts
- packages/botonic-react/tests/components/__snapshots__/whatsapp-catalog.test.jsx.snap
- packages/botonic-react/tests/components/__snapshots__/whatsapp-media-carousel.test.jsx.snap
- packages/botonic-react/tests/components/__snapshots__/whatsapp-product-carousel.test.jsx.snap
- packages/botonic-react/tests/components/__snapshots__/whatsapp-product-list.test.jsx.snap
- packages/botonic-react/tests/components/__snapshots__/whatsapp-product.test.jsx.snap
- packages/botonic-react/tests/components/whatsapp-catalog.test.jsx
- packages/botonic-react/tests/components/whatsapp-media-carousel.test.jsx
- packages/botonic-react/tests/components/whatsapp-product-carousel.test.jsx
- packages/botonic-react/tests/components/whatsapp-product-list.test.jsx
- packages/botonic-react/tests/components/whatsapp-product.test.jsx
- packages/botonic-react/tests/utils.test.js
Added [Whatsapp Catalog](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/sell-products-and-services/share-products/) component to Botonic
Component used to send the Whatsapp Catalog linked to the bot's phone number.
```
render() {
return (
<WhatsappCatalog
body='Catalog sent from the bot'
thumbnailProductId='p6ng7fghmh'
footer="Catalog footer!!!"
/>
)
}
```
> React/Core: added Whatsapp Catalog component to Botonic

- package-lock.json
- packages/botonic-core/package.json
- packages/botonic-core/src/handoff.ts
- packages/botonic-core/src/models/legacy-types.ts
- packages/botonic-core/tests/handoff.test.ts
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/handoff.ts
- packages/botonic-react/package.json
- packages/botonic-react/src/index-types.ts
* Modify `InitialQueuePosition` event to be the new `QueuePositionChanged`.
* Update related necessary logic in flow builder plugin.
```
// routes.js
import Thanks from './actions/thanks'
import TransferAgent from './actions/transfer-agent'
import QueuePositionChanged from './actions/queue-position-changed'
export const routes = function ({ input }) {
return [
{
path: 'queue-position-changed',
type: 'case_event_queue_position_changed',
action: QueuePositionChanged,
},
{ path: 'agent', text: /^handoff$/i, action: TransferAgent },
{ path: 'thanks-for-contacting', action: Thanks },
]
}
```
```
// transfer-agent.jsx
import { HandOffBuilder, HelpdeskEvent } from '@botonic/core'
import { Text } from '@botonic/react'
import React from 'react'
export default class extends React.Component {
static …
```
> feat(core/plugin-flow-builder): add support for notifying queue position changed #BLT-1449

- examples/flow-builder-typescript/package.json
It is necessary to publish everything inside the folder for the example to work properly, just like the other examples. 
When applying the src/** filter, neither the rspack-entires folder nor the rspack.config.ts file was published.
> feat: remove files from package.json

- package-lock.json
- packages/botonic-core/CHANGELOG.md
- packages/botonic-core/package.json
- packages/botonic-core/src/models/legacy-types.ts
- packages/botonic-plugin-flow-builder/CHANGELOG.md
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
- packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
- packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
- packages/botonic-plugin-flow-builder/tests/keyword.test.ts
- packages/botonic-plugin-flow-builder/tests/smart-intent.test.ts
- add nluResult botonic-core in request.input
- set and unset nluResult in plugin-flow-builder
Update keyword and smart-intents test to check that request.input.nluResult is set in after pre function and unset after post function
> feat(core & plugin-flow-builder): add nluResult in input

- package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action/first-interaction.ts
- packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/intent.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/tracking.ts
- packages/botonic-plugin-flow-builder/src/types.ts
- packages/botonic-plugin-flow-builder/src/user-input/index.ts
- packages/botonic-plugin-flow-builder/src/utils.ts
- packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
- packages/botonic-plugin-flow-builder/tests/keyword.test.ts
- packages/botonic-plugin-flow-builder/tests/knowledge-base.test.ts
- packages/botonic-plugin-flow-builder/tests/smart-intent.test.ts
Add config for handoff with shadowing to allow keywords, smart-intents and knowledge base. By default all this responses are disabled when create a case with shadow
> feat(plugin-flow-builder): allow shadowing configuration BLT-1539 

- package-lock.json
- packages/botonic-core/package.json
- packages/botonic-core/src/models/legacy-types.ts
- packages/botonic-plugin-flow-builder/CHANGELOG.md
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action/first-interaction.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/user-input/intent.ts
- packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
- packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
- packages/botonic-plugin-flow-builder/tests/first-interaction.test.ts
- packages/botonic-plugin-flow-builder/tests/keyword.test.ts
- packages/botonic-plugin-flow-builder/tests/smart-intent.test.ts
In order to have available the detection of keywords, smart-intents and intents-babel in the first interaction, as long as the user input is of text type and there is no payload, a match with keywords, smart-intents or intents-babel will be searched. This information is stored in the request.inpu.nluResolution together with the payload pointing to the matched node.
In this way it is no longer necessary to look for the match within the action when it is the first interaction, since the necessary payload will be stored in the input.nluResolution.payload.
Update tests
> plugin-flow-builder: nluResolution available in first interaction

- .github/workflows/botonic-common-workflow.yml
- .github/workflows/botonic-docs-netlify-deploy.yml
- .github/workflows/botonic-docs-tests.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/pre-commit.yml
Adapt gh action code as of the following reminder:
https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
> fix: adapt actions to not use legacy cache

- packages/botonic-plugin-flow-builder/CHANGELOG.md
- packages/botonic-plugin-flow-builder/src/action/fallback.ts
- packages/botonic-plugin-flow-builder/src/action/first-interaction.ts
- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
- packages/botonic-plugin-flow-builder/src/action/payload.ts
- packages/botonic-plugin-flow-builder/src/api.ts
- packages/botonic-plugin-flow-builder/src/content-fields/flow-handoff.tsx
- packages/botonic-plugin-flow-builder/src/functions/conditional-country.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/types.ts
- packages/botonic-plugin-flow-builder/tests/conditional-country.test.ts
- packages/botonic-plugin-flow-builder/tests/first-interaction.test.ts
- packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
- packages/botonic-plugin-flow-builder/tests/knowledge-base.test.ts
- packages/botonic-plugin-flow-builder/tests/tracking/track-knowledge-base.test.ts
- packages/botonic-react/src/util/webchat.ts
- packages/botonic-react/src/webchat/webchat.tsx
plugin-flow-builder does not need to receive the locale in any function. Always use system_locale from session to generate contents.
Update all tests
> plugin-flow-builder: no need to receive the locale in any function #BLT-1593 

- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/types.ts
- packages/botonic-plugin-google-translation/src/index.ts
- packages/botonic-plugin-hubtype-analytics/src/index.ts
- packages/botonic-plugin-hubtype-analytics/tests/helpers/index.ts
- packages/botonic-plugin-knowledge-bases/src/index.ts
- packages/botonic-react/src/components/message/message-feedback.tsx
- packages/botonic-react/src/webchat/tracking.ts
In this PR there are changes in several plugins that are necessary for the next version (0.35.0)
**@botonic/plugin-hubtype-analytics**
- Uses BotContext instead of BotRequest
- Remove the optional functions that could be passed in through the constructor to obtain the locale and the country
**@botonic/react**
- Creates a hook for the feedback tracking function of a knowledge base message. Inside this hook the request is recreated as a BotContext  (in the frontend there is no BotContext) which is what the hubtype analytics plugin needs to receive.
**@botonic/plugin-flow-builder**
- Removes the getLocale function that was passed through the constructor
**@botonic/plugin-knowledge-bases**
- use BotContext instead of BotRequest
**@botonic/plugin-google-translation**
- use getUserLocale …
> Some fixes before 0.35.0

- packages/botonic-cli/src/botonic-api-service.ts
- packages/botonic-cli/src/interfaces.ts
The v1 and v2 of users endpoints are deprecated.
Ideally we should have a `v?/users/me/` in the external API, but at least it allows to remove the v1 and v2 endpoitns from the back end.
Also it uses the /v1/sign-up/ endpoint for creation
It removes all teh unnecessary attributes from Me interface to leave only the ones that makes sense for botonic.
> feat(botonic-cli): Use v3 of users' endpoints and sign-up specific endpoint, and simplify the Me type

- package-lock.json
- packages/botonic-plugin-flow-builder/CHANGELOG.md
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/tests/execute-start-conversation.test.ts
- packages/botonic-plugin-flow-builder/tests/first-interaction.test.ts
- packages/botonic-plugin-flow-builder/tests/helpers/flows/basic.ts
- packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
- packages/botonic-plugin-flow-builder/tests/tracking/track-smart-intent.test.ts
plugin-flow-builder always adds match contents with some nlu when bot pass from conversation start node. Until now it only added contents of a match with NLU when it was the first interaction.
Update basicFlow, now smart intents titles are in snake_case.
Add a test to check that executeConversationStart always add match of keywords or smart intents in all interactions.
> feat(plugin-flow-builder): always adds match contents with some nlu 

- package-lock.json
- packages/botonic-plugin-ai-agents/package.json
- packages/botonic-plugin-ai-agents/src/ai-agent-client.ts
- packages/botonic-plugin-ai-agents/src/constants.ts
- packages/botonic-plugin-ai-agents/src/errors.ts
- packages/botonic-plugin-ai-agents/src/index.ts
- packages/botonic-plugin-ai-agents/src/types.ts
- packages/botonic-plugin-ai-agents/tsconfig.esm.json
- packages/botonic-plugin-ai-agents/tsconfig.json
Create a plugin-ai-agent. This plugin have the inference function. This function call a different endpoint when the bot is running in local development because the bot not have the message_id. When the plugin call the test endpoint the agent don't have memory.
> plugin-ai-agent: create new plugin-ai-agent #BLT-1633

- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/filters/index.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/types.ts
- packages/botonic-plugin-flow-builder/tests/ai-agent.test.ts
- packages/botonic-plugin-flow-builder/tests/content-filters/remove-button.test.ts
- packages/botonic-plugin-flow-builder/tests/helpers/utils.ts
Be able to add contentFilters in the plugin's settings.
These filters will be applied to the contents just before tracking.
The AiAgent feature is unfinished, for now I skip the tests and the flow builder constructor will set undefined so the AiAgent will never work. When we finish the feature I will activate it again.
Add a test to check that a button can be removed with a filter
> plugin-flow-builder: add contentFilters #BLT-1683

- package-lock.json
- packages/botonic-react/CHANGELOG.md
- packages/botonic-react/package.json
- packages/botonic-react/src/webview-app.tsx
WebviewApp to retrieve user_id and bot_id from new url generated by backend and using them to retrieve bot session via external api.
> feat: retrieve context for webviews from new external api endpoint for bot session context

- package-lock.json
- packages/botonic-plugin-ai-agents/package.json
- packages/botonic-plugin-ai-agents/src/index.ts
- packages/botonic-plugin-ai-agents/src/types.ts
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action/ai-agent.ts
- packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
- packages/botonic-plugin-flow-builder/src/api.ts
- packages/botonic-plugin-flow-builder/src/content-fields/flow-ai-agent.tsx
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/ai-agent.ts
- packages/botonic-plugin-flow-builder/src/content-fields/hubtype-fields/common.ts
- packages/botonic-plugin-flow-builder/src/types.ts
Rename tools to active_tools in ai-agent node(plugin-flow-builder)
Rename tools to activeTools in aiAgentArgs (plugin-ai-agents)
> plugin flow-builder & ai-agents: rename tools to active_tools in flow ai-agent node

- package-lock.json
- packages/botonic-react/CHANGELOG.md
- packages/botonic-react/package.json
- packages/botonic-react/src/components/button/index.tsx
- packages/botonic-react/src/components/markdown.js
- packages/botonic-react/src/components/message/index.jsx
- packages/botonic-react/src/util/environment.js
- packages/botonic-react/src/webchat/webchat.tsx
- packages/botonic-react/tests/components/render-markdown.test.jsx
Set the default target parameter in links depending if the webchat is opened within a iOS/Android webview (`_self`) or not (`_blank`)
If the webchat is displayed within an iOS webview (inside an iOS App), the links weren't working because the default target was `_blank` and on iOS webviews the links only work if the target is `_self`.
Create a new `isInWebView` function to detect if the environment is a webview in iOS/Android.
> react: Detect automatically if the webchat is running in iOS/Android webview

- packages/botonic-core/src/models/legacy-types.ts
Add a missing `salesforce` attribute inside the `Input.context` type used when the organisation or the bot are integrated with Salesforce.
Missing attribute in `Input` type
> style(core): Add missing salesforce attribute inside Input.context type

- packages/botonic-react/src/webchat/context/types.ts
Set the type of the `user` argument of the `updateUser` function as `Partial<ClientUser>` because you may want to update just part of the user attributes, not all of them.
If you wanted to update just some user attributes, you would get a Typescript error.
> fix(react): Fix type of user argument in updateUser function

- package-lock.json
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-react/CHANGELOG.md
- packages/botonic-react/package.json
- packages/botonic-react/src/webchat/input-panel/send-button.tsx
- packages/botonic-react/src/webchat/theme/default-theme.ts
Change behaviour to use custom buttons in input panel component. If you define a custom component for some button (Attachments, Emojis or SendButton) you don't need to put enable attribute set to true. If you define a custo button but you set enable to false, the custom button is not used.
> botonic-react: input panel buttons no need enable attribute set to true to be used

- .github/workflows/botonic-ci-test-all-packages.yml
- .github/workflows/botonic-plugin-ai-agents.yml
- packages/botonic-plugin-ai-agents/babel.config.js
- packages/botonic-plugin-ai-agents/jest.config.js
- packages/botonic-plugin-ai-agents/package.json
- packages/botonic-plugin-ai-agents/src/index.ts
- packages/botonic-plugin-ai-agents/src/runner.ts
- packages/botonic-plugin-ai-agents/src/types.ts
- packages/botonic-plugin-ai-agents/tests/agent-builder.test.ts
- packages/botonic-plugin-ai-agents/tests/runner.test.ts
- packages/botonic-plugin-ai-agents/tsconfig.tests.json
- packages/botonic-plugin-flow-builder/src/action/ai-agent.ts
- packages/botonic-plugin-flow-builder/src/types.ts
- packages/botonic-plugin-flow-builder/tests/__mocks__/ai-agent.ts
plugin-ai-agents return an object with interface InferenceResponse. With this object we can know the tools executed or if ai agents not respond (exit is true). In the future we include in this response the guardrails info.
```typescript
export type InferenceResponse = {
messages: AgenticOutputMessage[]
toolsExecuted: string[]
exit: boolean
inputGuardrailTriggered: boolean
outputGuardrailTriggered: boolean
} | undefined
```
plugin -flow-builder use this object to generate response, in the future PR use this info to track ai-agents responses
Update mockAiAgentResponse to pass tests
> plugin-ai-agents & plugin-flow-builder: create InferenceResponse for ai-agents #BLT-1803

- packages/botonic-core/src/models/hubtype-analytics.ts
- packages/botonic-core/src/models/index.ts
- packages/botonic-plugin-flow-builder/src/action/fallback.ts
- packages/botonic-plugin-flow-builder/src/action/knowledge-bases.ts
- packages/botonic-plugin-flow-builder/src/action/payload.ts
- packages/botonic-plugin-flow-builder/src/tracking.ts
- packages/botonic-plugin-flow-builder/src/user-input/keyword.ts
- packages/botonic-plugin-flow-builder/src/user-input/smart-intent.ts
- packages/botonic-plugin-flow-builder/tests/messages/flow-rating.test.ts
- packages/botonic-plugin-hubtype-analytics/src/types.ts
- packages/botonic-react/src/webchat/tracking.ts
Refactor hubtype-analytics, pass all interfaces and enums to @botonic/core to be able to import them in @botonic/plugin-flow-builder and @botonic/react to type events
Import from @botonic/core interfaces and enums and export from @botnic/plugin-hubtype-analytics, this way it is not necessary to change the imports in the bots.
In the last commit I create a functions to track custom events a feedback events from webchat.
> refactor: create hubtype-analytics interfaces and enums in @botonic/core #BLT-1806

- packages/botonic-plugin-ai-agents/src/guardrails/input.ts
- packages/botonic-plugin-ai-agents/tests/guardrails/input.test.ts
Use only last message when running input Guardrail.
> Fix: Use only last message on guardrail

- packages/botonic-plugin-flow-builder/CHANGELOG.md
- packages/botonic-plugin-flow-builder/src/action/index.tsx
- packages/botonic-plugin-flow-builder/src/constants.ts
- packages/botonic-plugin-flow-builder/src/content-fields/flow-ai-agent.tsx
Change the payload used in the buttons created by the AI Agent, currently `do-nothing`  to `fb-do-nothing`
The current one is already used by the delivery team.
> feat: change do-nothing payload #BLT-1830

- package-lock.json
- packages/botonic-plugin-flow-builder/CHANGELOG.md
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/content-fields/whatsapp-button-list/flow-whatsapp-button-list.tsx
Fix the value set in the `payload` prop when returning the value in the `toBotonic` method of `FlowWhatsappButtonList` for non WhatsApp channels.
Clicking a button of a `FlowWhatsappButtonList` component rendered in a webchat was not redirecting to the expected content.
> fix(plugin-flow-builder): Fix payload in toBotonic method of FlowWhatsappButtonList

- package-lock.json
- packages/botonic-plugin-flow-builder/CHANGELOG.md
- packages/botonic-plugin-flow-builder/package.json
- packages/botonic-plugin-flow-builder/src/action/payload.ts
- packages/botonic-plugin-flow-builder/src/index.ts
- packages/botonic-plugin-flow-builder/src/types.ts
Extract the logic that obtains the submitted rating information into a function so it can be exported and used in the bots.
If the bot needs to do some extra logic with the rating selected, it needs to have a way to obtain the rating value selected by the user.
After exporting this new `getRatingButtonClicked` function, we could add a Plugin in the bot to do some extra logic in the `pre` method when a rating is submitted:
```ts
import { AGENT_RATING_PAYLOAD, getRatingSubmittedInfo } from '@botonic/plugin-flow-builder'
...
async pre(request: PluginPreRequest<BotPlugins>) {
const { payload, cmsPlugin } = getRequestData(request)
const agentRatingPayloadRegex = new RegExp(`^${AGENT_RATING_PAYLOAD}.*`)
if (agentRatingPayloadRegex.test(payload)) {
const { value } = …
```
> FlowBuilder: Export function to obtain the rating value selected
